export type DailyStudy = {
  id: string;
  title: string;
  scripture: string;
  verse: string;
  insight: string;
  reflection: string;
  themes: string[]; // peace, strength, love, faith, guidance, forgiveness, gratitude, finances, health, parenting, career, purpose
};

export const dailyStudies: DailyStudy[] = [
  {
    id: "1",
    title: "The Promise of God's Peace",
    scripture: "John 14:27",
    verse: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.",
    insight: "Jesus offers a peace that's fundamentally different from what the world offers. Worldly peace depends on circumstances - having enough money, health, or success. But Christ's peace is a settled confidence in God's sovereign control, regardless of external conditions.",
    reflection: "What situations in your life are currently disturbing your peace? How might Jesus' promise of 'not as the world gives' change your perspective on finding peace?",
    themes: ["peace", "trust", "faith"],
  },
  {
    id: "2",
    title: "Strength from the Lord",
    scripture: "Psalm 46:1",
    verse: "God is our refuge and strength, an ever-present help in trouble.",
    insight: "This psalm reminds us that God is not a distant deity, but an 'ever-present' help. The Hebrew word for 'strength' here implies security and might. God doesn't just give us strength; He IS our strength. When we feel weak, we can run to Him as our refuge.",
    reflection: "Where do you typically turn for strength when life gets difficult? How might your life look different if God was your first refuge rather than your last resort?",
    themes: ["strength", "refuge", "hope"],
  },
  {
    id: "3",
    title: "Love as Our Identity",
    scripture: "1 John 4:19",
    verse: "We love because he first loved us.",
    insight: "Our capacity to love others flows from understanding how deeply God loves us. This verse reveals that love is not primarily an emotion we generate, but a response to the love we've received. When we grasp God's unconditional love, it overflows naturally toward others.",
    reflection: "Do you truly believe God loves you unconditionally? How might a deeper understanding of God's love for you transform how you love difficult people in your life?",
    themes: ["love", "identity", "grace"],
  },
  {
    id: "4",
    title: "Faithful in Little Things",
    scripture: "Luke 16:10",
    verse: "Whoever can be trusted with very little can also be trusted with much, and whoever is dishonest with very little will also be dishonest with much.",
    insight: "God often tests our character in small, seemingly insignificant matters before entrusting us with greater responsibilities. This principle applies especially to finances. How we handle $10 reveals what we'd do with $10,000. Faithfulness isn't measured by the amount but by our attitude and integrity.",
    reflection: "What 'little things' is God asking you to be faithful with right now? How might your stewardship of small responsibilities prepare you for future opportunities?",
    themes: ["stewardship", "faithfulness", "finances"],
  },
  {
    id: "5",
    title: "Honor God with Firstfruits",
    scripture: "Proverbs 3:9-10",
    verse: "Honor the Lord with your wealth, with the firstfruits of all your crops; then your barns will be filled to overflowing, and your vats will brim over with new wine.",
    insight: "The 'firstfruits' principle means giving God the first and best portion of our income, not the leftovers. This practice demonstrates that we trust God as our provider. The promise of overflow isn't about getting rich, but about experiencing God's supernatural provision when we put Him first financially.",
    reflection: "Do you give God your 'firstfruits' or your leftovers? What might change in your heart and finances if you honored God first before paying bills or spending on yourself?",
    themes: ["finances", "stewardship", "generosity"],
  },
  // 6. Finances/Contentment - matches Devotional #6: Contentment is Wealth
  {
    id: "6",
    title: "The Secret of Contentment",
    scripture: "Philippians 4:12-13",
    verse: "I know what it is to be in need, and I know what it is to have plenty. I have learned the secret of being content in any and every situation, whether well fed or hungry, whether living in plenty or in want. I can do all this through him who gives me strength.",
    insight: "Paul reveals that contentment is learned, not natural. It's a 'secret' that comes through experiencing both abundance and lack while depending on Christ through both. The famous 'I can do all things' isn't about achieving worldly success, but about enduring any circumstance with Christ's strength. True contentment is Christ-sufficiency, not self-sufficiency.",
    reflection: "What circumstances are currently testing your contentment? How might Christ's strength enable you to be content regardless of what you have or don't have?",
    themes: ["contentment", "strength", "peace"],
  },
  // 7. Finances/Generosity - matches Devotional #7: Generosity Opens Heaven's Windows
  {
    id: "7",
    title: "Honor God with Firstfruits",
    scripture: "Proverbs 3:9-10",
    verse: "Honor the Lord with your wealth, with the firstfruits of all your crops; then your barns will be filled to overflowing, and your vats will brim over with new wine.",
    insight: "The 'firstfruits' principle means giving God the first and best portion of our income, not the leftovers. This practice demonstrates that we trust God as our provider. The promise of overflow isn't about getting rich, but about experiencing God's supernatural provision when we put Him first financially.",
    reflection: "Do you give God your 'firstfruits' or your leftovers? What might change in your heart and finances if you honored God first before paying bills or spending on yourself?",
    themes: ["finances", "stewardship", "generosity"],
  },
  // 8. Career/Work - matches Devotional #8: Your Business Is Your Ministry
  {
    id: "8",
    title: "Working for God's Glory",
    scripture: "1 Corinthians 10:31",
    verse: "So whether you eat or drink or whatever you do, do it all for the glory of God.",
    insight: "Paul includes even mundane activities like eating and drinking to show that every action can glorify God when done with the right heart. This transforms our view of work - it's not just about earning money or advancing careers, but about honoring God through excellence, integrity, and service. Even secular work becomes sacred when done 'unto the Lord.'",
    reflection: "How might your approach to work change if you viewed your job as a calling to glorify God? What would it look like to work 'unto the Lord' this week?",
    themes: ["work", "purpose", "calling"],
  },
  // 9. Career/Integrity - matches Devotional #9: Integrity Over Profit
  {
    id: "9",
    title: "Working for God's Glory",
    scripture: "1 Corinthians 10:31",
    verse: "So whether you eat or drink or whatever you do, do it all for the glory of God.",
    insight: "Paul includes even mundane activities like eating and drinking to show that every action can glorify God when done with the right heart. This transforms our view of work - it's not just about earning money or advancing careers, but about honoring God through excellence, integrity, and service. Even secular work becomes sacred when done 'unto the Lord.'",
    reflection: "How might your approach to work change if you viewed your job as a calling to glorify God? What would it look like to work 'unto the Lord' this week?",
    themes: ["work", "purpose", "calling", "integrity"],
  },
  {
    id: "10",
    title: "Healing and Wholeness",
    scripture: "Psalm 147:3",
    verse: "He heals the brokenhearted and binds up their wounds.",
    insight: "God's healing extends beyond physical ailments to emotional and spiritual wounds. The phrase 'binds up' is a tender image of God carefully bandaging our hurts like a loving caregiver. He doesn't just cover wounds; He actively heals them. Sometimes healing is instant, sometimes gradual, but God is always the Great Physician working toward our wholeness.",
    reflection: "What broken areas of your heart need God's healing touch? Are you willing to let Him into those painful places to bind up your wounds?",
    themes: ["healing", "comfort", "restoration"],
  },
  {
    id: "11",
    title: "Wisdom for Parents",
    scripture: "Deuteronomy 6:6-7",
    verse: "These commandments that I give you today are to be on your hearts. Impress them on your children. Talk about them when you sit at home and when you walk along the road, when you lie down and when you get up.",
    insight: "This passage reveals that spiritual formation happens in everyday moments, not just formal teaching times. The instruction to talk about God's truth 'when you sit... walk... lie down... get up' means integrating faith into all of life. Children learn more from what they observe in our daily lives than from our intentional lessons.",
    reflection: "How naturally does faith conversation flow in your home? What ordinary moments could become opportunities to 'impress' God's truth on your children?",
    themes: ["parenting", "family", "faith"],
  },
  {
    id: "12",
    title: "Working for God's Glory",
    scripture: "1 Corinthians 10:31",
    verse: "So whether you eat or drink or whatever you do, do it all for the glory of God.",
    insight: "Paul includes even mundane activities like eating and drinking to show that every action can glorify God when done with the right heart. This transforms our view of work - it's not just about earning money or advancing careers, but about honoring God through excellence, integrity, and service. Even secular work becomes sacred when done 'unto the Lord.'",
    reflection: "How might your approach to work change if you viewed your job as a calling to glorify God? What would it look like to work 'unto the Lord' this week?",
    themes: ["work", "purpose", "calling"],
  },
  {
    id: "13",
    title: "Created with Purpose",
    scripture: "Jeremiah 29:11",
    verse: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.",
    insight: "This beloved verse was originally spoken to Israel in exile, reminding them that even in hardship, God had a purpose and plan. The same is true for us. God's plans for us are good, filled with hope, and aimed at our ultimate prosperity (which often looks different from worldly success). Our job is to trust His timing and process.",
    reflection: "Do you believe God has a good plan for your life, even when circumstances seem contrary? What might it look like to trust His plans over your own agenda?",
    themes: ["purpose", "hope", "trust"],
  },
  {
    id: "14",
    title: "Courage Over Fear",
    scripture: "Joshua 1:9",
    verse: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.",
    insight: "God commanded Joshua to be courageous three times in this chapter. Courage isn't the absence of fear, but choosing to obey despite fear. The foundation for courage is God's presence - 'the Lord your God will be with you.' We can face anything when we remember we never face it alone. God goes before us, beside us, and behind us.",
    reflection: "What are you afraid of today? How might remembering God's constant presence give you courage to take the next step?",
    themes: ["courage", "fear", "strength"],
  },
  {
    id: "15",
    title: "Unity in Relationships",
    scripture: "Ephesians 4:2-3",
    verse: "Be completely humble and gentle; be patient, bearing with one another in love. Make every effort to keep the unity of the Spirit through the bond of peace.",
    insight: "Unity doesn't mean uniformity - we can disagree while remaining united in Christ. Notice the active verbs: 'be humble,' 'be patient,' 'bearing with,' 'make every effort.' Unity requires intentional work. The qualities listed - humility, gentleness, patience, love, peace - are the building blocks of healthy relationships.",
    reflection: "Which relationship in your life needs more humility, patience, or gentleness? What specific step could you take today to 'make every effort' toward unity?",
    themes: ["relationships", "unity", "love"],
  },
  {
    id: "16",
    title: "The Secret of Contentment",
    scripture: "Philippians 4:12-13",
    verse: "I know what it is to be in need, and I know what it is to have plenty. I have learned the secret of being content in any and every situation, whether well fed or hungry, whether living in plenty or in want. I can do all this through him who gives me strength.",
    insight: "Paul reveals that contentment is learned, not natural. It's a 'secret' that comes through experiencing both abundance and lack while depending on Christ through both. The famous 'I can do all things' isn't about achieving worldly success, but about enduring any circumstance with Christ's strength. True contentment is Christ-sufficiency, not self-sufficiency.",
    reflection: "What circumstances are currently testing your contentment? How might Christ's strength enable you to be content regardless of what you have or don't have?",
    themes: ["contentment", "strength", "peace"],
  },
  {
    id: "17",
    title: "Perseverance Through Trials",
    scripture: "Romans 5:3-4",
    verse: "Not only so, but we also glory in our sufferings, because we know that suffering produces perseverance; perseverance, character; and character, hope.",
    insight: "This passage reveals God's process for spiritual growth: suffering → perseverance → character → hope. We don't seek suffering, but when it comes, God uses it to develop qualities that can't be formed any other way. Perseverance is like a spiritual muscle that only grows under resistance. The ultimate product is hope - confident expectation in God's faithfulness.",
    reflection: "What trial are you currently persevering through? Can you see how God might be using it to develop character and deepen your hope in Him?",
    themes: ["perseverance", "character", "hope"],
  },
  {
    id: "18",
    title: "The Fruit of Self-Control",
    scripture: "Proverbs 25:28",
    verse: "Like a city whose walls are broken through is a person who lacks self-control.",
    insight: "Ancient cities depended on walls for protection; without them, they were vulnerable to every enemy. Similarly, self-control protects us from destructive impulses, habits, and decisions. The Holy Spirit empowers us with self-control as part of His fruit (Galatians 5:23). It's not white-knuckled willpower but Spirit-enabled discipline that guards our hearts and lives.",
    reflection: "What area of your life feels like 'broken walls' - lacking protection and discipline? What would it look like to invite the Holy Spirit's power into that area?",
    themes: ["self-control", "discipline", "holiness"],
  },
  {
    id: "19",
    title: "Joy as Our Strength",
    scripture: "Psalm 16:11",
    verse: "You make known to me the path of life; you will fill me with joy in your presence, with eternal pleasures at your right hand.",
    insight: "True joy is found in God's presence, not in circumstances. This verse connects joy with knowing God's path for our lives. When we walk in His will, in His presence, joy naturally flows. Unlike happiness, which depends on happenings, joy is rooted in our relationship with God and the eternal perspective He gives us.",
    reflection: "Where are you searching for joy? How might intentionally spending time in God's presence fill you with the joy you're seeking?",
    themes: ["joy", "presence", "worship"],
  },
  {
    id: "20",
    title: "Humble Service",
    scripture: "Mark 10:45",
    verse: "For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many.",
    insight: "Jesus redefines greatness as service. If the King of kings came to serve, how much more should we? True humility doesn't think less of itself but thinks of itself less. Serving others is how we follow Christ's example most directly. Every act of service, no matter how small, reflects the heart of Jesus who gave His life for us.",
    reflection: "Who can you serve today in a practical way? How might serving others actually be a way of serving and honoring Christ Himself?",
    themes: ["humility", "service", "love"],
  },
  {
    id: "21",
    title: "The Sabbath Principle",
    scripture: "Mark 2:27",
    verse: "Then he said to them, 'The Sabbath was made for man, not man for the Sabbath.'",
    insight: "Rest isn't just a suggestion - it's a divine design. God established Sabbath not as a burden but as a gift for our well-being. In a culture that glorifies busyness, choosing rest is an act of trust, declaring that God can sustain the world without our constant effort. Regular rest protects us from burnout and reminds us that our worth isn't found in productivity.",
    reflection: "When was the last time you took a full day of rest? What keeps you from embracing the gift of Sabbath?",
    themes: ["rest", "trust", "wisdom"],
  },
  {
    id: "22",
    title: "The Value of Godly Friends",
    scripture: "Proverbs 27:17",
    verse: "As iron sharpens iron, so one person sharpens another.",
    insight: "Authentic Christian friendship involves both encouragement and accountability. Just as iron sharpens iron through friction, godly friends challenge us to grow. They celebrate our victories, confront our sin, pray for us faithfully, and speak truth in love. This kind of friendship doesn't happen by accident - it requires vulnerability, time, and commitment to each other's spiritual growth.",
    reflection: "Do you have friends who sharpen you spiritually? Are you being that kind of friend to others?",
    themes: ["friendship", "accountability", "growth"],
  },
  {
    id: "23",
    title: "Faith in the Silence",
    scripture: "Habakkuk 2:3",
    verse: "For the revelation awaits an appointed time; it speaks of the end and will not prove false. Though it linger, wait for it; it will certainly come and will not delay.",
    insight: "Sometimes God's timing feels painfully slow. We pray for breakthrough that doesn't come, seek answers that remain hidden, wait for promises that seem delayed. But God's silence doesn't mean absence. He's often working behind the scenes, preparing both the answer and us to receive it. Faith means trusting God's timing even when we can't understand it.",
    reflection: "What have you been waiting for God to do? How might this season of waiting be developing your character and deepening your trust?",
    themes: ["faith", "waiting", "trust"],
  },
  {
    id: "24",
    title: "Living Legacy",
    scripture: "Psalm 78:4",
    verse: "We will not hide them from their descendants; we will tell the next generation the praiseworthy deeds of the Lord, his power, and the wonders he has done.",
    insight: "Your faith isn't just for you - it's meant to be passed down. The way you live today sets a spiritual trajectory for generations you'll never meet. Children learn more from what they observe than what they're taught. When they see authentic faith - including your struggles, doubts, and how you trust God through them - it shapes their own relationship with Him.",
    reflection: "What spiritual legacy are you building? If the next generation only knew God through watching your life, what would they learn about Him?",
    themes: ["legacy", "family", "faith"],
  },
  {
    id: "25",
    title: "The Freedom of Forgiveness",
    scripture: "Matthew 6:14-15",
    verse: "For if you forgive other people when they sin against you, your heavenly Father will also forgive you. But if you do not forgive others their sins, your Father will not forgive your sins.",
    insight: "Unforgiveness is like drinking poison and expecting the other person to die. It chains you to the past and gives your offender continued power over your emotional state. Jesus links our forgiveness from God to our forgiveness of others - not because we earn God's grace, but because truly grasping His forgiveness transforms how we treat those who hurt us. Forgiveness doesn't excuse the wrong or mean reconciliation is automatic, but it releases you from bitterness's prison.",
    reflection: "Is there someone you're holding unforgiveness toward? What would it cost you to forgive? What is unforgiveness already costing you?",
    themes: ["forgiveness", "freedom", "healing"],
  },
  {
    id: "26",
    title: "Work as Worship",
    scripture: "1 Corinthians 10:31",
    verse: "So whether you eat or drink or whatever you do, do it all for the glory of God.",
    insight: "Paul includes even eating and drinking to show that every activity can glorify God when done with the right heart. Your 'secular' work becomes 'sacred' when performed as an offering to God. Excellence at work honors Him. Integrity in business dealings witnesses to Him. Kindness to difficult coworkers reflects Him. You don't need to be in 'full-time ministry' to serve God full-time - you're already there.",
    reflection: "How would your approach to work change if you viewed every task as an opportunity to worship God? What would excellence look like in your specific role?",
    themes: ["work", "purpose", "excellence"],
  },
  {
    id: "27",
    title: "Boldness in the Spirit",
    scripture: "Acts 4:31",
    verse: "After they prayed, the place where they were meeting was shaken. And they were all filled with the Holy Spirit and spoke the word of God boldly.",
    insight: "The early church didn't pray for safety or comfort when persecuted - they prayed for boldness to keep preaching. Their confidence wasn't in their own abilities but in the Holy Spirit's empowerment. True boldness isn't recklessness or arrogance; it's Spirit-enabled courage to speak truth and live out faith regardless of consequences. When we feel timid, we can ask God for the same boldness He gave the apostles.",
    reflection: "Where do you need more boldness in your faith? What fears hold you back from speaking up or stepping out for God?",
    themes: ["boldness", "courage", "witness"],
  },
  {
    id: "28",
    title: "Breaking Free from the Past",
    scripture: "Isaiah 43:18-19",
    verse: "Forget the former things; do not dwell on the past. See, I am doing a new thing! Now it springs up; do you not perceive it?",
    insight: "God doesn't want you trapped by your past - whether it's past failures, past hurts, or even past successes. While we should learn from history, we're not meant to live there. God is always doing something new, but we miss it when we're stuck looking backward. The same power that raised Jesus from the dead can resurrect dead dreams, restore broken relationships, and redeem wasted years. Your best days aren't behind you - they're ahead.",
    reflection: "What past experience - good or bad - are you having trouble letting go of? How might focusing on what God is doing now free you to move forward?",
    themes: ["freedom", "new beginnings", "hope"],
  },
  {
    id: "29",
    title: "The Body of Christ",
    scripture: "1 Corinthians 12:27",
    verse: "Now you are the body of Christ, and each one of you is a part of it.",
    insight: "The church isn't just an organization - it's an organism, a living body with Christ as the head. Every believer has a unique role and essential function. Just as a body can't function if parts are missing or not working together, the church needs every member operating in their gifts. You're not just attending church - you are the church. Your participation, gifts, and presence matter more than you realize.",
    reflection: "What's your role in the body of Christ? Are you using your gifts to serve the church, or are you sitting on the sidelines?",
    themes: ["church", "unity", "purpose"],
  },
  {
    id: "30",
    title: "Present with God",
    scripture: "Psalm 46:10",
    verse: "Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.",
    insight: "In our noisy, hurried world, being still is countercultural. But God invites us to stop striving, stop performing, and simply be present with Him. Stillness isn't about physical inactivity but about internal quietness - creating space to hear His voice, experience His presence, and remember His sovereignty. When we're still, we remember that He is God and we are not, and that truth brings profound peace.",
    reflection: "When was the last time you were truly still before God - no agenda, no requests, just being with Him? What would it look like to build stillness into your daily rhythm?",
    themes: ["presence", "peace", "worship"],
  },
  // Days 31-90: Studies correlated with devotionals 31-90
  {
    id: "31",
    title: "Asking for Wisdom",
    scripture: "Proverbs 3:5-6",
    verse: "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.",
    insight: "Wisdom isn't just knowledge - it's the ability to apply God's truth to your specific situation. James tells us God gives wisdom generously when we ask. But asking requires humility to admit we don't have all the answers and faith to believe God will guide us. True wisdom involves trusting God more than our own logic, submitting our decisions to Him, and following His direction even when it challenges our understanding.",
    reflection: "What decision are you facing that requires divine wisdom? Have you truly asked God for guidance, or are you just informing Him of your plans?",
    themes: ["wisdom", "guidance", "trust"],
  },
  {
    id: "32",
    title: "Living in the Now",
    scripture: "Matthew 6:34",
    verse: "Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.",
    insight: "Jesus commands us not to worry about tomorrow because anxiety robs us of today's joy. Regret anchors us in the past; anxiety drags us into the future. But life happens in the present. Today is the only day you can actually live. When you're fully present - experiencing, engaging, and embracing this moment - you discover that God's grace is sufficient for each day's challenges.",
    reflection: "What past regrets or future anxieties are stealing your ability to be fully present today? How can you practice being more mindful of this moment?",
    themes: ["presence", "peace", "gratitude"],
  },
  {
    id: "33",
    title: "Your Unique Race",
    scripture: "Hebrews 12:1-2",
    verse: "Therefore, since we are surrounded by so great a cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us, fixing our eyes on Jesus.",
    insight: "God marked out a specific race for you - not for anyone else. When you compare your mile 3 to someone else's mile 15, you'll always feel behind. But comparison is irrelevant when each runner has a unique track. The key is to fix your eyes on Jesus, not on other runners. Run your race, not theirs. Your pace, progress, and path are between you and God alone.",
    reflection: "Who are you comparing yourself to, and how is it affecting your joy? What would change if you focused solely on your own race and Jesus as your finish line?",
    themes: ["identity", "perseverance", "focus"],
  },
  {
    id: "34",
    title: "Protecting Your Heart",
    scripture: "Psalm 19:14",
    verse: "May these words of my mouth and this meditation of my heart be pleasing in your sight, Lord, my Rock and my Redeemer.",
    insight: "Your heart is the command center of your life. What you allow into it - through media, relationships, thoughts, and experiences - shapes who you become. David understood this and asked God to help him guard not just his words but also the meditations of his heart. Protecting your heart isn't about building walls; it's about installing filters that keep toxic influences out and godly truth in.",
    reflection: "What inputs in your life need better filtering? What would change if you evaluated everything by asking, 'Will this help or hurt my heart's health?'",
    themes: ["purity", "discernment", "transformation"],
  },
  {
    id: "35",
    title: "The Gratitude Advantage",
    scripture: "Psalm 100:4",
    verse: "Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name.",
    insight: "Gratitude is the gateway to God's presence. When you approach God with thanksgiving, your perspective shifts from what you lack to what you have, from problems to blessings, from complaint to contentment. Gratitude isn't denial of difficulties; it's acknowledgment that God is good despite them. A grateful heart attracts joy, repels bitterness, and opens you to experience more of God's goodness.",
    reflection: "List three things you're grateful for right now, even if life is hard. How does expressing gratitude change how you feel about your current situation?",
    themes: ["gratitude", "worship", "perspective"],
  },
  {
    id: "36",
    title: "Power in Weakness",
    scripture: "2 Corinthians 4:7",
    verse: "But we have this treasure in jars of clay to show that this all-surpassing power is from God and not from us.",
    insight: "Paul describes believers as 'jars of clay' - fragile, ordinary, cracked containers. Why? To make it obvious that any power displayed comes from God, not us. Your weakness isn't a liability; it's God's opportunity. When you're inadequate, God's adequacy shines. When you're broken, His strength fills the cracks. Stop hiding your weakness and start leaning into God's power.",
    reflection: "What area of weakness are you ashamed of? How might God want to display His strength through that very weakness?",
    themes: ["weakness", "power", "humility"],
  },
  {
    id: "37",
    title: "Forgiveness Breaks Chains",
    scripture: "Ephesians 4:31-32",
    verse: "Get rid of all bitterness, rage and anger, brawling and slander, along with every form of malice. Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.",
    insight: "Unforgiveness is like swallowing poison and expecting the other person to die. It chains you to the past and gives the offender ongoing power over your emotional and spiritual well-being. But forgiveness breaks those chains. It's not about them; it's about your freedom. When you forgive as Christ forgave you - completely, sacrificially, immediately - you're released from bitterness's prison.",
    reflection: "Who do you need to forgive? What would it look like to release them today, not because they deserve it, but because you need freedom?",
    themes: ["forgiveness", "freedom", "healing"],
  },
  {
    id: "38",
    title: "The Power of Words",
    scripture: "Proverbs 12:18",
    verse: "The words of the reckless pierce like swords, but the tongue of the wise brings healing.",
    insight: "Words have creative power. God spoke the world into existence. Your words don't create worlds, but they do create reality - encouraging or discouraging, building or tearing down, blessing or cursing. Every word you speak either injects life or poison into others' hearts. Wise people wield words carefully, knowing they can heal deep wounds or inflict lasting pain.",
    reflection: "Think about your recent conversations. Have your words brought healing or hurt? What needs to change in how you speak?",
    themes: ["words", "wisdom", "influence"],
  },
  {
    id: "39",
    title: "Mind Renewal",
    scripture: "Isaiah 26:3",
    verse: "You will keep in perfect peace those whose minds are steadfast, because they trust in you.",
    insight: "Your mind is a battlefield. What you think determines how you live. Negative thought patterns create negative life patterns. But Paul says you can be transformed by renewing your mind. How? By replacing lies with truth, meditating on Scripture, taking thoughts captive, and fixing your mind on God. A steadfast mind - one focused on God's truth - experiences perfect peace even in imperfect circumstances.",
    reflection: "What negative thought pattern is dominating your mind? What truth from God's Word can you use to replace that lie?",
    themes: ["mind", "peace", "transformation"],
  },
  {
    id: "40",
    title: "Finishing Strong",
    scripture: "Philippians 3:13-14",
    verse: "Brothers and sisters, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead, I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.",
    insight: "Paul understood that perseverance requires both forgetting and straining - letting go of past failures and pressing toward future goals. You can't finish strong while looking backward. The race isn't won by those who start fast but by those who finish faithful. Keep your eyes on the prize, refuse to quit, and trust that God will reward your perseverance.",
    reflection: "What past failure or regret are you allowing to slow your race? What would it look like to let it go and press forward today?",
    themes: ["perseverance", "focus", "victory"],
  },
  {
    id: "41",
    title: "God's Constant Presence",
    scripture: "Deuteronomy 31:6",
    verse: "Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you; he will never leave you nor forsake you.",
    insight: "Loneliness lies. It whispers that you're abandoned, forgotten, alone. But God promises He will never leave or forsake you. Ever. His presence isn't contingent on your feelings. Even when you don't sense Him, He's there. Even when circumstances suggest otherwise, He remains. His faithfulness doesn't waver. His commitment doesn't fail. You are never, ever alone.",
    reflection: "When have you felt most alone? Looking back, can you now see evidence that God was actually present even when you didn't feel Him?",
    themes: ["presence", "faithfulness", "comfort"],
  },
  {
    id: "42",
    title: "Divine Timing",
    scripture: "Habakkuk 2:3",
    verse: "For the revelation awaits an appointed time; it speaks of the end and will not prove false. Though it linger, wait for it; it will certainly come and will not delay.",
    insight: "God operates on a divine timeline that rarely matches ours. What feels like delay to you is actually divine positioning. He's working behind the scenes, arranging circumstances, preparing people, and developing your character. His timing is never early, never late - always perfect. Waiting isn't punishment; it's preparation. Trust the process even when you can't see the progress.",
    reflection: "What are you waiting for right now? How might God be using this waiting season to prepare you or the situation?",
    themes: ["timing", "patience", "trust"],
  },
  {
    id: "43",
    title: "Running Unhindered",
    scripture: "1 Corinthians 9:24-25",
    verse: "Do you not know that in a race all the runners run, but only one gets the prize? Run in such a way as to get the prize. Everyone who competes in the games goes into strict training. They do it to get a crown that will not last, but we do it to get a crown that will last forever.",
    insight: "Athletes eliminate anything that hinders performance - excess weight, poor nutrition, inadequate training. Similarly, believers must throw off sin that entangles and weights that slow them down. What's hindering your spiritual race? Is it secret sin, toxic relationships, time-wasting habits, or misplaced priorities? Identify it. Eliminate it. Run free.",
    reflection: "What 'weight' in your life isn't necessarily sin but is slowing your spiritual progress? What needs to be cut to help you run faster?",
    themes: ["freedom", "discipline", "purpose"],
  },
  {
    id: "44",
    title: "Persistent Prayer",
    scripture: "Romans 12:12",
    verse: "Be joyful in hope, patient in affliction, faithful in prayer.",
    insight: "Jesus taught persistence in prayer through the parable of the widow and the unjust judge. If relentless asking works with a corrupt judge, how much more with a loving Father? God isn't annoyed by your repeated requests - He's moved by your faith and persistence. Keep asking, keep seeking, keep knocking. Your breakthrough might be one prayer away.",
    reflection: "What have you stopped praying about because you're tired of asking? What if God wants you to keep praying because He's about to answer?",
    themes: ["prayer", "persistence", "faith"],
  },
  {
    id: "45",
    title: "New Creation Identity",
    scripture: "Galatians 2:20",
    verse: "I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me.",
    insight: "Your old self died with Christ on the cross. That person - defined by shame, failure, and sin - no longer exists. You're now a new creation with a new identity: loved, chosen, holy, righteous. The Christian life isn't about trying harder to be good; it's about allowing Christ to live through you. You're not who you were. You're who He says you are.",
    reflection: "What old identity label are you still carrying that Christ has already removed? How would your life change if you truly believed your new identity?",
    themes: ["identity", "transformation", "freedom"],
  },
  {
    id: "46",
    title: "Investing in Eternity",
    scripture: "Luke 12:33-34",
    verse: "Sell your possessions and give to the poor. Provide purses for yourselves that will not wear out, a treasure in heaven that will never fail, where no thief comes near and no moth destroys. For where your treasure is, there your heart will be also.",
    insight: "Jesus connects your treasure to your heart. Where you invest reveals what you value. Earthly treasures - money, possessions, achievements - are temporary. Only three things last: God, His Word, and people. Wise investors put resources into what endures. Generosity, evangelism, discipleship, and service are eternal investments with guaranteed returns.",
    reflection: "Where is most of your time, money, and energy invested? If your spending and schedule reflect your priorities, what do they reveal about what you truly treasure?",
    themes: ["eternity", "generosity", "priorities"],
  },
  {
    id: "47",
    title: "Loving Enemies",
    scripture: "Romans 12:20-21",
    verse: "On the contrary: 'If your enemy is hungry, feed him; if he is thirsty, give him something to drink. In doing this, you will heap burning coals on his head.' Do not be overcome by evil, but overcome evil with good.",
    insight: "Loving enemies defies human nature but defines divine nature. Retaliation is easy; blessing is supernatural. When you respond to hate with love, insult with kindness, and harm with help, you break the cycle of evil. You also become like Jesus, who loved His enemies all the way to the cross. This kind of love isn't natural - it's Spirit-empowered and world-changing.",
    reflection: "Who treats you as an enemy? What would it look like to actively bless them this week instead of avoiding or resenting them?",
    themes: ["love", "forgiveness", "transformation"],
  },
  {
    id: "48",
    title: "Conquering Fear",
    scripture: "Psalm 27:1",
    verse: "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid?",
    insight: "Fear asks 'what if?' Faith responds 'even if.' David faced giants, armies, and betrayal, yet declared fearlessness. Why? Because God was his light (showing the way), salvation (securing the outcome), and stronghold (protecting in battle). When you know God is for you, with you, and in you, fear loses its power. Courage isn't the absence of fear; it's trusting God in spite of it.",
    reflection: "What specific fear is paralyzing you right now? How does knowing God as your light, salvation, and stronghold change how you view that fear?",
    themes: ["courage", "fear", "trust"],
  },
  {
    id: "49",
    title: "The Gift of Rest",
    scripture: "Matthew 11:28-30",
    verse: "Come to me, all you who are weary and burdened, and I will give you rest. Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls. For my yoke is easy and my burden is light.",
    insight: "Jesus invites the weary to rest - not leisure or laziness, but soul rest. He offers to trade your heavy burdens for His light yoke. A yoke connects two animals for work, but Jesus' yoke is easy because He pulls with you. You're not meant to carry life alone. Margin, Sabbath, and rest aren't luxuries; they're divine invitations to work with Jesus rather than apart from Him.",
    reflection: "What burdens are you carrying that Jesus wants to take? What would change if you truly believed His yoke is light and He's pulling with you?",
    themes: ["rest", "burden", "grace"],
  },
  {
    id: "50",
    title: "Don't Give Up",
    scripture: "Isaiah 40:31",
    verse: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.",
    insight: "Weariness is inevitable; giving up is optional. When you're exhausted, hope in the Lord. Wait on Him. He promises renewed strength - not just to survive but to soar. Eagles don't flap frantically; they catch wind currents and soar effortlessly. Similarly, when you wait on God, His Spirit lifts you above your circumstances. Keep hoping. Keep trusting. Keep going.",
    reflection: "Where are you most weary right now? What does it mean for you to 'wait on the Lord' in that specific situation?",
    themes: ["perseverance", "hope", "strength"],
  },
  {
    id: "51",
    title: "Worship as Warfare",
    scripture: "2 Chronicles 20:21-22",
    verse: "After consulting the people, Jehoshaphat appointed men to sing to the Lord and to praise him for the splendor of his holiness as they went out at the head of the army, saying: 'Give thanks to the Lord, for his love endures forever.' As they began to sing and praise, the Lord set ambushes against the men.",
    insight: "When Jehoshaphat's army faced overwhelming odds, they put worshipers on the front lines. As they praised God, He fought for them. Worship is spiritual warfare - it shifts focus from problem to Provider, declares God's supremacy over circumstances, and invites His intervention. Sacrificial praise in the storm confuses the enemy and activates heaven's armies.",
    reflection: "What battle are you fighting? What would happen if you led with worship instead of worry?",
    themes: ["worship", "warfare", "victory"],
  },
  {
    id: "52",
    title: "Breaking Family Patterns",
    scripture: "Joshua 24:15",
    verse: "But if serving the Lord seems undesirable to you, then choose for yourselves this day whom you will serve, whether the gods your ancestors served beyond the Euphrates, or the gods of the Amorites, in whose land you are living. But as for me and my household, we will serve the Lord.",
    insight: "Joshua recognized that his family had patterns from previous generations - idolatry, compromise, disobedience. But he declared that the cycle stops with him. You're not destined to repeat your family's mistakes. In Christ, you have authority to break generational curses and establish new legacies. Your choice to follow God can change your family tree for generations to come.",
    reflection: "What negative pattern from your family history are you repeating? What would it look like to declare, 'As for me and my house, we will serve the Lord' and establish a new legacy?",
    themes: ["legacy", "freedom", "family"],
  },
  {
    id: "53",
    title: "Faithfulness in Small Things",
    scripture: "Zechariah 4:10",
    verse: "Who dares despise the day of small things, since the seven eyes of the Lord that range throughout the earth will rejoice when they see the chosen capstone in the hand of Zerubbabel?",
    insight: "Big breakthroughs are built on small obediences. Don't despise small beginnings or incremental progress. God is watching your faithfulness in hidden places. How you handle little assignments qualifies you for bigger ones. Joseph was faithful as a slave and prisoner before leading Egypt. David was faithful with sheep before leading Israel. Your current 'small thing' is preparation for something greater.",
    reflection: "What small task or role feels insignificant right now? How might God be using it to prepare you for something bigger?",
    themes: ["faithfulness", "preparation", "character"],
  },
  {
    id: "54",
    title: "Scars as Testimonies",
    scripture: "John 20:27",
    verse: "Then he said to Thomas, 'Put your finger here; see my hands. Reach out your hand and put it into my side. Stop doubting and believe.'",
    insight: "Jesus rose with His scars. He could have erased them, but He kept them as evidence of His victory. Your scars - emotional, spiritual, physical - aren't signs of defeat; they're proof of survival. What you've overcome can become someone else's breakthrough. Your mess is your message. Don't hide your scars; share them. Your story could be someone's hope.",
    reflection: "What painful experience from your past could God use to encourage or help someone else? Who might need to hear your testimony?",
    themes: ["testimony", "healing", "purpose"],
  },
  {
    id: "55",
    title: "Trusting Closed Doors",
    scripture: "Proverbs 19:21",
    verse: "Many are the plans in a person's heart, but it is the Lord's purpose that prevails.",
    insight: "Closed doors hurt, especially when you were certain they were God's plan. But what if God closed that door to redirect you to something better? His 'no' or 'not now' protects you from wrong timing, wrong fit, or wrong direction. When God closes a door, He's not punishing you; He's guiding you. His purposes always prevail, and they're always better than your plans.",
    reflection: "What closed door are you still mourning? Can you trust that God closed it for a reason and is opening something better?",
    themes: ["trust", "direction", "sovereignty"],
  },
  {
    id: "56",
    title: "Mind, Body, Soul Health",
    scripture: "1 Thessalonians 5:23",
    verse: "May God himself, the God of peace, sanctify you through and through. May your whole spirit, soul and body be kept blameless at the coming of our Lord Jesus Christ.",
    insight: "God cares about your whole being - spirit, soul (mind/emotions), and body. Mental health isn't separate from spiritual health; it's part of it. Depression, anxiety, and trauma are real struggles that require real help. Stewarding your mental health honors God. Seeing a therapist, taking medication, and joining support groups are acts of wisdom, not weakness. God works through professionals and medicine to bring wholeness.",
    reflection: "How are you caring for your mental and emotional health? What practical step could you take this week to better steward your mind and emotions?",
    themes: ["health", "wholeness", "stewardship"],
  },
  {
    id: "57",
    title: "Marriage Requires Work",
    scripture: "Ecclesiastes 4:9-12",
    verse: "Two are better than one, because they have a good return for their labor: If either of them falls down, one can help the other up. But pity anyone who falls and has no one to help them up. Also, if two lie down together, they will keep warm. But how can one keep warm alone? Though one may be overpowered, two can defend themselves. A cord of three strands is not quickly broken.",
    insight: "Marriage isn't two people facing each other; it's two people facing the same direction with God in the center - a three-strand cord. Strong marriages don't happen by accident. They require intentionality: communication, forgiveness, service, prayer, date nights, counseling, and daily choices to love even when it's hard. The enemy attacks marriages; fight for yours.",
    reflection: "What's one practical way you can invest in your marriage this week? If you're single, what marriage principle can you apply to your current relationships?",
    themes: ["marriage", "partnership", "commitment"],
  },
  {
    id: "58",
    title: "The Cost of Discipleship",
    scripture: "Matthew 16:24-25",
    verse: "Then Jesus said to his disciples, 'Whoever wants to be my disciple must deny themselves and take up their cross and follow me. For whoever wants to save their life will lose it, but whoever loses their life for me will find it.'",
    insight: "Following Jesus costs something. It might cost comfort, popularity, money, relationships, or security. But what you gain infinitely surpasses what you give up. Jesus doesn't promise easy; He promises worth it. Real discipleship requires daily self-denial and willing sacrifice. But in losing your life for Him, you find true life - abundant, purposeful, eternal.",
    reflection: "What is following Jesus costing you right now? Are you willing to pay that cost, trusting that He's worth it?",
    themes: ["discipleship", "sacrifice", "purpose"],
  },
  {
    id: "59",
    title: "Raising Arrows",
    scripture: "Psalm 127:3-4",
    verse: "Children are a heritage from the Lord, offspring a reward from him. Like arrows in the hands of a warrior are children born in one's youth.",
    insight: "Children are arrows - designed to be launched into the world to hit targets you may never reach. Your job as a parent isn't to keep them close forever but to shape them, aim them, and release them for God's purposes. This requires intentional spiritual formation: prayer, Scripture, modeling authentic faith, and speaking identity. Point your arrows toward heaven, and trust God to direct their flight.",
    reflection: "If you have children, what are you doing to spiritually form them? What legacy are you establishing in your home?",
    themes: ["parenting", "legacy", "purpose"],
  },
  {
    id: "60",
    title: "Fresh Starts Every Morning",
    scripture: "Psalm 30:5",
    verse: "For his anger lasts only a moment, but his favor lasts a lifetime; weeping may stay for the night, but rejoicing comes in the morning.",
    insight: "No matter how dark the night, morning always comes. God's mercies are new every morning. Yesterday's failure doesn't define today's potential. Yesterday's pain doesn't dictate today's peace. God offers fresh starts, clean slates, and new beginnings every single day. His compassions never fail. His faithfulness never wavers. Today is a new day. Start again.",
    reflection: "What from yesterday do you need to release so you can embrace today's fresh start? What would change if you truly believed God's mercies are new this morning?",
    themes: ["grace", "new beginnings", "hope"],
  },
  {
    id: "61",
    title: "Walking Humbly",
    scripture: "Philippians 2:3-4",
    verse: "Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves, not looking to your own interests but each of you to the interests of the others.",
    insight: "Humility isn't thinking less of yourself; it's thinking of yourself less. It's recognizing that everything you have - talents, opportunities, breath - is a gift from God. Pride takes credit; humility gives glory. Pride competes; humility celebrates. Pride demands recognition; humility finds joy in serving without applause. Jesus, though God, humbled Himself to death on a cross. If He can be humble, so can you.",
    reflection: "Where is pride showing up in your life? What would humility look like in that specific area?",
    themes: ["humility", "service", "character"],
  },
  {
    id: "62",
    title: "The Power of Community",
    scripture: "Proverbs 27:17",
    verse: "As iron sharpens iron, so one person sharpens another.",
    insight: "You can't grow alone. Iron sharpening iron requires friction - challenging conversations, accountability, truth-telling, and encouragement. Authentic community means letting people into your mess, being vulnerable about struggles, and allowing godly people to speak into your life. It's uncomfortable but essential. Find your people - those who will sharpen you, pray for you, and walk with you through every season.",
    reflection: "Who is sharpening you? Who are you sharpening? If you can't answer both, what step can you take toward authentic community this week?",
    themes: ["community", "growth", "accountability"],
  },
  {
    id: "63",
    title: "Healthy Boundaries Honor God",
    scripture: "Galatians 6:2, 5",
    verse: "Carry each other's burdens, and in this way you will fulfill the law of Christ... For each one should carry their own load.",
    insight: "There's a difference between burdens (heavy, temporary crises we help each other carry) and loads (daily responsibilities each person must carry). Healthy boundaries mean helping with burdens without enabling people to avoid their loads. Saying 'no' isn't selfish; it protects your capacity to say 'yes' to what God called you to. Boundaries honor both God's call on your life and others' responsibility for theirs.",
    reflection: "Where do you need to establish boundaries - with your time, relationships, or commitments? What's one boundary you need to set this week?",
    themes: ["boundaries", "wisdom", "stewardship"],
  },
  {
    id: "64",
    title: "Work as Worship",
    scripture: "1 Corinthians 10:31",
    verse: "So whether you eat or drink or whatever you do, do it all for the glory of God.",
    insight: "There's no sacred-secular divide. All work done for God's glory is worship. Whether you're preaching or plumbing, teaching or typing, parenting or programming - if you're doing it for God's glory, it's ministry. Excellence in your work honors God and witnesses to others. Your workplace is your mission field. Your work ethic preaches louder than your words. Let everything you do bring glory to God.",
    reflection: "How does viewing your daily work as worship change your attitude toward it? What would 'working as unto the Lord' look like in your current job?",
    themes: ["work", "worship", "purpose"],
  },
  {
    id: "65",
    title: "Small Wins Add Up",
    scripture: "Luke 16:10",
    verse: "Whoever can be trusted with very little can also be trusted with much, and whoever is dishonest with very little will also be dishonest with much.",
    insight: "Big victories are built on small obediences. Every prayer, every good choice, every act of faithfulness matters to God. Don't despise small progress or incremental growth. Compound interest works in spiritual life too - small, consistent actions over time produce massive results. Celebrate small wins. Thank God for progress. Keep showing up. The harvest is coming.",
    reflection: "What small win from today can you celebrate? How has small, consistent faithfulness in one area produced growth over time?",
    themes: ["faithfulness", "perseverance", "growth"],
  },
  {
    id: "66",
    title: "Living on Purpose",
    scripture: "Psalm 90:12",
    verse: "Teach us to number our days, that we may gain a heart of wisdom.",
    insight: "Life is short. Time is limited. When you realize your days are numbered, you live differently - more intentionally, more purposefully, more wisely. Wise people don't drift through life on autopilot. They set goals, make plans, prioritize what matters, and eliminate what doesn't. They live by design, not default. Don't let life happen to you; happen to life. Be intentional.",
    reflection: "If you knew you had only one year left, what would you change about how you're living now? What's stopping you from making that change today?",
    themes: ["purpose", "intentionality", "wisdom"],
  },
  {
    id: "67",
    title: "The Mentorship Cycle",
    scripture: "Titus 2:3-5",
    verse: "Likewise, teach the older women to be reverent in the way they live, not to be slanderers or addicted to much wine, but to teach what is good. Then they can urge the younger women to love their husbands and children, to be self-controlled and pure.",
    insight: "God designed faith to be passed down generationally through mentorship. Older believers teach younger ones. Those further along help those a few steps behind. This isn't about perfection; it's about progression. You're qualified to mentor someone who's where you were, and you need mentoring from someone who's where you're going. Multiplication happens through intentional investment.",
    reflection: "Who is mentoring you? Who are you mentoring? If neither, what's your first step toward finding a mentor or becoming one?",
    themes: ["mentorship", "discipleship", "legacy"],
  },
  {
    id: "68",
    title: "Breaking Addiction's Chains",
    scripture: "John 8:36",
    verse: "So if the Son sets you free, you will be free indeed.",
    insight: "Addiction feels like unbreakable chains, but Jesus came to set captives free. Freedom is possible, but it requires both God's power and practical steps: admitting the problem, getting professional help, building accountability, identifying triggers, and replacing bad habits with healthy ones. You can't do it alone, but you don't have to. Christ offers freedom; counselors offer tools; community offers support. The path to freedom is hard, but it's worth it.",
    reflection: "What addiction or stronghold has you bound? What's the first practical step toward freedom? Who can you tell who will help hold you accountable?",
    themes: ["freedom", "healing", "accountability"],
  },
  {
    id: "69",
    title: "Stewarding Your Gifts",
    scripture: "Romans 12:6-8",
    verse: "We have different gifts, according to the grace given to each of us. If your gift is prophesying, then prophesy in accordance with your faith; if it is serving, then serve; if it is teaching, then teach; if it is to encourage, then give encouragement.",
    insight: "God gave you unique gifts for His purposes and others' good. Your gifts aren't random; they're intentional. They reveal how God wants to use you. Don't compare your gifts to others or covet their calling. Use what God gave you. Develop it. Deploy it. Serve with it. There's someone only you can reach, a problem only you can solve, a message only you can deliver.",
    reflection: "What gifts has God given you? Are you actively using them to serve others and glorify Him? If not, what's stopping you?",
    themes: ["gifts", "service", "purpose"],
  },
  {
    id: "70",
    title: "Praying for Prodigals",
    scripture: "Luke 15:17-20",
    verse: "When he came to his senses, he said... 'I will set out and go back to my father'... So he got up and went to his father. But while he was still a long way off, his father saw him and was filled with compassion for him.",
    insight: "The prodigal story reveals a father's heart - watching, waiting, ready to run when his son returns. That's your Heavenly Father's heart toward every prodigal. If you're praying for someone far from God, don't give up. God is pursuing them relentlessly. Your prayers matter. Their story isn't over. Keep believing, keep praying, keep hoping. The father is watching for their return.",
    reflection: "Who are you praying for who's far from God? What encourages you about the prodigal's story? How can you continue faithfully interceding?",
    themes: ["intercession", "hope", "grace"],
  },
  {
    id: "71",
    title: "The Discipline of Fasting",
    scripture: "Joel 2:12",
    verse: "'Even now,' declares the Lord, 'return to me with all your heart, with fasting and weeping and mourning.'",
    insight: "Fasting isn't about earning God's favor; it's about increasing spiritual sensitivity. When you deny physical appetite, you awaken spiritual hunger. Fasting clarifies God's voice, breaks strongholds, and intensifies prayers. It's not magic but discipline - positioning your heart to hear and respond to God more clearly. Start small and let the Holy Spirit guide how and when you fast.",
    reflection: "When was the last time you fasted? What might God be inviting you to fast from (food, media, distractions) to seek Him more intentionally?",
    themes: ["fasting", "discipline", "spiritual growth"],
  },
  {
    id: "72",
    title: "Guarding Your Thought Life",
    scripture: "2 Corinthians 10:5",
    verse: "We demolish arguments and every pretension that sets itself up against the knowledge of God, and we take captive every thought to make it obedient to Christ.",
    insight: "Your thought life determines your whole life. You can't stop thoughts from coming, but you can choose which ones you entertain. Taking thoughts captive means evaluating every thought against God's truth and rejecting lies. 'I'm worthless' gets replaced with 'I'm loved by God.' 'This is hopeless' becomes 'God is working.' Control your thoughts or they'll control you.",
    reflection: "What negative thought pattern dominates your mind? What truth from Scripture can you use to take that thought captive and replace it?",
    themes: ["mind", "truth", "transformation"],
  },
  {
    id: "73",
    title: "When God Redirects",
    scripture: "Acts 16:6-10",
    verse: "Paul and his companions traveled throughout the region of Phrygia and Galatia, having been kept by the Holy Spirit from preaching the word in the province of Asia. When they came to the border of Mysia, they tried to enter Bithynia, but the Spirit of Jesus would not allow them to.",
    insight: "Paul had plans to preach in Asia and Bithynia, but God redirected him to Macedonia instead. That redirection changed Western civilization. Sometimes God's 'no' to your plans is a 'yes' to something better. His redirections aren't rejections; they're course corrections. If God is closing doors or changing directions, trust Him. He sees what you don't.",
    reflection: "Where is God redirecting you right now? Can you trust that His plan is better than yours, even when you don't understand it?",
    themes: ["guidance", "trust", "obedience"],
  },
  {
    id: "74",
    title: "The Fifth Commandment",
    scripture: "Ephesians 6:2-3",
    verse: "'Honor your father and mother'—which is the first commandment with a promise—'so that it may go well with you and that you may enjoy long life on the earth.'",
    insight: "Honoring parents doesn't require agreeing with them or excusing their failures. It means treating them with respect because of the position God gave them. Even if they weren't who you needed, you can still honor their role while setting healthy boundaries. God attaches blessing to this command - not manipulation but principle. When you honor authority, you position yourself for blessing.",
    reflection: "How are you honoring (or dishonoring) your parents? What does honor look like in your specific situation - gratitude, forgiveness, service, boundaries?",
    themes: ["honor", "family", "blessing"],
  },
  {
    id: "75",
    title: "Faithful with Little",
    scripture: "Matthew 25:21",
    verse: "His master replied, 'Well done, good and faithful servant! You have been faithful with a few things; I will put you in charge of many things. Come and share your master's happiness!'",
    insight: "God evaluates faithfulness, not fruitfulness. He's not impressed by talent or results as much as He's watching stewardship. Are you faithful with what He's given you - time, money, talents, opportunities? Faithful stewards manage wisely, invest strategically, and give generously. One day you'll give an account. The goal isn't to hear 'You succeeded' but 'Well done, faithful servant.'",
    reflection: "How are you stewarding what God has entrusted to you? In what area do you need to improve your faithfulness?",
    themes: ["stewardship", "faithfulness", "accountability"],
  },
  {
    id: "76",
    title: "The Gift of Singleness",
    scripture: "1 Corinthians 7:32-35",
    verse: "I would like you to be free from concern. An unmarried man is concerned about the Lord's affairs—how he can please the Lord. But a married man is concerned about the affairs of this world—how he can please his wife—and his interests are divided.",
    insight: "Paul calls singleness a gift - undivided devotion to God. Marriage is beautiful, but so is singleness. If you're single, don't waste this season wishing for marriage. Maximize it. Pursue God wholeheartedly. Develop your gifts. Serve without distraction. Whether God calls you to lifelong singleness or eventual marriage, steward this season well. Fulfillment is found in Christ, not relationship status.",
    reflection: "If you're single, how are you stewarding this season? If you're married, how can you help singles in your life see their season as valuable, not as a waiting room?",
    themes: ["singleness", "purpose", "contentment"],
  },
  {
    id: "77",
    title: "Abiding for Fruitfulness",
    scripture: "John 15:4-5",
    verse: "Remain in me, as I also remain in you. No branch can bear fruit by itself; it must remain in the vine. Neither can you bear fruit unless you remain in me. I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing.",
    insight: "Branches don't strain to produce fruit; they simply stay attached to the vine, and fruit happens naturally. Same with you. Abiding - staying connected through prayer, Scripture, worship, and obedience - produces fruit automatically: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control. Don't strive. Abide.",
    reflection: "How connected are you to Jesus right now? What spiritual discipline helps you abide most effectively?",
    themes: ["abiding", "fruitfulness", "relationship"],
  },
  {
    id: "78",
    title: "Trusting God with Your Kids",
    scripture: "Proverbs 3:5-6",
    verse: "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.",
    insight: "Your kids aren't really yours - they're God's, entrusted to you. You can't control their choices or guarantee outcomes, but you can pray, model faith, and trust God with them. Parenting requires surrendering control and trusting God's sovereignty. He loves your kids more than you do. Whether they're toddlers or adults, keep praying, keep believing, and keep trusting. God is faithful.",
    reflection: "What fear do you have about your children? How does it change your perspective to remember they belong to God first?",
    themes: ["parenting", "trust", "surrender"],
  },
  {
    id: "79",
    title: "Healing from Past Pain",
    scripture: "Psalm 147:3",
    verse: "He heals the brokenhearted and binds up their wounds.",
    insight: "Your past hurt you - abuse, betrayal, trauma, loss. Those wounds are real and deep. But God specializes in healing broken hearts. Healing doesn't erase the past; it removes its power over your future. Get help. See a counselor. Process the pain. Bring it into the light. Forgiveness isn't forgetting; it's releasing. You're not damaged goods; you're an overcomer. Healing is possible.",
    reflection: "What past pain still affects you today? What's your next step toward healing - counseling, confrontation, confession, forgiveness?",
    themes: ["healing", "wholeness", "redemption"],
  },
  {
    id: "80",
    title: "The Joy of Generosity",
    scripture: "2 Corinthians 9:6-7",
    verse: "Remember this: Whoever sows sparingly will also reap sparingly, and whoever sows generously will also reap generously. Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver.",
    insight: "Generosity isn't about the amount; it's about the heart. God loves cheerful givers - those who give freely, joyfully, and generously. Generosity breaks greed's grip and demonstrates trust in God's provision. You can't outgive God. As you sow generously - money, time, kindness, grace - you reap bountifully, not always financially but always spiritually. Give freely. Watch what God does.",
    reflection: "Where can you be more generous this week - financially, with your time, or in showing grace? How does your giving reflect your trust in God's provision?",
    themes: ["generosity", "giving", "trust"],
  },
  {
    id: "81",
    title: "Living with Purpose",
    scripture: "Ephesians 2:10",
    verse: "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.",
    insight: "You're not an accident. God created you on purpose, for a purpose. He prepared good works for you before you were born. Your life has meaning beyond survival. You have a unique calling - a specific assignment that leverages your gifts, experiences, and passions for His glory. Don't waste your life on trivial pursuits. Discover your purpose. Pursue your calling. Live intentionally.",
    reflection: "What good works has God prepared for you? How are your current activities aligning with your God-given purpose?",
    themes: ["purpose", "calling", "identity"],
  },
  {
    id: "82",
    title: "The Ministry of Listening",
    scripture: "Proverbs 18:13",
    verse: "To answer before listening—that is folly and shame.",
    insight: "In a world full of talkers, listening is rare and valuable. Most people don't need your advice; they need your attention. True listening requires humility (admitting you don't know everything), patience (not interrupting), and love (caring about their experience). When you truly listen, you're ministering - showing people they matter, they're seen, and they're heard. Listen more. Talk less.",
    reflection: "In your recent conversations, have you listened more than you talked? What would change if your goal was to understand rather than to respond?",
    themes: ["listening", "humility", "ministry"],
  },
  {
    id: "83",
    title: "Freedom from Comparison",
    scripture: "2 Corinthians 5:9-10",
    verse: "So we make it our goal to please him, whether we are at home in the body or away from it. For we must all appear before the judgment seat of Christ, so that each of us may receive what is due us for the things done while in the body, whether good or bad.",
    insight: "One day you'll stand before Jesus to give an account of your life. He won't ask why you weren't like someone else. He'll ask if you were faithful with what He gave you. Comparison is irrelevant because you're running a unique race. Stop measuring your mile 3 against their mile 15. Run your race. Please Him, not them.",
    reflection: "Who are you comparing yourself to? How would your life change if you focused only on pleasing Jesus with what He's given you?",
    themes: ["comparison", "identity", "faithfulness"],
  },
  {
    id: "84",
    title: "Confession Brings Healing",
    scripture: "Psalm 32:3-5",
    verse: "When I kept silent, my bones wasted away through my groaning all day long. For day and night your hand was heavy on me; my strength was sapped as in the heat of summer. Then I acknowledged my sin to you and did not cover up my iniquity. I said, 'I will confess my transgressions to the Lord.' And you forgave the guilt of my sin.",
    insight: "Secret sin saps strength. Unconfessed sin creates internal groaning. But confession brings healing and freedom. David describes the physical toll of hidden sin and the relief of confession. When you bring sin into the light - confessing to God and a trusted person - shame loses power. Confession isn't weakness; it's the path to wholeness.",
    reflection: "What sin are you hiding? Who can you confess to who will pray for you and hold you accountable?",
    themes: ["confession", "healing", "freedom"],
  },
  {
    id: "85",
    title: "Armed for Battle",
    scripture: "Ephesians 6:10-11",
    verse: "Finally, be strong in the Lord and in his mighty power. Put on the full armor of God, so that you can take your stand against the devil's schemes.",
    insight: "Spiritual warfare is real. The enemy prowls like a lion, seeking to devour. But you're not defenseless. God provides armor: truth, righteousness, peace, faith, salvation, the Word, and prayer. These aren't passive; they're active weapons. Stand firm. Fight back. The battle is real, but so is your authority in Christ. You're on the winning side.",
    reflection: "What piece of spiritual armor do you most need to 'put on' today? How can you actively use it to fight the specific battle you're facing?",
    themes: ["warfare", "victory", "authority"],
  },
  {
    id: "86",
    title: "Maximizing Time",
    scripture: "Psalm 39:4-5",
    verse: "Show me, Lord, my life's end and the number of my days; let me know how fleeting my life is. You have made my days a mere handbreadth; the span of my years is as nothing before you. Everyone is but a breath, even those who seem secure.",
    insight: "Life is short. Your days are numbered. When you realize how fleeting life is, you live differently - more intentionally, less wastefully. Time is your most valuable resource. You can earn more money, but you can't create more time. Wise people redeem their time by eliminating distractions and investing in what matters: relationships, growth, and eternal impact.",
    reflection: "Track your time for one day. Where are hours going? What needs more time? What needs less? What change will you make?",
    themes: ["time", "stewardship", "wisdom"],
  },
  {
    id: "87",
    title: "Worshiping Together",
    scripture: "Psalm 95:6-7",
    verse: "Come, let us bow down in worship, let us kneel before the Lord our Maker; for he is our God and we are the people of his pasture, the flock under his care.",
    insight: "There's power in corporate worship that you can't experience alone. When believers gather to worship, God inhabits their praises. Singing with hundreds of voices reminds you you're not alone. Worshiping alongside others strengthens your faith. Hearing the Word with the body sharpens understanding. Don't neglect gathering together. Your presence matters. You need the church, and the church needs you.",
    reflection: "How consistently are you engaging in corporate worship? If you've been isolated, what's keeping you from gathering with believers?",
    themes: ["worship", "community", "presence"],
  },
  {
    id: "88",
    title: "Tested and Refined",
    scripture: "1 Peter 1:6-7",
    verse: "In all this you greatly rejoice, though now for a little while you may have had to suffer grief in all kinds of trials. These have come so that the proven genuineness of your faith—of greater worth than gold, which perishes even though refined by fire—may result in praise, glory and honor when Jesus Christ is revealed.",
    insight: "Trials aren't fun, but they're purposeful. God uses them to test and refine your faith like gold in fire. Untested faith is immature faith. When trials come, they reveal what you really believe. Will you trust God when it costs you? Will you worship in the storm? Will you obey when it's hard? Pass the test, and you emerge stronger, more mature, more like Jesus.",
    reflection: "What trial are you in right now? How might God be using it to refine your faith? What's He teaching you through it?",
    themes: ["testing", "refinement", "perseverance"],
  },
  {
    id: "89",
    title: "Learned Contentment",
    scripture: "1 Timothy 6:6-8",
    verse: "But godliness with contentment is great gain. For we brought nothing into the world, and we can take nothing out of it. But if we have food and clothing, we will be content with that.",
    insight: "Contentment isn't having everything you want; it's wanting what you have. Paul learned contentment in plenty and poverty. How? By finding satisfaction in Christ, not circumstances. Contentment is peace in the present while pursuing the future. It's gratitude for what is while hoping for what's coming. It defeats comparison, kills covetousness, and cultivates joy. Learn contentment. Practice gratitude.",
    reflection: "What would change if you practiced contentment with what you currently have? What are three things you have now that you once prayed for?",
    themes: ["contentment", "gratitude", "peace"],
  },
  {
    id: "90",
    title: "Making Disciples",
    scripture: "Acts 1:8",
    verse: "But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.",
    insight: "The Great Commission isn't for pastors and missionaries; it's for every believer. You have a mission: make disciples. This doesn't require special training or theological degrees. It means living in a way that makes people curious about Jesus, sharing your story, inviting people to church, and discipling those who respond. Your mission field is where you are - workplace, neighborhood, gym, school. Be a witness.",
    reflection: "Who has God placed in your life who needs Jesus? What's one way you can point them to Him this week?",
    themes: ["mission", "witness", "purpose"],
  },
];

// Get today's study based on day cycling
export function getTodayDailyStudy(viewedIds: string[] = []): DailyStudy {
  const startOfYear = new Date(new Date().getFullYear(), 0, 1);
  const today = new Date();
  const dayOfYear = Math.floor((today.getTime() - startOfYear.getTime()) / (1000 * 60 * 60 * 24));
  const index = dayOfYear % dailyStudies.length;
  return dailyStudies[index];
}

// Get a study that correlates with a devotional
// Priority: 1) Match by ID for perfect correlation, 2) Match by themes
export function getCorrelatedDailyStudy(
  devotionalId: string,
  devotionalThemes: string[],
  viewedIds: string[] = []
): DailyStudy {
  // PRIORITY 1: Perfect 1:1 correlation - match study by devotional ID
  const matchedById = dailyStudies.find(s => s.id === devotionalId);
  if (matchedById) return matchedById;
  
  // PRIORITY 2: Try to match study with devotional themes (unviewed first)
  for (const theme of devotionalThemes) {
    const matchedStudy = dailyStudies.find(
      s => !viewedIds.includes(s.id) && s.themes.includes(theme)
    );
    if (matchedStudy) return matchedStudy;
  }
  
  // PRIORITY 3: Try any theme match regardless of viewed status
  for (const theme of devotionalThemes) {
    const matchedStudy = dailyStudies.find(s => s.themes.includes(theme));
    if (matchedStudy) return matchedStudy;
  }
  
  // PRIORITY 4: Fallback to today's study
  return getTodayDailyStudy(viewedIds);
}
