export type Devotional = {
  id: string;
  date: string;
  title: string;
  scripture: string;
  verse: string;
  reflection: string;
};

export const devotionals: Devotional[] = [
  {
    id: "1",
    date: "2025-01-25",
    title: "Finding Peace in the Storm",
    scripture: "Philippians 4:6-7",
    verse: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.",
    reflection: "Life can feel overwhelming at times. Bills pile up, relationships get complicated, and worries seem to multiply. But God invites us to bring every concern to Him - not just the 'spiritual' ones, but everything. When we pray with thanksgiving, acknowledging His goodness even in hard times, His supernatural peace guards our hearts. Today, what burden can you lay at His feet?",
  },
  {
    id: "2",
    date: "2025-01-26",
    title: "Strength for Today",
    scripture: "Isaiah 40:31",
    verse: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.",
    reflection: "Feeling exhausted? You're not alone. God doesn't promise we'll never be tired, but He does promise to renew our strength when we put our hope in Him. Notice the progression: soar, run, walk. Sometimes victory looks like soaring above problems, sometimes it's running through them, and sometimes it's just taking the next step. Whatever pace you're at today, God meets you there.",
  },
  {
    id: "3",
    date: "2025-01-27",
    title: "Love in Action",
    scripture: "1 John 3:18",
    verse: "Dear children, let us not love with words or speech but with actions and in truth.",
    reflection: "Love is more than a feeling - it's a choice we make every day. Today, look for practical ways to show Christ's love: a kind word to a struggling friend, help with a task, or simply being present for someone. Small acts of love create ripples that extend far beyond what we can see.",
  },
  {
    id: "4",
    date: "2025-01-28",
    title: "The Heart of Stewardship",
    scripture: "Luke 16:10",
    verse: "Whoever can be trusted with very little can also be trusted with much, and whoever is dishonest with very little will also be dishonest with much.",
    reflection: "God cares about how we handle money not because He needs it, but because it reveals our hearts. Every financial decision is a spiritual decision. When we're faithful with $10, God knows we'll be faithful with $10,000. Today's small choices - skipping unnecessary purchases, giving generously, paying bills on time - build character that prepares us for greater opportunities. How are you stewarding what God has already given you?",
  },
  {
    id: "5",
    date: "2025-01-29",
    title: "First Fruits, Not Leftovers",
    scripture: "Proverbs 3:9-10",
    verse: "Honor the Lord with your wealth, with the firstfruits of all your crops; then your barns will be filled to overflowing, and your vats will brim over with new wine.",
    reflection: "The principle of firstfruits challenges our natural tendency to give God what's left after we've taken care of everything else. When we honor God first with our finances - through tithing and generous giving - we're declaring that He is our true provider. It's not about earning God's favor, but about aligning our priorities with His kingdom. What would it look like to give God your 'firstfruits' this week, rather than your leftovers?",
  },
  {
    id: "6",
    date: "2025-01-30",
    title: "Contentment is Wealth",
    scripture: "1 Timothy 6:6-8",
    verse: "But godliness with contentment is great gain. For we brought nothing into the world, and we can take nothing out of it. But if we have food and clothing, we will be content with that.",
    reflection: "True wealth isn't measured by bank accounts, but by contentment. You can be rich and miserable, or have little and be joyful. The secret is godliness paired with contentment - finding satisfaction in God rather than stuff. When you arrived on earth, you brought nothing. When you leave, you'll take nothing. Everything in between is a gift from God to be stewarded wisely and held loosely. Today, choose gratitude over greed, and watch how it transforms your relationship with money.",
  },
  {
    id: "7",
    date: "2025-01-31",
    title: "Generosity Opens Heaven's Windows",
    scripture: "2 Corinthians 9:6-7",
    verse: "Remember this: Whoever sows sparingly will also reap sparingly, and whoever sows generously will also reap generously. Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver.",
    reflection: "God's economy defies logic: the more you give, the more you have. Not because giving is a formula to get rich, but because generous hearts attract God's blessing in unexpected ways. Notice the emphasis on the heart - not the amount. God isn't looking for reluctant or pressured giving, but cheerful, faith-filled generosity. When you give with joy, you're participating in God's work and declaring your trust in His provision. Who can you bless financially today, even in a small way?",
  },
  {
    id: "8",
    date: "2025-02-01",
    title: "Your Business Is Your Ministry",
    scripture: "Colossians 3:23",
    verse: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.",
    reflection: "Many Christians separate 'sacred' work (ministry) from 'secular' work (business). But God sees no such division. Your business is your mission field. Every customer interaction, every employee relationship, every business decision is an opportunity to reflect Christ's character. Excellence in your work isn't about personal glory - it's about representing a God who does all things well. Today, how can your business practices point people to Jesus?",
  },
  {
    id: "9",
    date: "2025-02-02",
    title: "Integrity Over Profit",
    scripture: "Proverbs 11:1",
    verse: "The Lord detests dishonest scales, but accurate weights find favor with him.",
    reflection: "Pressure to succeed can tempt us to compromise - cut corners, exaggerate results, or treat people unfairly. But God values integrity more than profits. Dishonest gain never honors Him, no matter how much it increases your bottom line. When you choose honesty even when it costs you, you're building a business on the solid foundation of God's principles. Your integrity is your brand in God's economy. What business practice is God asking you to examine today?",
  },
  {
    id: "10",
    date: "2025-02-03",
    title: "Faithful With Little, Trusted With Much",
    scripture: "Luke 16:10",
    verse: "Whoever can be trusted with very little can also be trusted with much, and whoever is dishonest with very little will also be dishonest with much.",
    reflection: "Dreaming of scaling your business? God first tests faithfulness with what you have now. How you treat your first customer determines if you're ready for thousands. How you manage your first dollar reveals if you can steward millions. Big opportunities are built on small obediences. Don't despise the day of small beginnings - God is watching how you handle them. Excellence in the little things qualifies you for greater things. What 'small thing' in your business needs your faithful attention today?",
  },
  {
    id: "11",
    date: "2025-02-04",
    title: "God-Sized Vision",
    scripture: "Ephesians 3:20",
    verse: "Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.",
    reflection: "Are you playing it safe with your business vision, or are you dreaming God-sized dreams? God delights in doing immeasurably more than we can imagine - but it requires faith to believe it and courage to pursue it. Your business isn't limited by your resources; it's empowered by God's limitless power working within you. Don't settle for what's comfortable when God is inviting you into what's extraordinary. What bold step is God asking you to take that requires His supernatural provision?",
  },
  {
    id: "12",
    date: "2025-02-05",
    title: "Servant Leadership",
    scripture: "Mark 10:43-45",
    verse: "Whoever wants to become great among you must be your servant, and whoever wants to be first must be slave of all. For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many.",
    reflection: "The world's leadership model says: climb over others to reach the top. Jesus' model says: lift others up as you rise. Great leaders serve their teams, not the other way around. When you lead like Jesus - prioritizing people over profits, serving rather than demanding, empowering rather than controlling - you create a culture that attracts talent and honors God. Your authority is validated by your willingness to serve. Who in your business needs your servant leadership today?",
  },
  {
    id: "13",
    date: "2025-02-06",
    title: "Excellence as Worship",
    scripture: "1 Corinthians 10:31",
    verse: "So whether you eat or drink or whatever you do, do it all for the glory of God.",
    reflection: "Your work quality is a form of worship. When you deliver excellent products, provide outstanding customer service, and conduct business with integrity, you're reflecting the excellence of God Himself. Mediocrity doesn't honor Him. You represent the Creator of the universe - let your work reflect His craftsmanship. Excellence isn't perfectionism that burns you out; it's the pursuit of quality that points to a God who does all things well. What area of your business is God asking you to elevate to a new level of excellence?",
  },
  {
    id: "14",
    date: "2025-02-07",
    title: "Building Wealth God's Way",
    scripture: "Deuteronomy 8:18",
    verse: "But remember the Lord your God, for it is he who gives you the ability to produce wealth, and so confirms his covenant, which he swore to your ancestors, as it is today.",
    reflection: "God isn't against wealth - He's the one who gives you the ability to create it. But with that ability comes responsibility. Building wealth biblically means acknowledging God as the source, managing money wisely, and using resources generously. It's not about how much you have, but what you do with what God has given you. Are you building wealth to hoard or to honor God and bless others? Today, thank God for the ability to earn, save, and invest. Then ask Him to guide you in stewarding it well.",
  },
  {
    id: "15",
    date: "2025-02-08",
    title: "Your Body, God's Temple",
    scripture: "1 Corinthians 3:16-17",
    verse: "Don't you know that you yourselves are God's temple and that God's Spirit dwells in your midst? If anyone destroys God's temple, God will destroy that person; for God's temple is sacred, and you together are that temple.",
    reflection: "Taking care of your physical health isn't vanity - it's stewardship. Your body houses the Spirit of the living God. Every choice you make about food, exercise, rest, and health care is a spiritual decision. Neglecting your body limits your ability to serve God fully. Jesus modeled this balance - He worked hard, but also rested. He fed crowds, but also ate. He walked miles, but also withdrew to pray. Today, honor God by making one healthy choice: drink more water, take a walk, get more sleep, or schedule that overdue doctor's appointment.",
  },
  {
    id: "16",
    date: "2025-02-09",
    title: "Parenting as Discipleship",
    scripture: "Deuteronomy 6:6-7",
    verse: "These commandments that I give you today are to be on your hearts. Impress them on your children. Talk about them when you sit at home and when you walk along the road, when you lie down and when you get up.",
    reflection: "Parenting isn't about perfection - it's about presence. God doesn't call you to be a flawless parent; He calls you to faithfully point your children toward Him in everyday moments. Faith is caught as much as it's taught. Your kids are watching how you handle stress, how you treat others, how you respond to failure. They're learning about God through your life, not just your words. Today, look for one ordinary moment - a meal, a car ride, bedtime - to talk about God's love or pray together. Small, consistent moments build a lifetime of faith.",
  },
  {
    id: "17",
    date: "2025-02-10",
    title: "The Patient Investor",
    scripture: "Proverbs 13:11",
    verse: "Dishonest money dwindles away, but whoever gathers money little by little makes it grow.",
    reflection: "Our culture screams 'get rich quick!' but God's wisdom says 'grow wealth slowly.' Biblical investing isn't about gambling or speculation - it's about patient, consistent stewardship. Like a farmer planting seeds, you won't see immediate results, but over time, small investments compound into significant resources. This isn't just about personal gain - it's about expanding your capacity to provide for your family and give generously. Every $50 invested today is a seed planted for tomorrow's harvest. Start small, be consistent, trust the process, and watch God multiply your faithfulness.",
  },
  {
    id: "18",
    date: "2025-02-11",
    title: "The Debt-Free Dream",
    scripture: "Proverbs 22:7",
    verse: "The rich rule over the poor, and the borrower is slave to the lender.",
    reflection: "Debt feels like chains - limiting your options, stealing your peace, and controlling your decisions. But freedom is possible. It starts with facing the reality, making a plan, and taking one step at a time. Every payment, no matter how small, is a victory. Every sacrifice today is an investment in tomorrow's freedom. God doesn't condemn you for past financial mistakes - He offers wisdom for the path forward. Imagine waking up debt-free: no credit card bills, no car payments, no student loans. That future is within reach if you commit to the journey today. What one expense can you cut this week to make an extra debt payment?",
  },
  {
    id: "19",
    date: "2025-02-12",
    title: "Your Career, God's Calling",
    scripture: "Jeremiah 29:11",
    verse: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.",
    reflection: "Feeling stuck in your career? God has plans for you - plans for growth, impact, and fulfillment. Career development isn't about climbing ladders for ego; it's about stewarding your gifts and expanding your capacity to serve. Every skill you develop, every certification you earn, every leadership lesson you learn prepares you for greater influence. Joseph's prison season prepared him to lead Egypt. David's shepherding trained him to lead Israel. What if your current role is God's training ground for your future calling? Don't despise where you are - grow where you're planted, and trust God to open doors when you're ready.",
  },
  {
    id: "20",
    date: "2025-02-13",
    title: "The Freedom of a Budget",
    scripture: "Proverbs 21:5",
    verse: "The plans of the diligent lead to profit as surely as haste leads to poverty.",
    reflection: "Does budgeting feel restrictive? Flip the script. A budget isn't a cage - it's a roadmap to freedom. Without a plan, money disappears into the void. With a budget, every dollar has a purpose aligned with your values. You're in control, not controlled. Budgeting isn't about deprivation; it's about intention. It's saying 'yes' to what matters and 'not right now' to what doesn't. When you budget, financial anxiety decreases because clarity increases. You know where your money goes, and you make it work for you. This week, track your spending. Next week, create a simple budget. Watch peace replace panic as you steward God's resources intentionally.",
  },
  {
    id: "21",
    date: "2025-02-14",
    title: "Words That Heal",
    scripture: "Proverbs 15:1",
    verse: "A gentle answer turns away wrath, but a harsh word stirs up anger.",
    reflection: "Communication can build bridges or burn them down. The difference? How you speak and how you listen. Harsh words wound deeply; gentle words heal profoundly. When conflict arises, your first reaction isn't always your best response. Take a breath, pray for wisdom, and choose words that build up. Listen more than you speak. Ask questions instead of making accusations. Assume the best, not the worst. Christ-centered communication transforms relationships - at home, at work, in friendships. Today, practice this: before responding to a difficult conversation, pause and ask 'Will these words build or tear down?' Choose wisely. Your words have power - use them to heal.",
  },
  {
    id: "22",
    date: "2025-02-15",
    title: "Increasing Your Income, God's Way",
    scripture: "Deuteronomy 8:18",
    verse: "But remember the Lord your God, for it is he who gives you the ability to produce wealth.",
    reflection: "Wanting to increase your income isn't greedy when your motives are right. God gives you the ability to earn, and He's pleased when you develop skills that expand your capacity to provide and give. Are you being paid fairly? Are you developing marketable skills? Are you working with excellence? Increasing income requires intentionality: negotiating salary, building side income, pursuing advancement, or starting a business. But never forget the source - God gives the ability. As your income grows, so should your giving, saving, and wise stewardship. Joseph, Lydia, and Paul understood this balance. They worked diligently, earned well, and used resources for kingdom purposes. What step toward income growth is God asking you to take?",
  },
  {
    id: "23",
    date: "2025-02-16",
    title: "True Financial Freedom",
    scripture: "John 8:36",
    verse: "So if the Son sets you free, you will be free indeed.",
    reflection: "Financial freedom isn't just a number in your bank account - it's peace that transcends circumstances. It's having margin, options, and the ability to give generously without stress. It's making life decisions based on God's calling, not paycheck necessity. True freedom means you're not controlled by debt, comparison, or financial anxiety. Building financial freedom takes time: eliminating debt, saving an emergency fund, investing consistently, and living below your means. But it's worth every sacrifice. Imagine the peace of weathering emergencies without panic, the joy of generous giving, the liberty of pursuing God's call without financial barriers. That freedom is possible. Will you commit to the journey?",
  },
  {
    id: "24",
    date: "2025-02-17",
    title: "Move Your Body, Honor Your God",
    scripture: "1 Corinthians 9:27",
    verse: "I discipline my body like an athlete, training it to do what it should.",
    reflection: "Exercise isn't vanity - it's stewardship. Your body is God's temple, and how you care for it matters. Paul understood physical discipline. He compared the Christian life to athletic training - requiring focus, effort, and consistency. When you exercise, you're not just building muscle; you're increasing energy, improving mood, and preparing yourself to serve God effectively. A healthy body supports a healthy mind and spirit. You don't need to become a fitness fanatic - just move daily. Walk, stretch, dance, play sports. Find joy in movement. As you exercise, pray and thank God for your body's ability to move. Let fitness be an act of worship, honoring the One who created you and called you to serve with strength and vitality.",
  },
  {
    id: "25",
    date: "2025-02-18",
    title: "The Power of Spoken Blessings",
    scripture: "Proverbs 18:21",
    verse: "The tongue has the power of life and death, and those who love it will eat its fruit.",
    reflection: "Your words shape reality more than you realize. When you speak blessing over your spouse, children, friends, or coworkers, you're participating in God's creative power. Blessing isn't just saying nice things - it's prophetically declaring God's truth and potential over someone's life. Tell your child they're capable and watch them rise to the challenge. Affirm your spouse's strengths and see them flourish. Encourage a struggling friend and witness hope return. Your words can build up or tear down, heal or wound, inspire or discourage. Choose life. Make it a daily practice: speak blessing at breakfast, before bed, in passing moments. Your tongue is a powerful tool - use it to reflect God's heart and call forth the best in everyone around you.",
  },
  {
    id: "26",
    date: "2025-02-19",
    title: "Rest is Resistance",
    scripture: "Exodus 20:8",
    verse: "Remember the Sabbath day by keeping it holy.",
    reflection: "In a culture that glorifies busyness, rest is revolutionary. God didn't suggest Sabbath - He commanded it. One full day each week of rest, worship, and restoration. Why? Because He knows you need it. Physically, emotionally, and spiritually. Rest isn't laziness; it's trust. It says, 'I believe God can run the world without me for 24 hours.' It's setting boundaries against the tyranny of productivity. It's choosing to be a human being, not a human doing. Your Sabbath might be Sunday, or it might be another day. What matters is that you protect it fiercely. No work emails, no projects, no hustle. Just rest, worship, family, joy, and margin. God doesn't need your exhaustion. He wants your trust. Will you rest?",
  },
  {
    id: "27",
    date: "2025-02-20",
    title: "Friendship as Spiritual Warfare",
    scripture: "Ecclesiastes 4:9-10",
    verse: "Two are better than one, because they have a good return for their labor: If either of them falls down, one can help the other up.",
    reflection: "Isolation is one of the enemy's favorite tactics. When you're alone, you're vulnerable to lies, discouragement, and sin. God designed you for community - not just church attendance, but genuine, deep friendships. Friends who know your struggles and still love you. Friends who call out your potential and confront your sin. Friends who pray for you, laugh with you, and show up in crisis. This level of friendship doesn't happen accidentally. It requires vulnerability, time, and commitment. Are you known? Do you have people who can speak truth into your life? If not, start small. Invite someone to coffee. Join a small group. Be honest about your need for connection. Authentic friendship is worth fighting for - it might even save your life.",
  },
  {
    id: "28",
    date: "2025-02-21",
    title: "When God Seems Silent",
    scripture: "Psalm 13:1",
    verse: "How long, Lord? Will you forget me forever? How long will you hide your face from me?",
    reflection: "Sometimes God feels distant. You pray, but heaven seems silent. You worship, but experience no presence. You're not alone - even King David felt this way. The psalms are filled with his honest cries: 'How long, Lord?' Here's what matters: David didn't stop praying. His lament was still prayer. He brought his confusion, frustration, and pain directly to God. Silence doesn't mean God has abandoned you. Sometimes He's working behind the scenes. Sometimes He's teaching you to trust Him without feelings. Sometimes He's preparing you for something greater. Don't let silence drive you from God - let it drive you to Him. Keep showing up. Keep seeking. Keep believing. The sunrise always comes, even after the darkest night. Hold on.",
  },
  {
    id: "29",
    date: "2025-02-22",
    title: "Generational Influence",
    scripture: "Deuteronomy 6:6-7",
    verse: "These commandments that I give you today are to be on your hearts. Impress them on your children. Talk about them when you sit at home and when you walk along the road.",
    reflection: "You're not just living for yourself - you're setting a trajectory for generations you'll never meet. Your faith, values, and choices ripple through time. The way you honor God today influences your children, their children, and beyond. This is both sobering and exciting. What legacy are you building? Are you modeling authentic faith, or just religious performance? Are you teaching your kids to love God, or just avoid sin? Generational influence happens in ordinary moments - bedtime prayers, dinner conversations, how you handle stress, the way you treat your spouse. You don't have to be perfect, but you do have to be real. Let your children see you worship, struggle, repent, and trust God. That authenticity will shape their faith more than any sermon. What you're building matters eternally.",
  },
  {
    id: "30",
    date: "2025-02-23",
    title: "The Ministry of Presence",
    scripture: "Romans 12:15",
    verse: "Rejoice with those who rejoice; mourn with those who mourn.",
    reflection: "Sometimes the most powerful thing you can offer is simply showing up. Not with answers, advice, or attempts to fix everything - just your presence. When someone is grieving, they don't need your theology about suffering. When someone is celebrating, they don't need your caution about pride. They need you to be present. To sit in the pain without rushing to resolution. To share the joy without stealing the spotlight. Jesus modeled this perfectly. He wept with Mary and Martha. He celebrated at the wedding in Cana. He was fully present in every moment. In our distracted, hurried culture, presence is rare and precious. Put down your phone. Make eye contact. Listen more than you talk. Let people feel seen and heard. Sometimes God's love is most tangible not in your words, but in your willingness to simply be there. Show up. Stay. That's ministry.",
  },
  {
    id: "31",
    date: "2025-02-24",
    title: "Wisdom for Every Decision",
    scripture: "James 1:5",
    verse: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.",
    reflection: "Facing a tough decision? God isn't hiding His wisdom - He promises to give it generously when you ask. The key is asking in faith, believing He will guide you. Wisdom isn't just knowledge; it's knowing how to apply truth to your specific situation. Whether you're deciding about a job, relationship, investment, or any life choice, God wants to direct your steps. Don't lean on your own understanding alone. Seek His perspective through prayer, Scripture, and wise counsel. Today, bring that pressing decision to God. Ask for wisdom, then watch for His leading through peace, circumstances, and confirmation. He will guide you.",
  },
  {
    id: "32",
    date: "2025-02-25",
    title: "The Gift of Today",
    scripture: "Psalm 118:24",
    verse: "This is the day the Lord has made; let us rejoice and be glad in it.",
    reflection: "Today is a gift - that's why it's called the present. You didn't earn it; God gave it. Yesterday is gone, tomorrow isn't promised, but today is here. Don't waste it worrying about the past or anxious about the future. God has purpose packed into this very day. Yes, even if it's an ordinary Tuesday. The ordinary becomes extraordinary when lived with gratitude and intentionality. What if you approached today as your only day? What would you prioritize? Who would you love? What would you say? Choose joy today. Find beauty in small moments. Speak words of life. Serve someone. Worship freely. This is the day the Lord has made - don't miss it.",
  },
  {
    id: "33",
    date: "2025-02-26",
    title: "Breaking the Comparison Trap",
    scripture: "Galatians 6:4",
    verse: "Each one should test their own actions. Then they can take pride in themselves alone, without comparing themselves to someone else.",
    reflection: "Social media makes comparison inevitable. Someone always has a better job, body, family, vacation, or life - at least that's what their highlight reel shows. But comparison steals joy and distorts truth. God didn't call you to be anyone else; He called you to be you. Your journey is unique. Your gifts are specific. Your calling is personal. When you compare, you dishonor the masterpiece God is creating in your life. Instead of measuring yourself against others, evaluate your own growth. Are you more like Jesus than last year? That's what matters. Celebrate others' wins without diminishing yours. Run your race. God's plan for you is perfect - don't trade it for someone else's.",
  },
  {
    id: "34",
    date: "2025-02-27",
    title: "Guard Your Heart",
    scripture: "Proverbs 4:23",
    verse: "Above all else, guard your heart, for everything you do flows from it.",
    reflection: "Your heart is the wellspring of your life. What goes into it eventually comes out in your attitudes, words, and actions. That's why you must guard it carefully. What are you allowing into your heart? What media are you consuming? What conversations are you having? What thoughts are you entertaining? Garbage in, garbage out. But good seed planted produces good fruit. Guard your heart by being selective about inputs. Limit negative news. Choose uplifting content. Spend time in Scripture. Surround yourself with positive people. Feed your mind truth. When you protect your heart, you protect your future. What needs to be filtered out today? What good thing needs to be let in?",
  },
  {
    id: "35",
    date: "2025-02-28",
    title: "The Power of Gratitude",
    scripture: "1 Thessalonians 5:18",
    verse: "Give thanks in all circumstances; for this is God's will for you in Christ Jesus.",
    reflection: "Gratitude changes everything. It shifts your focus from what's wrong to what's right, from lack to abundance, from complaint to contentment. Notice Paul doesn't say 'give thanks for all circumstances' but 'in all circumstances.' You don't have to be thankful for cancer, but you can be thankful in it - for medical care, support, God's presence. Gratitude is a discipline, especially when life is hard. Start small: list three things you're grateful for right now. Your breath, your sight, water to drink. Build from there. Keep a gratitude journal. Say thanks before complaining. Watch how it transforms your perspective. A grateful heart is a magnet for joy, a repellent for bitterness, and a reflection of trust in God's goodness. Practice gratitude today.",
  },
  {
    id: "36",
    date: "2025-03-01",
    title: "When You Feel Inadequate",
    scripture: "2 Corinthians 12:9",
    verse: "But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.'",
    reflection: "Feeling inadequate? Good. That's where God works best. Paul begged God to remove his weakness, but God said no. Why? Because divine power shines brightest through human weakness. When you're strong, you rely on yourself. When you're weak, you rely on God - and that's when miracles happen. Your inadequacy isn't disqualifying; it's your invitation to experience God's sufficiency. Moses stuttered but led a nation. Gideon was fearful but defeated armies. David was a shepherd boy but killed a giant. God specializes in using weak people to do strong things. Stop waiting to feel qualified. Your weakness + God's strength = more than enough. Today, bring your inadequacy to God and watch His power work through you.",
  },
  {
    id: "37",
    date: "2025-03-02",
    title: "The Cost of Unforgiveness",
    scripture: "Matthew 6:14-15",
    verse: "For if you forgive other people when they sin against you, your heavenly Father will also forgive you. But if you do not forgive others their sins, your Father will not forgive your sins.",
    reflection: "Unforgiveness is like drinking poison and expecting the other person to die. It doesn't hurt them - it destroys you. Bitterness, resentment, and grudges imprison your heart and limit your relationship with God. Notice Jesus connects your forgiveness from God to your forgiveness of others. Why? Because unforgiveness reveals a hard heart that hasn't fully grasped God's grace. You've been forgiven an unpayable debt - how can you withhold forgiveness from others? Forgiving doesn't mean what they did was okay. It means you're releasing them to God and freeing yourself from bitterness. It's a choice, not a feeling. Today, who do you need to forgive? Release them. Not for their sake, but for yours. Freedom awaits.",
  },
  {
    id: "38",
    date: "2025-03-03",
    title: "Your Words Create Worlds",
    scripture: "Proverbs 18:21",
    verse: "The tongue has the power of life and death, and those who love it will eat its fruit.",
    reflection: "Your words are powerful - they create reality. Speak defeat, and you'll live defeated. Speak faith, and you'll see possibilities. Speak blessing, and you'll experience abundance. Words aren't just sounds; they're spiritual forces that shape your world. God spoke creation into existence. You're made in His image - your words matter. What are you speaking over your life, your family, your future? Are you declaring God's promises or agreeing with fear? Change your words, change your life. Stop saying 'I'm broke' - say 'I'm building wealth.' Stop saying 'I'm stressed' - say 'I'm learning to trust God.' Stop saying 'I can't' - say 'With God, I can.' Your tongue is a powerful tool. Use it wisely. Speak life today.",
  },
  {
    id: "39",
    date: "2025-03-04",
    title: "The Battle for Your Mind",
    scripture: "Romans 12:2",
    verse: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.",
    reflection: "Your biggest battlefield is your mind. What you think determines how you live. Negative thoughts produce negative outcomes. God-centered thoughts produce godly living. That's why Paul says be transformed by renewing your mind - it's an ongoing process. You can't change your past, but you can change how you think about it. You can't control circumstances, but you can control your response. Renew your mind by filling it with truth. Read Scripture daily. Meditate on God's promises. Replace lies with truth. When fear whispers 'you'll fail,' counter with 'I can do all things through Christ.' When shame says 'you're not enough,' respond with 'I'm chosen and loved.' Win the battle in your mind, and you'll win the battle in your life. What thought needs renewing today?",
  },
  {
    id: "40",
    date: "2025-03-05",
    title: "Patience in the Process",
    scripture: "Galatians 6:9",
    verse: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.",
    reflection: "You're doing the right things, but not seeing results yet. Don't quit. Harvest takes time. A farmer doesn't plant seeds Monday and expect corn Friday. Growth happens underground before it's visible. Keep going. Your faithfulness matters more than your feelings. The process is developing character you'll need for the harvest. What if you're one prayer, one day, one act of obedience away from breakthrough? Many people give up right before the miracle. Don't be that person. Keep praying, keep believing, keep obeying. God sees your effort. He honors persistence. Your harvest is coming - at the proper time. Not your time. His time. And His timing is always perfect. Today, choose patience. Choose trust. Choose one more day of faithfulness.",
  },
  {
    id: "41",
    date: "2025-03-06",
    title: "You Are Not Alone",
    scripture: "Hebrews 13:5",
    verse: "Never will I leave you; never will I forsake you.",
    reflection: "Loneliness whispers lies: 'No one understands. No one cares. You're all alone.' But God says: 'I'm right here. I haven't left. I won't forsake you.' Feelings lie, but God's Word is true. Even when you don't feel His presence, He's there. Even when friends disappoint, He remains. Even in the darkest valley, He walks beside you. You're never alone. God is with you in every moment - the celebrated victories and the hidden struggles. He knows your name, your pain, your fears, your dreams. He's not distant or distracted. He's present, attentive, and actively working on your behalf. Today, if you feel alone, talk to Him. Tell Him what you're feeling. Listen for His response. You'll find He's been there all along, waiting to comfort you. You're not alone. You never were.",
  },
  {
    id: "42",
    date: "2025-03-07",
    title: "Trusting God's Timing",
    scripture: "Ecclesiastes 3:1",
    verse: "There is a time for everything, and a season for every activity under the heavens.",
    reflection: "Waiting is hard when you're ready now. But God's timing is rarely your timing - and that's a good thing. He sees the whole picture; you see one frame. He knows what you need to learn, who you need to meet, how you need to grow before the door opens. His delays aren't denials; they're divine appointments. Joseph waited years in prison before becoming prime minister. David was anointed king but shepherded sheep for years before wearing a crown. Your waiting isn't wasted - it's working something in you that you'll need for what's next. Trust the process. Trust the Planner. God hasn't forgotten your dream; He's preparing you for it. What if your delay is actually divine protection or perfect positioning? Keep trusting. Your season is coming.",
  },
  {
    id: "43",
    date: "2025-03-08",
    title: "The Sin You're Tolerating",
    scripture: "Hebrews 12:1",
    verse: "Let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us.",
    reflection: "What sin have you been tolerating? Not the big, obvious ones - the subtle sins you've made peace with. The little compromises. The 'not that bad' habits. The 'everyone does it' behaviors. Secret sins that nobody knows about. Here's the truth: sin that's tolerated will eventually dominate. What starts as a small compromise becomes a stronghold. That's why you must throw it off - not minimize it, not manage it, but eliminate it. Confession is the first step. Bring it into the light. Tell God, tell a trusted friend. Get accountability. Break the shame-secrecy cycle. Then take practical steps: delete the app, avoid the trigger, change the routine. God offers grace for repentance and power for change. You don't have to stay stuck. What sin is hindering your race? Throw it off today.",
  },
  {
    id: "44",
    date: "2025-03-09",
    title: "When Prayer Feels Pointless",
    scripture: "Luke 18:1",
    verse: "Then Jesus told his disciples a parable to show them that they should always pray and not give up.",
    reflection: "You've prayed for months, maybe years, and nothing has changed. Prayer feels pointless. Why keep asking? Jesus anticipated this question and told a story: a widow persistently petitioned an unjust judge until he gave her justice. Jesus' point? If persistence works with an unjust judge, how much more with a loving Father? Keep praying. Don't give up. God isn't ignoring you; He's working in ways you can't see. Sometimes delays build character. Sometimes timing isn't right. Sometimes the answer is 'not yet' or 'something better.' But persistent prayer is never wasted. It changes you even when circumstances don't change. It builds faith. It aligns your heart with God's. It positions you for breakthrough. Today, pray again. Believe again. Trust again. Don't give up.",
  },
  {
    id: "45",
    date: "2025-03-10",
    title: "Your Identity in Christ",
    scripture: "2 Corinthians 5:17",
    verse: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!",
    reflection: "Who are you? Your answer to that question shapes everything. If you identify by your past, you're trapped. If you identify by your mistakes, you're condemned. If you identify by others' opinions, you're unstable. But if you identify as a new creation in Christ, you're free. Your identity isn't based on what you've done but on what Christ has done for you. You're not defined by your worst moment. You're defined by His best moment - the cross. You're forgiven, loved, chosen, adopted, redeemed, justified, sanctified, and being transformed. The old you - the shame, the guilt, the failure - is gone. The new you - radiant, righteous, and empowered - is here. Live from your new identity, not your old one. You're not who you were. You're who He says you are.",
  },
  {
    id: "46",
    date: "2025-03-11",
    title: "Investing in Eternity",
    scripture: "Matthew 6:19-20",
    verse: "Do not store up for yourselves treasures on earth, where moths and vermin destroy, and where thieves break in and steal. But store up for yourselves treasures in heaven.",
    reflection: "Everything on earth is temporary. Your car will rust. Your house will decay. Your bank account won't transfer to eternity. Only three things last forever: God, His Word, and people. That's it. So the question is: what are you investing in? Are you building an earthly kingdom or God's kingdom? Are you living for now or forever? This doesn't mean you can't enjoy earthly blessings - God gives us richly all things to enjoy. But it does mean holding them loosely and prioritizing eternal investments: leading people to Christ, discipling believers, giving generously, serving faithfully. One day you'll stand before God. What will matter then? Not your résumé, but your faithfulness. Not your possessions, but your obedience. Not what you accumulated, but what you gave away. Today, invest in something that will outlast you.",
  },
  {
    id: "47",
    date: "2025-03-12",
    title: "The Gift of Difficult People",
    scripture: "Matthew 5:44",
    verse: "But I tell you, love your enemies and pray for those who persecute you.",
    reflection: "That difficult person in your life? God put them there. Not to torment you, but to transform you. They're sandpaper smoothing your rough edges. They expose areas where you need to grow in patience, forgiveness, love, and grace. Easy people don't develop character; difficult people do. Jesus loved His enemies. Can you love yours? Not with warm feelings, but with a choice to bless them instead of curse them, pray for them instead of gossip about them, show kindness instead of revenge. This is supernatural love - impossible without God's help. But when you love difficult people, you become like Jesus. You break the cycle of retaliation. You demonstrate a love that confounds the world. Today, pray for that difficult person. Ask God to bless them. It will change you more than it changes them.",
  },
  {
    id: "48",
    date: "2025-03-13",
    title: "Overcoming Fear with Faith",
    scripture: "2 Timothy 1:7",
    verse: "For God has not given us a spirit of fear, but of power and of love and of a sound mind.",
    reflection: "Fear isn't from God. That anxious, panicked, 'what if' thinking? Not from Him. God gives power (courage to act), love (confidence in His care), and a sound mind (clear, rational thinking). Fear is a spirit - and you have authority over it. When fear knocks, let faith answer. Don't deny the fear; acknowledge it, then choose faith anyway. 'I'm afraid, but I trust God.' 'This is scary, but God is with me.' 'I don't know the outcome, but I know who holds the future.' Fear paralyzes. Faith mobilizes. Fear says 'what if it goes wrong?' Faith says 'what if it goes right?' Today, what are you afraid of? Name it. Now counter it with truth. Replace fear with a promise from God's Word. Speak it out loud. Fear loses power when you confront it with faith.",
  },
  {
    id: "49",
    date: "2025-03-14",
    title: "The Discipline of Margin",
    scripture: "Psalm 23:2",
    verse: "He makes me lie down in green pastures, he leads me beside quiet waters.",
    reflection: "Your calendar is full. Your to-do list is endless. You rush from one thing to the next, always behind, always stressed. Sound familiar? God didn't design you to live at maximum capacity 24/7. Even He rested on the seventh day. You need margin - blank space in your schedule, room to breathe, time for unplanned moments. Margin isn't laziness; it's wisdom. It's saying no to good things so you can say yes to God things. It's leaving space for divine interruptions. It's prioritizing people over productivity. Without margin, you're too busy to hear God's voice, too rushed to notice someone's need, too exhausted to enjoy your own life. Today, evaluate your schedule. What can you cut? What can you delegate? What can you simply let go? Create margin. Breathe. Rest. Live.",
  },
  {
    id: "50",
    date: "2025-03-15",
    title: "When You Feel Like Quitting",
    scripture: "Galatians 6:9",
    verse: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.",
    reflection: "You're tired. You've tried everything. Nothing's working. You're ready to quit. But what if you're closer to breakthrough than you think? What if the enemy is fighting hardest right before your victory? Don't quit on a bad day. Don't make permanent decisions based on temporary emotions. When you feel like quitting, that's precisely when you need to press in harder. Pray more, not less. Worship louder, not quieter. Surround yourself with encouragers, not critics. Remember why you started. Recall what God promised. Look how far you've come. Your feelings lie, but God's promises are true. The harvest is coming. Your breakthrough is near. One more day. One more prayer. One more step of faith. Don't give up now. You've got this - because God's got you.",
  },
  {
    id: "51",
    date: "2025-03-16",
    title: "The Sacrifice of Praise",
    scripture: "Hebrews 13:15",
    verse: "Through Jesus, therefore, let us continually offer to God a sacrifice of praise—the fruit of lips that openly profess his name.",
    reflection: "Notice it's called a 'sacrifice' of praise. Why? Because sometimes praise costs you something. It's easy to praise when life is good. But praising when life is hard? That's a sacrifice. When you're in pain but still say 'God is good.' When you're confused but still say 'God is faithful.' When you're disappointed but still say 'God knows what He's doing.' That's sacrificial worship. And it's powerful. It doesn't deny your pain; it declares God's supremacy over it. Praise in the storm doesn't change the storm, but it changes you in the storm. It shifts your focus from problem to Provider. Today, offer a sacrifice of praise. Even if you don't feel like it. Even if nothing's changed. Praise Him anyway. Watch what happens in your heart.",
  },
  {
    id: "52",
    date: "2025-03-17",
    title: "Breaking Generational Curses",
    scripture: "Exodus 20:5-6",
    verse: "I the Lord your God am a jealous God, punishing the children for the sin of the parents to the third and fourth generation of those who hate me, but showing love to a thousand generations of those who love me.",
    reflection: "Patterns in your family? Addiction, divorce, poverty, abuse? Those aren't just coincidence - they're generational strongholds. But here's good news: in Christ, you have authority to break them. You're not destined to repeat your parents' mistakes. The cycle stops with you. Through Christ, you can be the one who breaks the pattern and establishes a new legacy. It requires intentionality: acknowledging the pattern, repenting for your participation, forgiving those who hurt you, and making different choices. Get counseling. Build healthy relationships. Establish godly habits. Speak blessing over your children. The curse is real, but Christ's redemption is more powerful. Today, declare: 'As for me and my house, we will serve the Lord.' Break the curse. Start a blessing.",
  },
  {
    id: "53",
    date: "2025-03-18",
    title: "The Power of Consistent Obedience",
    scripture: "Luke 16:10",
    verse: "Whoever can be trusted with very little can also be trusted with much.",
    reflection: "Big breakthroughs are built on small obediences. Faithfulness in little things qualifies you for greater things. Did you pray when you didn't feel like it? That's obedience. Did you tithe when money was tight? That's faithfulness. Did you forgive when it hurt? That's maturity. God is watching these 'small' choices. They're not small to Him - they're proof of character. Joseph was faithful in prison before he ruled Egypt. David was faithful with sheep before leading Israel. Jesus was faithful in carpentry before starting ministry. Your current assignment might seem insignificant, but it's preparation for something greater. Don't despise the day of small beginnings. Be faithful where you are, and God will expand your influence. Excellence isn't reserved for big stages; it's practiced in hidden places. Today, be faithful in the little things.",
  },
  {
    id: "54",
    date: "2025-03-19",
    title: "Your Scars Tell a Story",
    scripture: "Revelation 1:18",
    verse: "I am the Living One; I was dead, and now look, I am alive for ever and ever!",
    reflection: "Jesus rose with His scars. He could have erased them, but He kept them as proof of victory. Your scars - emotional, spiritual, even physical - aren't signs of defeat. They're evidence of survival. Proof that you've been through something and came out the other side. Your mess is becoming your message. Your test is becoming your testimony. The pain you've endured is preparation for the people you'll help. Don't hide your scars; share them. When you're vulnerable about your struggles, you give others permission to be honest about theirs. Your story could be someone's lifeline. What the enemy meant for evil, God redeems for good. Today, thank God for your scars. They're proof you're still here, still fighting, still believing. Your survival is someone's hope.",
  },
  {
    id: "55",
    date: "2025-03-20",
    title: "When God Closes Doors",
    scripture: "Revelation 3:8",
    verse: "I know your deeds. See, I have placed before you an open door that no one can shut.",
    reflection: "That closed door hurts. It was the job you wanted, the relationship you envisioned, the opportunity you needed. But what if God closed it to protect you? What if He has something better? Closed doors aren't punishments; they're redirections. God's 'no' or 'not now' is protecting you from wrong timing, wrong fit, or wrong direction. Trust that He knows what He's doing. When one door closes, God opens another - often a better one. But you have to stop banging on the closed door to see the open one. Joseph's slavery in Egypt seemed like a closed door, but it positioned him to save nations. Paul couldn't preach in Asia, so he went to Europe and changed the western world. Today, release that closed door. Thank God for redirecting you. Your open door is coming.",
  },
  {
    id: "56",
    date: "2025-03-21",
    title: "Stewarding Your Mental Health",
    scripture: "3 John 1:2",
    verse: "Dear friend, I pray that you may enjoy good health and that all may go well with you, even as your soul is getting along well.",
    reflection: "Mental health isn't weakness - it's stewardship. Your mind is part of the temple God gave you to care for. Depression, anxiety, trauma - these aren't spiritual failures. They're real struggles that require real help. Jesus wept. David lamented. Elijah battled depression. Even biblical heroes struggled mentally. If you're struggling, get help. See a therapist. Take medication if needed. Join a support group. There's no shame in getting professional help any more than there's shame in seeing a doctor for a broken leg. God can heal miraculously, but He also works through counselors, doctors, and medicine. Taking care of your mental health isn't lack of faith; it's wise stewardship. Today, if you're struggling, reach out. Ask for help. You're not alone, and you're not weak. You're human.",
  },
  {
    id: "57",
    date: "2025-03-22",
    title: "Fighting for Your Marriage",
    scripture: "Mark 10:9",
    verse: "Therefore what God has joined together, let no one separate.",
    reflection: "Marriage is hard. Not because you married the wrong person, but because two sinners trying to become one will have friction. But don't give up. Your marriage is worth fighting for. When it's tough, remember why you started. Look at your wedding photos. Recall the promises you made. Choose love again - it's a decision, not just a feeling. Serve your spouse even when they don't deserve it. Communicate honestly, even when it's uncomfortable. Pray together, even when it's awkward. Get counseling before you need it. The enemy wants to destroy your marriage; don't give him a foothold. Fight for it. Fight fair. Fight together, not against each other. A strong marriage doesn't happen by accident; it happens by choice. Every single day. Today, do one thing to serve your spouse without expecting anything in return.",
  },
  {
    id: "58",
    date: "2025-03-23",
    title: "Your Calling Is Costly",
    scripture: "Luke 9:23",
    verse: "Then he said to them all: 'Whoever wants to be my disciple must deny themselves and take up their cross daily and follow me.'",
    reflection: "Following Jesus costs something. It might cost relationships, comfort, security, reputation, money, or time. Jesus never promised easy; He promised worth it. Your calling isn't a comfortable cruise; it's a costly adventure. It requires sacrifice. It demands surrender. It asks for everything. But what you gain infinitely surpasses what you give up. Knowing Christ. Experiencing purpose. Making eternal impact. Living fully alive. Peter left his fishing business. Paul abandoned his prestigious position. The disciples walked away from everything. What is your calling costing you? What is God asking you to lay down? The cost is real, but so is the reward. Don't let the cost deter you from your calling. The temporary sacrifice leads to eternal significance. Today, what is God asking you to surrender?",
  },
  {
    id: "59",
    date: "2025-03-24",
    title: "Raising Kingdom Kids",
    scripture: "Proverbs 22:6",
    verse: "Start children off on the way they should go, and even when they are old they will not turn from it.",
    reflection: "Parenting is discipleship. You're not just raising good kids; you're raising world-changers for God's kingdom. This happens through intentional spiritual formation: daily prayer, regular Scripture reading, modeling authentic faith, and talking about God in everyday moments. Let your kids see you worship, struggle, repent, and trust God. Don't pretend to have it all together. Show them what real faith looks like in real life. Take them to serve. Let them see you give generously. Discuss God's truth in natural conversations. Pray over them nightly. Speak blessing and identity. Your kids need your presence more than presents, your time more than things. They're watching you, learning from you, becoming like you. What legacy are you establishing? Today, pray with your kids. Tell them one way you saw God work in your life.",
  },
  {
    id: "60",
    date: "2025-03-25",
    title: "The Courage to Start Again",
    scripture: "Lamentations 3:22-23",
    verse: "Because of the Lord's great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.",
    reflection: "You failed. You messed up. You fell. Again. And you're wondering if you can start over. Yes. God's mercies are new every morning. Not recycled, not rationed - new. Fresh. Abundant. No matter what yesterday held, today is a new beginning. God isn't keeping score. He's not holding grudges. He's not punishing you. He's offering grace and inviting you to try again. Peter denied Jesus three times but became a pillar of the church. Moses murdered but delivered Israel. Paul persecuted Christians but wrote most of the New Testament. Your past doesn't disqualify you; it positions you to help others who struggle similarly. Today is a fresh start. Get up. Try again. God believes in you even when you don't believe in yourself. His compassions never fail. Start again.",
  },
  {
    id: "61",
    date: "2025-03-26",
    title: "Walking in Humility",
    scripture: "Micah 6:8",
    verse: "He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.",
    reflection: "Humility isn't thinking less of yourself; it's thinking of yourself less. It's acknowledging that everything you have is a gift from God. Your talents? He gave them. Your opportunities? He opened them. Your breath? He sustains it. Pride says 'look what I did.' Humility says 'look what God did through me.' Pride competes and compares. Humility celebrates and serves. Pride needs recognition. Humility finds fulfillment in obedience regardless of applause. Walk humbly by staying teachable, admitting when you're wrong, serving without needing credit, and pointing glory to God instead of yourself. The world elevates self-promotion, but God exalts the humble. When you decrease, He increases. Today, serve someone without telling anyone. Deflect a compliment to give God glory. Ask for help instead of pretending you have it all together.",
  },
  {
    id: "62",
    date: "2025-03-27",
    title: "Finding Your Community",
    scripture: "Hebrews 10:24-25",
    verse: "And let us consider how we may spur one another on toward love and good deeds, not giving up meeting together, as some are in the habit of doing, but encouraging one another.",
    reflection: "You can't do life alone. You need community - people who know you, challenge you, encourage you, and pray for you. Church isn't optional; it's essential. Not just attending, but connecting. Don't just sit in rows; do life together. Join a small group. Serve on a team. Build relationships beyond Sunday. Authentic community requires vulnerability. Let people see your mess. Ask for help. Admit struggles. When you're real, others will be too. Iron sharpens iron - that requires friction. Let godly people speak truth into your life, even when it's uncomfortable. Community isn't about finding perfect people; it's about imperfect people pursuing Christ together. Today, reach out. Invite someone to coffee. Join a group. Show up. Your people are waiting.",
  },
  {
    id: "63",
    date: "2025-03-28",
    title: "The Blessing of Boundaries",
    scripture: "Proverbs 4:23",
    verse: "Above all else, guard your heart, for everything you do flows from it.",
    reflection: "Boundaries aren't walls; they're fences that keep good things in and harmful things out. Saying 'no' isn't selfish; it's self-care that enables you to say 'yes' to what matters. You can't serve everyone. You can't attend every event. You can't meet every need. Jesus had boundaries - He often withdrew to pray, said no to demands, and prioritized His mission. Healthy boundaries protect your time, energy, relationships, and calling. They prevent burnout and resentment. Set boundaries with toxic people, excessive commitments, unhealthy habits, and draining activities. Don't feel guilty for protecting your peace. 'No' is a complete sentence. Today, identify one boundary you need to establish. Maybe it's limiting social media, saying no to an extra commitment, or addressing a difficult relationship. Set the boundary. Protect your heart.",
  },
  {
    id: "64",
    date: "2025-03-29",
    title: "Your Work Matters to God",
    scripture: "Colossians 3:23-24",
    verse: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters, since you know that you will receive an inheritance from the Lord as a reward.",
    reflection: "Your work isn't just a job - it's a calling. Whether you're a CEO, cashier, teacher, or stay-at-home parent, your work matters to God. You're not working for a paycheck or a boss; you're working for the Lord. Excellence in your work is worship. Integrity in your dealings is witness. Kindness to coworkers is ministry. Your workplace is your mission field. People are watching how you handle stress, treat others, and respond to challenges. Let your work ethic point them to Jesus. Don't compartmentalize sacred and secular. All work done for God's glory is sacred. Today, approach your tasks as an offering to God. Do your best, not to impress people, but to honor Him. Let your work be worship.",
  },
  {
    id: "65",
    date: "2025-03-30",
    title: "Celebrating Small Wins",
    scripture: "Zechariah 4:10",
    verse: "Do not despise these small beginnings, for the Lord rejoices to see the work begin.",
    reflection: "You're frustrated because progress feels slow. But small wins matter. Every step forward, no matter how small, is progress. You woke up and prayed - that's a win. You chose kindness when you wanted to snap - that's growth. You paid an extra $50 on debt - that's momentum. Don't despise small beginnings or incremental progress. God celebrates the work beginning, not just the work completed. Every giant was once a baby. Every oak was once an acorn. Every marathon begins with one step. Small, consistent actions over time produce massive results. The key is consistency. Keep showing up. Keep trying. Keep believing. Today, celebrate one small win. Acknowledge your progress, however minor it seems. Thank God for how far you've come. Small wins compound into big victories.",
  },
  {
    id: "66",
    date: "2025-03-31",
    title: "Living with Intentionality",
    scripture: "Ephesians 5:15-16",
    verse: "Be very careful, then, how you live—not as unwise but as wise, making the most of every opportunity, because the days are evil.",
    reflection: "Life doesn't happen by accident; it happens by intention. Intentional people don't drift; they direct. They set goals, make plans, and execute with purpose. Without intentionality, you'll waste time, miss opportunities, and live reactively instead of proactively. Intentionality applies to everything: relationships (schedule time), health (plan meals), finances (create budgets), faith (establish rhythms). Wise living isn't complicated; it's intentional. Today, evaluate your life. Are you living by design or default? What needs more intention - your marriage, parenting, career, faith, friendships? Pick one area and set a specific goal this week. Write it down. Tell someone. Take action. Don't let life happen to you. Happen to life. Be intentional.",
  },
  {
    id: "67",
    date: "2025-04-01",
    title: "The Gift of Mentorship",
    scripture: "2 Timothy 2:2",
    verse: "And the things you have heard me say in the presence of many witnesses entrust to reliable people who will also be qualified to teach others.",
    reflection: "You need two types of people in your life: mentors and mentees. Mentors who've been where you're going, who can guide, challenge, and encourage you. And mentees you're pouring into, passing on what you've learned. Paul mentored Timothy. Timothy mentored others. That's multiplication. Don't try to figure everything out alone. Find someone ahead of you and ask for guidance. And don't wait until you 'arrive' to mentor others. You're qualified to help people a few steps behind you. Your mess is someone's message. Your lessons are someone's shortcut. Today, identify someone you could mentor - a younger believer, new employee, struggling parent. Reach out. Offer coffee. Start the conversation. And if you need mentoring, ask someone you respect. Most people are honored to help; they're just waiting to be asked.",
  },
  {
    id: "68",
    date: "2025-04-02",
    title: "Breaking Free from Addiction",
    scripture: "1 Corinthians 10:13",
    verse: "No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can endure it.",
    reflection: "Addiction feels like chains you can't break. But freedom is possible. Not through willpower alone, but through God's power combined with practical steps. Admit you have a problem. Bring it into the light. Tell someone you trust. Get professional help - counseling, rehab, support groups. Identify triggers and avoid them. Replace the addiction with healthy habits. Build accountability. This isn't about perfection; it's about progress. You might relapse, but that doesn't mean you failed - it means you're human. Get back up. Keep fighting. God doesn't condemn you; He empowers you. His grace is sufficient. His power is made perfect in weakness. Freedom is yours in Christ. Today, take one step: call a counselor, attend a meeting, confess to a friend, delete the app. Break one chain. Freedom is worth fighting for.",
  },
  {
    id: "69",
    date: "2025-04-03",
    title: "Your Unique Gifting",
    scripture: "1 Peter 4:10",
    verse: "Each of you should use whatever gift you have received to serve others, as faithful stewards of God's grace in its various forms.",
    reflection: "God gave you unique gifts, talents, and passions - not for your glory, but for His purposes and others' good. Your gifts aren't random; they're intentional. They reveal how God wants to use you to impact the world. Maybe you're a natural encourager, gifted teacher, creative artist, strategic thinker, or compassionate servant. Don't compare your gifts to others. Don't covet their calling. Use what God gave you. Steward your gifts by developing them, deploying them, and using them to serve. Your gifts are needed. There's someone only you can reach, a problem only you can solve, a message only you can deliver. Don't bury your talents. Today, identify one gift God gave you. How can you use it this week to serve someone? Deploy your gift. Steward your calling.",
  },
  {
    id: "70",
    date: "2025-04-04",
    title: "Hope for the Prodigal",
    scripture: "Luke 15:20",
    verse: "But while he was still a long way off, his father saw him and was filled with compassion for him; he ran to his son, threw his arms around him and kissed him.",
    reflection: "If you're far from God, feeling like you've gone too far or messed up too much, listen: the Father is watching for you. He's not angry; He's waiting. He's not pointing His finger; He's opening His arms. You don't have to clean up before you come home. Come as you are. Broken. Ashamed. Empty. He'll restore you. The prodigal son wasted his inheritance, lived in sin, and hit rock bottom. But when he returned, his father didn't lecture him. He ran to him. Embraced him. Celebrated him. That's your Heavenly Father's heart toward you. Stop running. Turn around. Come home. Today, pray one simple prayer: 'Father, I'm coming home.' He's been waiting. He'll run to meet you.",
  },
  {
    id: "71",
    date: "2025-04-05",
    title: "The Power of Fasting",
    scripture: "Matthew 6:16-18",
    verse: "When you fast, do not look somber as the hypocrites do... But when you fast, put oil on your head and wash your face, so that it will not be obvious to others that you are fasting, but only to your Father.",
    reflection: "Fasting isn't about earning God's favor; it's about increasing your spiritual sensitivity. When you deny physical appetite, you awaken spiritual hunger. Fasting clarifies hearing God's voice, breaks strongholds, and intensifies intercession. It's not a formula or manipulation; it's a discipline that positions your heart. Fast from food, media, social networking - whatever dominates your attention. Use the time you'd normally spend on that thing to pray, read Scripture, and seek God. Don't broadcast your fast; that defeats the purpose. Between you and God. Start small: skip one meal, fast from social media for a day, dedicate a day to prayer. Watch how it sharpens your spiritual awareness and strengthens your dependence on God. Today, consider what you might fast from this week and why.",
  },
  {
    id: "72",
    date: "2025-04-06",
    title: "Transforming Your Thought Life",
    scripture: "Philippians 4:8",
    verse: "Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things.",
    reflection: "Your thought life shapes your whole life. Toxic thoughts produce toxic lives. God-centered thoughts produce godly living. You can't stop thoughts from coming, but you can choose which ones you entertain. When negative thoughts arise, take them captive. Replace lies with truth. 'I'm worthless' becomes 'I'm loved by God.' 'I'll never change' becomes 'I'm being transformed.' 'This is hopeless' becomes 'God is working.' Guard what you consume - media, conversations, content - because inputs become thoughts. Fill your mind with truth: Scripture, worship, encouraging content, life-giving conversations. Your mind is a battlefield. Win the war by controlling what you think about. Today, notice your thought patterns. When negativity hits, counter it with Philippians 4:8. Think on what's true, noble, right, pure, lovely, admirable.",
  },
  {
    id: "73",
    date: "2025-04-07",
    title: "When God Redirects Your Plans",
    scripture: "Proverbs 16:9",
    verse: "In their hearts humans plan their course, but the Lord establishes their steps.",
    reflection: "You had a plan. It made sense. You prayed about it, maybe even felt peace. But then God redirected. The job fell through. The relationship ended. The door closed. Now you're confused. Was I wrong? Did I miss God? Not necessarily. Sometimes God allows you to plan so He can redirect. Sometimes the plan was right for a season but not for now. Sometimes He's protecting you from something you can't see. God's redirections aren't rejections; they're course corrections. Trust that He knows what He's doing. If God is redirecting, don't fight it. Don't force doors. Don't cling to old plans. Release control. Stay flexible. Watch for His new direction. Today, if God is redirecting your plans, surrender. Ask Him: 'What now?' Trust His steps even when they don't match yours.",
  },
  {
    id: "74",
    date: "2025-04-08",
    title: "Honoring Your Parents",
    scripture: "Exodus 20:12",
    verse: "Honor your father and your mother, so that you may live long in the land the Lord your God is giving you.",
    reflection: "Honoring parents doesn't mean they were perfect. It means respecting the position God gave them, regardless of performance. Maybe your parents failed you. Maybe they weren't who you needed. You can acknowledge hurt while still choosing honor. Honoring doesn't require agreeing with them or enabling bad behavior. It means speaking respectfully, setting healthy boundaries, and not slandering them. It's treating them with dignity even when it's hard. If they weren't there for you, you can still break cycles, forgive freely, and choose to honor. If they were great, express gratitude. Call them. Thank them. Serve them as they age. God attaches blessing to this command. Today, how can you honor your parents? Maybe it's a phone call, a letter of gratitude, forgiveness extended, or simply praying for them.",
  },
  {
    id: "75",
    date: "2025-04-09",
    title: "Stewarding Your Resources Wisely",
    scripture: "1 Corinthians 4:2",
    verse: "Now it is required that those who have been given a trust must prove faithful.",
    reflection: "Everything you have is a trust from God: your time, talent, treasure, influence, relationships. None of it is truly 'yours' - it's His, entrusted to you. Stewardship asks: what are you doing with what God gave you? Faithful stewards manage wisely, invest strategically, and give generously. They don't hoard or waste. Are you stewarding your finances well - budgeting, saving, giving? Your time - investing in what matters? Your influence - pointing people to Jesus? Your body - treating it as God's temple? One day you'll give an account. Not to earn salvation - that's grace. But to show faithfulness with what He entrusted. Today, evaluate one area: finances, time, health, relationships. How are you stewarding it? What needs to change? Faithful stewardship honors God and positions you for more.",
  },
  {
    id: "76",
    date: "2025-04-10",
    title: "The Gift of Singleness",
    scripture: "1 Corinthians 7:7-8",
    verse: "I wish that all of you were as I am. But each of you has your own gift from God; one has this gift, another has that. Now to the unmarried and the widows I say: It is good for them to stay unmarried, as I do.",
    reflection: "Singleness isn't a waiting room for marriage; it's a gift with unique purpose. Yes, marriage is beautiful, but so is singleness. Paul called it a gift - undivided devotion to God, freedom to serve without distraction, ability to pursue calling without compromise. If you're single, don't waste this season wishing you were married. Steward it. Pursue God wholeheartedly. Develop your gifts. Serve freely. Build deep friendships. Travel. Take risks. Maximize this unique season. Your fulfillment isn't found in relationship status; it's found in Christ. Whether you marry or stay single, both are God's gift. Don't despise your current gift. Embrace it. Maximize it. Use it for His glory. Today, thank God for your singleness. Ask how He wants you to steward this season. Live fully now.",
  },
  {
    id: "77",
    date: "2025-04-11",
    title: "Bearing Good Fruit",
    scripture: "John 15:5",
    verse: "I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing.",
    reflection: "Fruitfulness isn't about trying harder; it's about staying connected. Branches don't strain to produce fruit - they simply stay attached to the vine, and fruit happens naturally. Same with you. When you abide in Christ - spending time with Him, obeying His Word, relying on His strength - fruit grows automatically. Love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control. You can't manufacture these qualities; they're produced by the Spirit as you stay connected to Jesus. Disconnected branches wither. Connected branches flourish. Today, evaluate your connection to Christ. Are you abiding or striving? Spending daily time with Him or running on fumes? Fruit is the evidence of your connection. Stay connected. The fruit will come.",
  },
  {
    id: "78",
    date: "2025-04-12",
    title: "Trusting God With Your Kids",
    scripture: "Psalm 127:3",
    verse: "Children are a heritage from the Lord, offspring a reward from him.",
    reflection: "Your kids aren't really yours - they're God's, entrusted to you. You can't control their choices, protect them from all pain, or guarantee outcomes. But you can pray, model faith, create a loving home, and trust God with them. Parenting is terrifying because you love deeply but control little. Your job is faithfulness; God's job is results. Pray over them daily. Speak blessing. Point them to Jesus. But release them to God. He loves them more than you do. Whether they're toddlers or adults, whether they're following Jesus or running from Him, keep praying. Keep believing. Keep trusting. God can reach them where you can't. Today, pray specifically for your kids. Release anxiety. Trust that God has them. He's faithful, even when you can't see what He's doing.",
  },
  {
    id: "79",
    date: "2025-04-13",
    title: "Overcoming Past Trauma",
    scripture: "Isaiah 43:18-19",
    verse: "Forget the former things; do not dwell on the past. See, I am doing a new thing! Now it springs up; do you not perceive it?",
    reflection: "Your past hurt you. Abuse, betrayal, loss, trauma - it left scars. And while the pain was real, it doesn't have to define your future. God wants to do something new in you. Not erasing the past, but redeeming it. Healing doesn't mean forgetting; it means the memory no longer controls you. Get help. See a counselor. Join a support group. Process the pain instead of burying it. Bring it into the light. Trauma thrives in secrecy and shame. Freedom comes through acknowledgment, forgiveness (not for them, but for you), and choosing not to let it steal your future. You're not damaged goods. You're a overcomer. A survivor. A testament to God's redemption. Today, if trauma haunts you, reach out for help. Healing is possible. Your past doesn't determine your future.",
  },
  {
    id: "80",
    date: "2025-04-14",
    title: "Living Generously",
    scripture: "Acts 20:35",
    verse: "It is more blessed to give than to receive.",
    reflection: "Generosity isn't about how much you have; it's about how much you hold loosely. The widow gave two coins and Jesus praised her. Her amount was small, but her heart was huge. Generosity flows from trust: trusting God to provide, to replenish, to bless. When you give generously - money, time, kindness, grace - you're declaring 'I trust God's provision more than my accumulation.' Generosity breaks greed's grip. It shifts focus from getting to giving, from hoarding to blessing. And here's the secret: you can't outgive God. The more you give, the more He provides. Not always financially, but in peace, joy, relationships, opportunities. Generosity opens heaven's windows. Today, practice generosity. Tip extra. Give anonymously. Buy someone's groceries. Give your time. Be generous with forgiveness, encouragement, and love. Watch how it changes you.",
  },
  {
    id: "81",
    date: "2025-04-15",
    title: "Your God-Given Purpose",
    scripture: "Jeremiah 29:11",
    verse: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.",
    reflection: "You're not an accident. God created you on purpose, for a purpose. Your life has meaning beyond paying bills and passing time. God has plans for you - good plans, hopeful plans, prosperous plans. But here's the catch: His plans require your participation. You must seek Him, trust Him, and step out in faith. Your purpose is found at the intersection of your gifts, passions, and the needs around you. What breaks your heart? What are you good at? What opportunities are in front of you? Start there. Purpose isn't one grand moment; it's a daily choice to steward what God gave you. Today, ask God: 'What's my next step?' Then take it. Your purpose unfolds one obedient step at a time.",
  },
  {
    id: "82",
    date: "2025-04-16",
    title: "The Ministry of Listening",
    scripture: "James 1:19",
    verse: "My dear brothers and sisters, take note of this: Everyone should be quick to listen, slow to speak and slow to become angry.",
    reflection: "In a world full of noise, listening is a rare gift. Everyone wants to be heard; few want to listen. But listening is ministry. When you truly listen - not just waiting for your turn to talk, but genuinely hearing someone - you're showing them they matter. Listening requires humility (admitting you don't know everything), patience (not interrupting), and love (caring about their experience). Most people don't need your advice; they need your attention. Put down your phone. Make eye contact. Ask questions. Let them finish. Sometimes the most powerful thing you can offer is simply listening without trying to fix, correct, or teach. Today, practice the ministry of listening. Have a conversation where your goal is to understand, not to respond. Listen fully. You'll be amazed how it blesses both them and you.",
  },
  {
    id: "83",
    date: "2025-04-17",
    title: "Breaking Free from Comparison",
    scripture: "2 Corinthians 10:12",
    verse: "We do not dare to classify or compare ourselves with some who commend themselves. When they measure themselves by themselves and compare themselves with themselves, they are not wise.",
    reflection: "Comparison is a joy thief. When you measure your chapter 3 against someone else's chapter 20, you'll always feel behind. Social media makes this worse - everyone's posting highlights while you're living real life. But comparison is foolish. You don't know their whole story, their struggles, or what it cost them. And even if you did, their journey isn't yours. God gave you a unique race to run. Stop looking sideways and start looking up. Focus on your growth, not someone else's. Celebrate their win without diminishing yours. Run your race with endurance. The only comparison that matters is this: are you more like Jesus today than yesterday? Today, notice when comparison creeps in. Stop it. Thank God for your unique journey. Celebrate someone else's win genuinely.",
  },
  {
    id: "84",
    date: "2025-04-18",
    title: "The Importance of Confession",
    scripture: "James 5:16",
    verse: "Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective.",
    reflection: "Secrecy gives sin power. Shame thrives in darkness. Confession brings freedom. Not just confessing to God (which is essential), but confessing to a trusted person who can pray with you and hold you accountable. Sin loses power when exposed to light. When you confess, you're breaking shame's hold. You're admitting you're not perfect and don't have it all together. And guess what? Neither does anyone else. Vulnerability invites connection. When you're real about your struggles, others feel safe being real about theirs. Find a trusted friend, pastor, or counselor. Confess that sin you've been hiding. Ask for prayer. Get accountability. Watch how quickly shame loses its grip. Today, who can you confess to? Don't let pride or fear keep you trapped. Confession brings healing.",
  },
  {
    id: "85",
    date: "2025-04-19",
    title: "Fighting Spiritual Warfare",
    scripture: "Ephesians 6:12",
    verse: "For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world and against the spiritual forces of evil in the heavenly realms.",
    reflection: "Your real enemy isn't people - it's spiritual forces. When relationships break, temptation intensifies, or circumstances crumble, recognize there's a spiritual battle. The enemy wants to kill, steal, and destroy. But you're not defenseless. God gave you armor: truth, righteousness, peace, faith, salvation, the Word, and prayer. Fight with these weapons. When lies attack, speak truth. When temptation comes, quote Scripture. When fear rises, worship. When opposition increases, pray. Don't fight people; fight spiritual forces through spiritual weapons. Stand firm. Don't retreat. The battle is real, but so is your authority in Christ. The victory is already won; you're enforcing it. Today, identify one spiritual attack you're facing. Speak Scripture over it. Pray against it. Stand firm.",
  },
  {
    id: "86",
    date: "2025-04-20",
    title: "Redeeming Your Time",
    scripture: "Ephesians 5:15-16",
    verse: "Be very careful, then, how you live—not as unwise but as wise, making the most of every opportunity, because the days are evil.",
    reflection: "Time is your most valuable resource. You can earn more money, but you can't get more time. Every day is 24 hours - how are you spending them? Scrolling endlessly? Binge-watching shows? Procrastinating? Or investing in what matters? Wise people redeem time. They prioritize relationships over entertainment, growth over comfort, eternal impact over temporary pleasure. This doesn't mean no rest or fun - God designed you for both. But it means being intentional. Track your time for one week. You'll be shocked where hours go. Then realign. What needs more time? What needs less? Make the most of every opportunity - not through frantic busyness, but through purposeful living. Today, identify one time-waster you can eliminate. Redirect that time toward something that matters. Redeem your time.",
  },
  {
    id: "87",
    date: "2025-04-21",
    title: "The Power of Corporate Worship",
    scripture: "Psalm 22:3",
    verse: "Yet you are enthroned as the Holy One; you are the one Israel praises.",
    reflection: "God inhabits the praises of His people. When believers gather to worship, His presence manifests powerfully. There's something about corporate worship you can't experience alone. Singing with hundreds or thousands of other voices reminds you you're not alone. Seeing others worship with hands raised and tears streaming encourages your own faith. Hearing the Word preached alongside others sharpens your understanding. Don't neglect gathering with believers. Yes, you can worship at home, but don't replace corporate worship with streaming services. Your physical presence matters. You need the church, and the church needs you. Your voice, your prayers, your gifts. Today, if you've been isolated, make a commitment to return to corporate worship. Find a church. Show up consistently. Worship with God's people.",
  },
  {
    id: "88",
    date: "2025-04-22",
    title: "When Your Faith Is Tested",
    scripture: "James 1:2-4",
    verse: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.",
    reflection: "Trials aren't fun, but they're purposeful. God uses them to grow you. Untested faith is immature faith. When everything's easy, you don't know what you really believe. But when trials come - financial pressure, health scares, relationship problems, loss - that's when faith is tested and proven. Tests reveal whether you trust God's character or just appreciate His blessings. Will you worship in the storm? Will you obey when it costs you? Will you trust when you can't see? Pass the test, and you emerge stronger, more mature, more like Jesus. The trial you're in right now is developing perseverance you'll need for what's next. Don't waste your pain. Let it refine you. Today, ask God: 'What are you teaching me through this?' Trust that He's working even when you can't see it.",
  },
  {
    id: "89",
    date: "2025-04-23",
    title: "The Blessing of Contentment",
    scripture: "Philippians 4:11-12",
    verse: "I have learned to be content whatever the circumstances. I know what it is to be in need, and I know what it is to have plenty. I have learned the secret of being content in any and every situation.",
    reflection: "Contentment isn't about having everything you want; it's about wanting what you have. Paul learned contentment through plenty and poverty. How? By finding satisfaction in Christ, not circumstances. Discontentment says 'I'll be happy when...' Contentment says 'I'm grateful now.' It's not settling for less or lacking ambition. It's peace in the present while pursuing the future. It's trusting God's provision and timing. Contentment defeats comparison, kills covetousness, and cultivates gratitude. When you're content, advertising can't manipulate you, keeping-up-with-the-Joneses loses appeal, and peace replaces panic. Today, practice contentment. Look around. What do you have right now that you once prayed for? A job, home, family, health, breath. Say thank you. Choose gratitude. Find contentment not in getting more, but in appreciating what you have.",
  },
  {
    id: "90",
    date: "2025-04-24",
    title: "Living on Mission",
    scripture: "Matthew 28:19-20",
    verse: "Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, and teaching them to obey everything I have commanded you.",
    reflection: "You have a mission: make disciples. It's not optional; it's Jesus' command to every believer. Making disciples doesn't mean you have to be a pastor or missionary. It means wherever you are - workplace, neighborhood, gym, school - point people to Jesus. Live in a way that makes them curious about your faith. Share your story. Invite them to church. Be ready to explain your hope. Disciple those who respond. The Great Commission isn't for 'super Christians'; it's for all Christians. Your mission field is right where you are. Who has God placed in your path? Who needs Jesus? Today, ask God to open your eyes to people around you who need Him. Pray for boldness to share. Then take one small step - a conversation, an invitation, a testimony shared. Live on mission.",
  },
];

export function getTodayDevotional(viewedIds: string[] = []): Devotional {
  const today = new Date();
  const dayOfYear = Math.floor((today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 86400000);
  
  const unviewed = devotionals.filter(d => !viewedIds.includes(d.id));
  
  if (unviewed.length > 0) {
    return unviewed[dayOfYear % unviewed.length];
  }
  
  return devotionals[dayOfYear % devotionals.length];
}

export function getPersonalizedDevotional(viewedIds: string[], preferences: string[] = []): Devotional {
  const unviewed = devotionals.filter(d => !viewedIds.includes(d.id));
  
  if (unviewed.length === 0) {
    return devotionals[Math.floor(Math.random() * devotionals.length)];
  }
  
  if (preferences.length > 0) {
    const preferredDevotionals = unviewed.filter(d => 
      preferences.some(pref => 
        d.title.toLowerCase().includes(pref.toLowerCase()) ||
        d.reflection.toLowerCase().includes(pref.toLowerCase())
      )
    );
    
    if (preferredDevotionals.length > 0) {
      return preferredDevotionals[Math.floor(Math.random() * preferredDevotionals.length)];
    }
  }
  
  return unviewed[Math.floor(Math.random() * unviewed.length)];
}

// Get theme keywords from devotional to match with prayer and study
export function getCorrelatedDevotionalTheme(devotional: Devotional): string[] {
  const keywords: string[] = [];
  const text = `${devotional.title} ${devotional.reflection}`.toLowerCase();
  
  // Common spiritual themes with more specific matching to avoid false positives
  const themeMap: Record<string, string[]> = {
    'finances': ['money', 'wealth', 'financial', 'steward', 'provision', 'tithe', 'giving', 'rich', 'poor', 'contentment'],
    'peace': ['peace', 'anxiety', 'worry', 'calm', 'rest', 'tranquil'],
    'strength': ['strength', 'courage', 'power', 'strong', 'mighty', 'endure'],
    'faith': ['faith', 'trust', 'believe', 'hope'],
    'guidance': ['guidance', 'wisdom', 'direction', 'path', 'choose', 'decision'],
    'forgiveness': ['forgive', 'mercy', 'grace', 'pardon', 'redemption'],
    'gratitude': ['thank', 'grateful', 'praise', 'blessing', 'appreciate'],
    'love': ['love others', 'compassion', 'kindness', 'serve others', 'care for others'],
    'health': ['health', 'body', 'physical', 'wellness', 'healing'],
    'parenting': ['parent', 'children', 'child', 'family'],
    'career': ['work', 'career', 'job', 'profession', 'business'],
    'purpose': ['purpose', 'calling', 'mission', 'identity'],
  };
  
  // Check finances first as it's very specific
  for (const [theme, searchTerms] of Object.entries(themeMap)) {
    if (searchTerms.some(term => text.includes(term))) {
      keywords.push(theme);
    }
  }
  
  return keywords.length > 0 ? keywords : ['peace']; // Default to peace if no match
}
