// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-album-art-helper.js
// 
// This file maps devotion titles to their album art images.
// Album art is automatically extracted from MP3 files using scripts/extract-album-art.sh

/**
 * Converts devotion title to kebab-case filename
 */
export function getAudioFileForDevotion(devotionTitle: string): string {
  const fileName = devotionTitle
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
  
  return fileName;
}

/**
 * Gets album art for a devotion by title.
 * Returns the image source or null if no album art exists.
 */
export function getAlbumArtForDevotion(devotionTitle: string): any | null {
  const fileName = getAudioFileForDevotion(devotionTitle);
  
  try {
    switch (fileName) {
      // Day 1: Finding Peace in the Storm
      case 'finding-peace-in-the-storm':
        return require('@/assets/audio/finding-peace-in-the-storm.jpg');
      
      // Day 2: Strength for Today
      case 'strength-for-today':
        return require('@/assets/audio/strength-for-today.jpg');
      
      // Day 3: Love in Action
      case 'love-in-action':
        return require('@/assets/audio/love-in-action.jpg');
      
      // Day 4: The Heart of Stewardship
      case 'the-heart-of-stewardship':
        return require('@/assets/audio/the-heart-of-stewardship.jpg');
      
      // Day 5: First Fruits, Not Leftovers
      case 'first-fruits-not-leftovers':
        return require('@/assets/audio/first-fruits-not-leftovers.jpg');
      
      // Day 6: Contentment is Wealth
      case 'contentment-is-wealth':
        return require('@/assets/audio/contentment-is-wealth.jpg');
      
      // Day 7: Generosity Opens Heaven's Windows
      case 'generosity-opens-heavens-windows':
        return require('@/assets/audio/generosity-opens-heavens-windows.jpg');
      
      // Day 8: Your Business Is Your Ministry
      case 'your-business-is-your-ministry':
        return require('@/assets/audio/your-business-is-your-ministry.jpg');
      
      // Day 9: Integrity Over Profit
      case 'integrity-over-profit':
        return require('@/assets/audio/integrity-over-profit.jpg');
      
      // Day 10: Faithful With Little, Trusted With Much
      case 'faithful-with-little-trusted-with-much':
        return require('@/assets/audio/faithful-with-little-trusted-with-much.jpg');
      
      // Day 11: God-Sized Vision
      case 'god-sized-vision':
        return require('@/assets/audio/god-sized-vision.jpg');
      
      // Day 12: Servant Leadership
      case 'servant-leadership':
        return require('@/assets/audio/servant-leadership.jpg');
      
      // Day 13: Excellence as Worship
      case 'excellence-as-worship':
        return require('@/assets/audio/excellence-as-worship.jpg');
      
      // Day 14: Building Wealth God's Way
      case 'building-wealth-gods-way':
        return require('@/assets/audio/building-wealth-gods-way.jpg');
      
      // Day 15: Your Body, God's Temple
      case 'your-body-gods-temple':
        return require('@/assets/audio/your-body-gods-temple.jpg');
      
      // Day 16: Parenting as Discipleship
      case 'parenting-as-discipleship':
        return require('@/assets/audio/parenting-as-discipleship.jpg');
      
      // Day 17: The Patient Investor
      case 'the-patient-investor':
        return require('@/assets/audio/the-patient-investor.jpg');
      
      // Day 18: The Debt-Free Dream
      case 'the-debt-free-dream':
        return require('@/assets/audio/the-debt-free-dream.jpg');
      
      // Day 19: Your Career, God's Calling
      case 'your-career-gods-calling':
        return require('@/assets/audio/your-career-gods-calling.jpg');
      
      // Day 20: The Freedom of a Budget
      case 'the-freedom-of-a-budget':
        return require('@/assets/audio/the-freedom-of-a-budget.jpg');
      
      // Day 21: Words That Heal
      case 'words-that-heal':
        return require('@/assets/audio/words-that-heal.jpg');
      
      // Day 22: Increasing Your Income, God's Way
      case 'increasing-your-income-gods-way':
        return require('@/assets/audio/increasing-your-income-gods-way.jpg');
      
      // Day 23: True Financial Freedom
      case 'true-financial-freedom':
        return require('@/assets/audio/true-financial-freedom.jpg');
      
      // Day 24: Move Your Body, Honor Your God
      case 'move-your-body-honor-your-god':
        return require('@/assets/audio/move-your-body-honor-your-god.jpg');
      
      // Day 25: The Power of Spoken Blessings
      case 'the-power-of-spoken-blessings':
        return require('@/assets/audio/the-power-of-spoken-blessings.jpg');
      
      // Day 26: Rest is Resistance
      case 'rest-is-resistance':
        return require('@/assets/audio/rest-is-resistance.jpg');
      
      // Day 27: Friendship as Spiritual Warfare
      case 'friendship-as-spiritual-warfare':
        return require('@/assets/audio/friendship-as-spiritual-warfare.jpg');
      
      // Day 28: When God Seems Silent
      case 'when-god-seems-silent':
        return require('@/assets/audio/when-god-seems-silent.jpg');
      
      // Day 29: Generational Influence
      case 'generational-influence':
        return require('@/assets/audio/generational-influence.jpg');
      
      // Day 30: The Ministry of Presence
      case 'the-ministry-of-presence':
        return require('@/assets/audio/the-ministry-of-presence.jpg');
      
      // Day 31: Wisdom for Every Decision
      case 'wisdom-for-every-decision':
        return require('@/assets/audio/wisdom-for-every-decision.jpg');
      
      // Day 32: The Gift of Today
      case 'the-gift-of-today':
        return require('@/assets/audio/the-gift-of-today.jpg');
      
      // Day 33: Breaking the Comparison Trap
      case 'breaking-the-comparison-trap':
        return require('@/assets/audio/breaking-the-comparison-trap.jpg');
      
      // Day 125: The Gift of Today
      case 'the-gift-of-today':
        return require('@/assets/audio/the-gift-of-today.jpg');
      
      // Day 132: The Ministry of Presence
      case 'the-ministry-of-presence':
        return require('@/assets/audio/the-ministry-of-presence.jpg');
      
      default:
        console.log(`ℹ️  No album art found for: ${fileName}.jpg`);
        return null;
    }
  } catch (error) {
    console.log(`⚠️  Could not load album art: ${fileName}.jpg`, error);
    return null;
  }
}
