/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-audio-helper.js
 * 
 * This file maps devotion titles to their corresponding audio files.
 * Audio files should be placed in /assets/audio/ with kebab-case names.
 * 
 * To update this file:
 * 1. Update constants/devotionals.ts if needed
 * 2. Run: node scripts/generate-audio-helper.js
 * 3. Add your MP3 files to /assets/audio/
 * 4. Rebuild the app
 */

import { getAudioFileForDevotion, hasAudioForDevotion } from './audioAvailability';

export { getAudioFileForDevotion, hasAudioForDevotion } from './audioAvailability';

/**
 * Dynamically loads audio file for a devotion.
 * Returns null if file doesn't exist or isn't registered.
 * 
 * USAGE:
 * 1. Add your MP3 file to /assets/audio/ with the exact kebab-case name
 * 2. The file will automatically load based on devotion title
 * 3. No manual registration needed!
 */
export function getDynamicAudioSource(devotionTitle: string): any | null {
  const fileName = getAudioFileForDevotion(devotionTitle);

  if (!hasAudioForDevotion(devotionTitle)) {
    return null;
  }
  
  try {
    // Auto-generated mappings for bundled audio files only
    switch (fileName) {
      // Day 1: Finding Peace in the Storm
      case 'finding-peace-in-the-storm':
        return require('@/assets/audio/finding-peace-in-the-storm.mp3');
      
      // Day 2: Strength for Today
      case 'strength-for-today':
        return require('@/assets/audio/strength-for-today.mp3');
      
      // Day 3: Love in Action
      case 'love-in-action':
        return require('@/assets/audio/love-in-action.mp3');
      
      // Day 4: The Heart of Stewardship
      case 'the-heart-of-stewardship':
        return require('@/assets/audio/the-heart-of-stewardship.mp3');
      
      // Day 5: First Fruits, Not Leftovers
      case 'first-fruits-not-leftovers':
        return require('@/assets/audio/first-fruits-not-leftovers.mp3');
      
      // Day 6: Contentment is Wealth
      case 'contentment-is-wealth':
        return require('@/assets/audio/contentment-is-wealth.mp3');
      
      // Day 7: Generosity Opens Heaven's Windows
      case 'generosity-opens-heavens-windows':
        return require('@/assets/audio/generosity-opens-heavens-windows.mp3');
      
      // Day 8: Your Business Is Your Ministry
      case 'your-business-is-your-ministry':
        return require('@/assets/audio/your-business-is-your-ministry.mp3');
      
      // Day 9: Integrity Over Profit
      case 'integrity-over-profit':
        return require('@/assets/audio/integrity-over-profit.mp3');
      
      // Day 10: Faithful With Little, Trusted With Much
      case 'faithful-with-little-trusted-with-much':
        return require('@/assets/audio/faithful-with-little-trusted-with-much.mp3');
      
      // Day 11: God-Sized Vision
      case 'god-sized-vision':
        return require('@/assets/audio/god-sized-vision.mp3');
      
      // Day 12: Servant Leadership
      case 'servant-leadership':
        return require('@/assets/audio/servant-leadership.mp3');
      
      // Day 13: Excellence as Worship
      case 'excellence-as-worship':
        return require('@/assets/audio/excellence-as-worship.mp3');
      
      // Day 14: Building Wealth God's Way
      case 'building-wealth-gods-way':
        return require('@/assets/audio/building-wealth-gods-way.mp3');
      
      // Day 15: Your Body, God's Temple
      case 'your-body-gods-temple':
        return require('@/assets/audio/your-body-gods-temple.mp3');
      
      // Day 16: Parenting as Discipleship
      case 'parenting-as-discipleship':
        return require('@/assets/audio/parenting-as-discipleship.mp3');
      
      // Day 17: The Patient Investor
      case 'the-patient-investor':
        return require('@/assets/audio/the-patient-investor.mp3');
      
      // Day 18: The Debt-Free Dream
      case 'the-debt-free-dream':
        return require('@/assets/audio/the-debt-free-dream.mp3');
      
      // Day 19: Your Career, God's Calling
      case 'your-career-gods-calling':
        return require('@/assets/audio/your-career-gods-calling.mp3');
      
      // Day 20: The Freedom of a Budget
      case 'the-freedom-of-a-budget':
        return require('@/assets/audio/the-freedom-of-a-budget.mp3');
      
      // Day 21: Words That Heal
      case 'words-that-heal':
        return require('@/assets/audio/words-that-heal.mp3');
      
      // Day 22: Increasing Your Income, God's Way
      case 'increasing-your-income-gods-way':
        return require('@/assets/audio/increasing-your-income-gods-way.mp3');
      
      // Day 23: True Financial Freedom
      case 'true-financial-freedom':
        return require('@/assets/audio/true-financial-freedom.mp3');
      
      // Day 24: Move Your Body, Honor Your God
      case 'move-your-body-honor-your-god':
        return require('@/assets/audio/move-your-body-honor-your-god.mp3');
      
      // Day 25: The Power of Spoken Blessings
      case 'the-power-of-spoken-blessings':
        return require('@/assets/audio/the-power-of-spoken-blessings.mp3');
      
      // Day 26: Rest is Resistance
      case 'rest-is-resistance':
        return require('@/assets/audio/rest-is-resistance.mp3');
      
      // Day 27: Friendship as Spiritual Warfare
      case 'friendship-as-spiritual-warfare':
        return require('@/assets/audio/friendship-as-spiritual-warfare.mp3');
      
      // Day 28: When God Seems Silent
      case 'when-god-seems-silent':
        return require('@/assets/audio/when-god-seems-silent.mp3');
      
      // Day 29: Generational Influence
      case 'generational-influence':
        return require('@/assets/audio/generational-influence.mp3');
      
      // Day 30: The Ministry of Presence
      case 'the-ministry-of-presence':
        return require('@/assets/audio/the-ministry-of-presence.mp3');
      
      // Day 31: Wisdom for Every Decision
      case 'wisdom-for-every-decision':
        return require('@/assets/audio/wisdom-for-every-decision.mp3');
      
      // Day 32: The Gift of Today
      case 'the-gift-of-today':
        return require('@/assets/audio/the-gift-of-today.mp3');
      
      // Day 33: Breaking the Comparison Trap
      case 'breaking-the-comparison-trap':
        return require('@/assets/audio/breaking-the-comparison-trap.mp3');
      
      // Day 34: Guard Your Heart
      case 'guard-your-heart':
        return require('@/assets/audio/guard-your-heart.mp3');
      
      // Day 35: The Power of Gratitude
      case 'the-power-of-gratitude':
        return require('@/assets/audio/the-power-of-gratitude.mp3');
      
      // Day 36: When You Feel Inadequate
      case 'when-you-feel-inadequate':
        return require('@/assets/audio/when-you-feel-inadequate.mp3');
      
      // Day 37: The Cost of Unforgiveness
      case 'the-cost-of-unforgiveness':
        return require('@/assets/audio/the-cost-of-unforgiveness.mp3');
      
      // Day 38: Your Words Create Worlds
      case 'your-words-create-worlds':
        return require('@/assets/audio/your-words-create-worlds.mp3');
      
      // Day 39: The Battle for Your Mind
      case 'the-battle-for-your-mind':
        return require('@/assets/audio/the-battle-for-your-mind.mp3');
      
      // Day 40: Patience in the Process
      case 'patience-in-the-process':
        return require('@/assets/audio/patience-in-the-process.mp3');
      
      // Day 41: You Are Not Alone
      case 'you-are-not-alone':
        return require('@/assets/audio/you-are-not-alone.mp3');
      
      // Day 42: Trusting God's Timing
      case 'trusting-gods-timing':
        return require('@/assets/audio/trusting-gods-timing.mp3');
      
      // Day 43: The Sin You're Tolerating
      case 'the-sin-youre-tolerating':
        return require('@/assets/audio/the-sin-youre-tolerating.mp3');
      
      // Day 44: When Prayer Feels Pointless
      case 'when-prayer-feels-pointless':
        return require('@/assets/audio/when-prayer-feels-pointless.mp3');
      
      // Day 45: Your Identity in Christ
      case 'your-identity-in-christ':
        return require('@/assets/audio/your-identity-in-christ.mp3');
      
      // Day 46: Investing in Eternity
      case 'investing-in-eternity':
        return require('@/assets/audio/investing-in-eternity.mp3');
      
      // Day 47: The Gift of Difficult People
      case 'the-gift-of-difficult-people':
        return require('@/assets/audio/the-gift-of-difficult-people.mp3');
      
      // Day 48: Overcoming Fear with Faith
      case 'overcoming-fear-with-faith':
        return require('@/assets/audio/overcoming-fear-with-faith.mp3');
      
      // Day 49: The Discipline of Margin
      case 'the-discipline-of-margin':
        return require('@/assets/audio/the-discipline-of-margin.mp3');
      
      // Day 51: The Sacrifice of Praise
      case 'the-sacrifice-of-praise':
        return require('@/assets/audio/the-sacrifice-of-praise.mp3');
      
      // Day 52: Breaking Generational Curses
      case 'breaking-generational-curses':
        return require('@/assets/audio/breaking-generational-curses.mp3');
      
      // Day 54: Your Scars Tell a Story
      case 'your-scars-tell-a-story':
        return require('@/assets/audio/your-scars-tell-a-story.mp3');
      
      // Day 55: When God Closes Doors
      case 'when-god-closes-doors':
        return require('@/assets/audio/when-god-closes-doors.mp3');
      
      // Day 56: Stewarding Your Mental Health
      case 'stewarding-your-mental-health':
        return require('@/assets/audio/stewarding-your-mental-health.mp3');
      
      // Day 57: Fighting for Your Marriage
      case 'fighting-for-your-marriage':
        return require('@/assets/audio/fighting-for-your-marriage.mp3');
      
      // Day 58: Your Calling Is Costly
      case 'your-calling-is-costly':
        return require('@/assets/audio/your-calling-is-costly.mp3');
      
      // Day 59: Raising Kingdom Kids
      case 'raising-kingdom-kids':
        return require('@/assets/audio/raising-kingdom-kids.mp3');
      
      // Day 61: Walking in Humility
      case 'walking-in-humility':
        return require('@/assets/audio/walking-in-humility.mp3');
      
      // Day 62: Finding Your Community
      case 'finding-your-community':
        return require('@/assets/audio/finding-your-community.mp3');
      
      // Day 63: The Blessing of Boundaries
      case 'the-blessing-of-boundaries':
        return require('@/assets/audio/the-blessing-of-boundaries.mp3');
      
      // Day 65: Celebrating Small Wins
      case 'celebrating-small-wins':
        return require('@/assets/audio/celebrating-small-wins.mp3');
      
      // Day 66: Living with Intentionality
      case 'living-with-intentionality':
        return require('@/assets/audio/living-with-intentionality.mp3');
      
      // Day 67: The Gift of Mentorship
      case 'the-gift-of-mentorship':
        return require('@/assets/audio/the-gift-of-mentorship.mp3');
      
      // Day 68: Breaking Free from Addiction
      case 'breaking-free-from-addiction':
        return require('@/assets/audio/breaking-free-from-addiction.mp3');
      
      // Day 69: Your Unique Gifting
      case 'your-unique-gifting':
        return require('@/assets/audio/your-unique-gifting.mp3');
      
      // Day 70: Hope for the Prodigal
      case 'hope-for-the-prodigal':
        return require('@/assets/audio/hope-for-the-prodigal.mp3');
      
      // Day 71: The Power of Fasting
      case 'the-power-of-fasting':
        return require('@/assets/audio/the-power-of-fasting.mp3');
      
      // Day 72: Transforming Your Thought Life
      case 'transforming-your-thought-life':
        return require('@/assets/audio/transforming-your-thought-life.mp3');
      
      // Day 73: When God Redirects Your Plans
      case 'when-god-redirects-your-plans':
        return require('@/assets/audio/when-god-redirects-your-plans.mp3');
      
      // Day 74: Honoring Your Parents
      case 'honoring-your-parents':
        return require('@/assets/audio/honoring-your-parents.mp3');
      
      // Day 75: Stewarding Your Resources Wisely
      case 'stewarding-your-resources-wisely':
        return require('@/assets/audio/stewarding-your-resources-wisely.mp3');
      
      // Day 76: The Gift of Singleness
      case 'the-gift-of-singleness':
        return require('@/assets/audio/the-gift-of-singleness.mp3');
      
      // Day 77: Bearing Good Fruit
      case 'bearing-good-fruit':
        return require('@/assets/audio/bearing-good-fruit.mp3');
      
      // Day 78: Trusting God With Your Kids
      case 'trusting-god-with-your-kids':
        return require('@/assets/audio/trusting-god-with-your-kids.mp3');
      
      // Day 79: Overcoming Past Trauma
      case 'overcoming-past-trauma':
        return require('@/assets/audio/overcoming-past-trauma.mp3');
      
      // Day 80: Living Generously
      case 'living-generously':
        return require('@/assets/audio/living-generously.mp3');
      
      // Day 81: Your God-Given Purpose
      case 'your-god-given-purpose':
        return require('@/assets/audio/your-god-given-purpose.mp3');
      
      // Day 82: The Ministry of Listening
      case 'the-ministry-of-listening':
        return require('@/assets/audio/the-ministry-of-listening.mp3');
      
      // Day 83: Breaking Free from Comparison
      case 'breaking-free-from-comparison':
        return require('@/assets/audio/breaking-free-from-comparison.mp3');
      
      // Day 84: The Importance of Confession
      case 'the-importance-of-confession':
        return require('@/assets/audio/the-importance-of-confession.mp3');
      
      // Day 85: Fighting Spiritual Warfare
      case 'fighting-spiritual-warfare':
        return require('@/assets/audio/fighting-spiritual-warfare.mp3');
      
      // Day 86: Redeeming Your Time
      case 'redeeming-your-time':
        return require('@/assets/audio/redeeming-your-time.mp3');
      
      // Day 87: The Power of Corporate Worship
      case 'the-power-of-corporate-worship':
        return require('@/assets/audio/the-power-of-corporate-worship.mp3');
      
      // Day 88: When Your Faith Is Tested
      case 'when-your-faith-is-tested':
        return require('@/assets/audio/when-your-faith-is-tested.mp3');
      
      // Day 89: The Blessing of Contentment
      case 'the-blessing-of-contentment':
        return require('@/assets/audio/the-blessing-of-contentment.mp3');
      
      // Day 90: Living on Mission
      case 'living-on-mission':
        return require('@/assets/audio/living-on-mission.mp3');
      
      // Day 91: The Power of Consistency
      case 'the-power-of-consistency':
        return require('@/assets/audio/the-power-of-consistency.mp3');
      
      // Day 92: Extending Grace
      case 'extending-grace':
        return require('@/assets/audio/extending-grace.mp3');
      
      // Day 93: The Danger of Pride
      case 'the-danger-of-pride':
        return require('@/assets/audio/the-danger-of-pride.mp3');
      
      // Day 94: God's Unconditional Love
      case 'gods-unconditional-love':
        return require('@/assets/audio/gods-unconditional-love.mp3');
      
      // Day 95: Practicing Patience
      case 'practicing-patience':
        return require('@/assets/audio/practicing-patience.mp3');
      
      // Day 96: Authenticity Over Perfection
      case 'authenticity-over-perfection':
        return require('@/assets/audio/authenticity-over-perfection.mp3');
      
      // Day 97: Hope in Dark Times
      case 'hope-in-dark-times':
        return require('@/assets/audio/hope-in-dark-times.mp3');
      
      // Day 98: Trusting God's Process
      case 'trusting-gods-process':
        return require('@/assets/audio/trusting-gods-process.mp3');
      
      // Day 100: Embracing Change
      case 'embracing-change':
        return require('@/assets/audio/embracing-change.mp3');
      
      // Day 101: The Blessing of Obedience
      case 'the-blessing-of-obedience':
        return require('@/assets/audio/the-blessing-of-obedience.mp3');
      
      // Day 102: Letting God Fight
      case 'letting-god-fight':
        return require('@/assets/audio/letting-god-fight.mp3');
      
      // Day 103: Faithful in Obscurity
      case 'faithful-in-obscurity':
        return require('@/assets/audio/faithful-in-obscurity.mp3');
      
      // Day 104: The Ministry of Encouragement
      case 'the-ministry-of-encouragement':
        return require('@/assets/audio/the-ministry-of-encouragement.mp3');
      
      // Day 105: Guarding Your Eyes
      case 'guarding-your-eyes':
        return require('@/assets/audio/guarding-your-eyes.mp3');
      
      // Day 106: Supernatural Peace
      case 'supernatural-peace':
        return require('@/assets/audio/supernatural-peace.mp3');
      
      // Day 107: Honoring Authority
      case 'honoring-authority':
        return require('@/assets/audio/honoring-authority.mp3');
      
      // Day 108: Redefining Success
      case 'redefining-success':
        return require('@/assets/audio/redefining-success.mp3');
      
      // Day 109: Loving the Unlovable
      case 'loving-the-unlovable':
        return require('@/assets/audio/loving-the-unlovable.mp3');
      
      // Day 110: The Practice of Solitude
      case 'the-practice-of-solitude':
        return require('@/assets/audio/the-practice-of-solitude.mp3');
      
      // Day 111: Stewarding Your Influence
      case 'stewarding-your-influence':
        return require('@/assets/audio/stewarding-your-influence.mp3');
      
      // Day 112: The Cost of Compromise
      case 'the-cost-of-compromise':
        return require('@/assets/audio/the-cost-of-compromise.mp3');
      
      // Day 114: Trusting in God's Provision
      case 'trusting-in-gods-provision':
        return require('@/assets/audio/trusting-in-gods-provision.mp3');
      
      // Day 115: The Discipline of Celebration
      case 'the-discipline-of-celebration':
        return require('@/assets/audio/the-discipline-of-celebration.mp3');
      
      // Day 116: Sowing and Reaping
      case 'sowing-and-reaping':
        return require('@/assets/audio/sowing-and-reaping.mp3');
      
      // Day 117: God's Perfect Timing
      case 'gods-perfect-timing':
        return require('@/assets/audio/gods-perfect-timing.mp3');
      
      // Day 118: Spiritual Warfare Reality
      case 'spiritual-warfare-reality':
        return require('@/assets/audio/spiritual-warfare-reality.mp3');
      
      // Day 119: The Fruit of the Spirit
      case 'the-fruit-of-the-spirit':
        return require('@/assets/audio/the-fruit-of-the-spirit.mp3');
      
      // Day 121: Surrendering Control
      case 'surrendering-control':
        return require('@/assets/audio/surrendering-control.mp3');
      
      // Day 125: The Gift of Today
      case 'the-gift-of-today':
        return require('@/assets/audio/the-gift-of-today.mp3');
      
      // Day 132: The Ministry of Presence
      case 'the-ministry-of-presence':
        return require('@/assets/audio/the-ministry-of-presence.mp3');
      
      // Day 203: Practicing Patience
      case 'practicing-patience':
        return require('@/assets/audio/practicing-patience.mp3');
      
      // Day 205: Living Generously
      case 'living-generously':
        return require('@/assets/audio/living-generously.mp3');
      
      // Day 229: Walking in Humility
      case 'walking-in-humility':
        return require('@/assets/audio/walking-in-humility.mp3');
      
      // Day 271: The Power of Gratitude
      case 'the-power-of-gratitude':
        return require('@/assets/audio/the-power-of-gratitude.mp3');
      
      // Day 347: Living Generously
      case 'living-generously':
        return require('@/assets/audio/living-generously.mp3');
      
      // Day 354: Trusting God's Timing
      case 'trusting-gods-timing':
        return require('@/assets/audio/trusting-gods-timing.mp3');
      
      default:
        return null;
    }
  } catch (error) {
    console.warn(`⚠️  Could not load audio file: ${fileName}.mp3`, error);
    return null;
  }
}

/**
 * Get audio source by day of year (1-365)
 */
export function getAudioSourceByDayOfYear(dayOfYear: number): any | null {
  // Import devotionals to get the title for the day
  const { devotionals } = require('@/constants/devotionals');
  const index = (dayOfYear - 1) % 365;
  const devotion = devotionals[index];
  
  if (!devotion) return null;
  
  return getDynamicAudioSource(devotion.title);
}
