/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-audio-helper.js
 * 
 * This file maps devotion titles to their corresponding audio files.
 * Audio files should be placed in /assets/audio/ with kebab-case names.
 * 
 * To update this file:
 * 1. Update constants/devotionals.ts if needed
 * 2. Run: node scripts/generate-audio-helper.js
 * 3. Add your MP3 files to /assets/audio/
 * 4. Rebuild the app
 */

export function getAudioFileForDevotion(devotionTitle: string): string {
  // Convert title to kebab-case for file name
  const fileName = devotionTitle
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '') // Remove special characters
    .replace(/\s+/g, '-') // Replace spaces with hyphens
    .replace(/-+/g, '-') // Replace multiple hyphens with single hyphen
    .trim();
  
  return fileName;
}

/**
 * Dynamically loads audio file for a devotion.
 * Returns null if file doesn't exist or isn't registered.
 * 
 * USAGE:
 * 1. Add your MP3 file to /assets/audio/ with the exact kebab-case name
 * 2. The file will automatically load based on devotion title
 * 3. No manual registration needed!
 */
export function getDynamicAudioSource(devotionTitle: string): any | null {
  const fileName = getAudioFileForDevotion(devotionTitle);
  
  try {
    // Auto-generated mappings for all 365 devotions
    switch (fileName) {
      // Day 1: Finding Peace in the Storm
      case 'finding-peace-in-the-storm':
        return require('@/assets/audio/finding-peace-in-the-storm.mp3');
      
      // Day 2: Strength for Today
      case 'strength-for-today':
        return require('@/assets/audio/strength-for-today.mp3');
      
      // Day 3: Love in Action
      case 'love-in-action':
        return require('@/assets/audio/love-in-action.mp3');
      
      // Day 4: The Heart of Stewardship
      case 'the-heart-of-stewardship':
        return require('@/assets/audio/the-heart-of-stewardship.mp3');
      
      // Day 5: First Fruits, Not Leftovers
      case 'first-fruits-not-leftovers':
        return require('@/assets/audio/first-fruits-not-leftovers.mp3');
      
      // Day 6: Contentment is Wealth
      case 'contentment-is-wealth':
        return require('@/assets/audio/contentment-is-wealth.mp3');
      
      // Day 7: Generosity Opens Heaven's Windows
      case 'generosity-opens-heavens-windows':
        return require('@/assets/audio/generosity-opens-heavens-windows.mp3');
      
      // Day 8: Your Business Is Your Ministry
      case 'your-business-is-your-ministry':
        return require('@/assets/audio/your-business-is-your-ministry.mp3');
      
      // Day 9: Integrity Over Profit
      case 'integrity-over-profit':
        return require('@/assets/audio/integrity-over-profit.mp3');
      
      // Day 10: Faithful With Little, Trusted With Much
      case 'faithful-with-little-trusted-with-much':
        return require('@/assets/audio/faithful-with-little-trusted-with-much.mp3');
      
      // Day 11: God-Sized Vision
      case 'god-sized-vision':
        return require('@/assets/audio/god-sized-vision.mp3');
      
      // Day 12: Servant Leadership
      case 'servant-leadership':
        return require('@/assets/audio/servant-leadership.mp3');
      
      // Day 13: Excellence as Worship
      case 'excellence-as-worship':
        return require('@/assets/audio/excellence-as-worship.mp3');
      
      // Day 14: Building Wealth God's Way
      case 'building-wealth-gods-way':
        return require('@/assets/audio/building-wealth-gods-way.mp3');
      
      // Day 15: Your Body, God's Temple
      case 'your-body-gods-temple':
        return require('@/assets/audio/your-body-gods-temple.mp3');
      
      // Day 16: Parenting as Discipleship
      case 'parenting-as-discipleship':
        return require('@/assets/audio/parenting-as-discipleship.mp3');
      
      // Day 17: The Patient Investor
      case 'the-patient-investor':
        return require('@/assets/audio/the-patient-investor.mp3');
      
      // Day 18: The Debt-Free Dream
      case 'the-debt-free-dream':
        return require('@/assets/audio/the-debt-free-dream.mp3');
      
      // Day 19: Your Career, God's Calling
      case 'your-career-gods-calling':
        return require('@/assets/audio/your-career-gods-calling.mp3');
      
      // Day 20: The Freedom of a Budget
      case 'the-freedom-of-a-budget':
        return require('@/assets/audio/the-freedom-of-a-budget.mp3');
      
      // Day 21: Words That Heal
      case 'words-that-heal':
        return require('@/assets/audio/words-that-heal.mp3');
      
      // Day 22: Increasing Your Income, God's Way
      case 'increasing-your-income-gods-way':
        return require('@/assets/audio/increasing-your-income-gods-way.mp3');
      
      // Day 23: True Financial Freedom
      case 'true-financial-freedom':
        return require('@/assets/audio/true-financial-freedom.mp3');
      
      // Day 24: Move Your Body, Honor Your God
      case 'move-your-body-honor-your-god':
        return require('@/assets/audio/move-your-body-honor-your-god.mp3');
      
      // Day 25: The Power of Spoken Blessings
      case 'the-power-of-spoken-blessings':
        return require('@/assets/audio/the-power-of-spoken-blessings.mp3');
      
      // Day 26: Rest is Resistance
      case 'rest-is-resistance':
        return require('@/assets/audio/rest-is-resistance.mp3');
      
      // Day 27: Friendship as Spiritual Warfare
      case 'friendship-as-spiritual-warfare':
        return require('@/assets/audio/friendship-as-spiritual-warfare.mp3');
      
      // Day 28: When God Seems Silent
      case 'when-god-seems-silent':
        return require('@/assets/audio/when-god-seems-silent.mp3');
      
      // Day 29: Generational Influence
      case 'generational-influence':
        return require('@/assets/audio/generational-influence.mp3');
      
      // Day 30: The Ministry of Presence
      case 'the-ministry-of-presence':
        return require('@/assets/audio/the-ministry-of-presence.mp3');
      
      // Day 31: Wisdom for Every Decision
      case 'wisdom-for-every-decision':
        return require('@/assets/audio/wisdom-for-every-decision.mp3');
      
      // Day 32: The Gift of Today
      case 'the-gift-of-today':
        return require('@/assets/audio/the-gift-of-today.mp3');
      
      // Day 33: Breaking the Comparison Trap
      case 'breaking-the-comparison-trap':
        return require('@/assets/audio/breaking-the-comparison-trap.mp3');
      
      // Day 34: Guard Your Heart
      case 'guard-your-heart':
        return require('@/assets/audio/guard-your-heart.mp3');
      
      // Day 35: The Power of Gratitude
      case 'the-power-of-gratitude':
        return require('@/assets/audio/the-power-of-gratitude.mp3');
      
      // Day 36: When You Feel Inadequate
      case 'when-you-feel-inadequate':
        return require('@/assets/audio/when-you-feel-inadequate.mp3');
      
      // Day 37: The Cost of Unforgiveness
      case 'the-cost-of-unforgiveness':
        return require('@/assets/audio/the-cost-of-unforgiveness.mp3');
      
      // Day 38: Your Words Create Worlds
      case 'your-words-create-worlds':
        return require('@/assets/audio/your-words-create-worlds.mp3');
      
      // Day 39: The Battle for Your Mind
      case 'the-battle-for-your-mind':
        return require('@/assets/audio/the-battle-for-your-mind.mp3');
      
      // Day 40: Patience in the Process
      case 'patience-in-the-process':
        return require('@/assets/audio/patience-in-the-process.mp3');
      
      // Day 41: You Are Not Alone
      case 'you-are-not-alone':
        return require('@/assets/audio/you-are-not-alone.mp3');
      
      // Day 42: Trusting God's Timing
      case 'trusting-gods-timing':
        return require('@/assets/audio/trusting-gods-timing.mp3');
      
      // Day 43: The Sin You're Tolerating
      case 'the-sin-youre-tolerating':
        return require('@/assets/audio/the-sin-youre-tolerating.mp3');
      
      // Day 44: When Prayer Feels Pointless
      case 'when-prayer-feels-pointless':
        return require('@/assets/audio/when-prayer-feels-pointless.mp3');
      
      // Day 45: Your Identity in Christ
      case 'your-identity-in-christ':
        return require('@/assets/audio/your-identity-in-christ.mp3');
      
      // Day 46: Investing in Eternity
      case 'investing-in-eternity':
        return require('@/assets/audio/investing-in-eternity.mp3');
      
      // Day 47: The Gift of Difficult People
      case 'the-gift-of-difficult-people':
        return require('@/assets/audio/the-gift-of-difficult-people.mp3');
      
      // Day 48: Overcoming Fear with Faith
      case 'overcoming-fear-with-faith':
        return require('@/assets/audio/overcoming-fear-with-faith.mp3');
      
      // Day 49: The Discipline of Margin
      case 'the-discipline-of-margin':
        return require('@/assets/audio/the-discipline-of-margin.mp3');
      
      // Day 50: When You Feel Like Quitting
      case 'when-you-feel-like-quitting':
        return require('@/assets/audio/when-you-feel-like-quitting.mp3');
      
      // Day 51: The Sacrifice of Praise
      case 'the-sacrifice-of-praise':
        return require('@/assets/audio/the-sacrifice-of-praise.mp3');
      
      // Day 52: Breaking Generational Curses
      case 'breaking-generational-curses':
        return require('@/assets/audio/breaking-generational-curses.mp3');
      
      // Day 53: The Power of Consistent Obedience
      case 'the-power-of-consistent-obedience':
        return require('@/assets/audio/the-power-of-consistent-obedience.mp3');
      
      // Day 54: Your Scars Tell a Story
      case 'your-scars-tell-a-story':
        return require('@/assets/audio/your-scars-tell-a-story.mp3');
      
      // Day 55: When God Closes Doors
      case 'when-god-closes-doors':
        return require('@/assets/audio/when-god-closes-doors.mp3');
      
      // Day 56: Stewarding Your Mental Health
      case 'stewarding-your-mental-health':
        return require('@/assets/audio/stewarding-your-mental-health.mp3');
      
      // Day 57: Fighting for Your Marriage
      case 'fighting-for-your-marriage':
        return require('@/assets/audio/fighting-for-your-marriage.mp3');
      
      // Day 58: Your Calling Is Costly
      case 'your-calling-is-costly':
        return require('@/assets/audio/your-calling-is-costly.mp3');
      
      // Day 59: Raising Kingdom Kids
      case 'raising-kingdom-kids':
        return require('@/assets/audio/raising-kingdom-kids.mp3');
      
      // Day 60: The Courage to Start Again
      case 'the-courage-to-start-again':
        return require('@/assets/audio/the-courage-to-start-again.mp3');
      
      // Day 61: Walking in Humility
      case 'walking-in-humility':
        return require('@/assets/audio/walking-in-humility.mp3');
      
      // Day 62: Finding Your Community
      case 'finding-your-community':
        return require('@/assets/audio/finding-your-community.mp3');
      
      // Day 63: The Blessing of Boundaries
      case 'the-blessing-of-boundaries':
        return require('@/assets/audio/the-blessing-of-boundaries.mp3');
      
      // Day 64: Your Work Matters to God
      case 'your-work-matters-to-god':
        return require('@/assets/audio/your-work-matters-to-god.mp3');
      
      // Day 65: Celebrating Small Wins
      case 'celebrating-small-wins':
        return require('@/assets/audio/celebrating-small-wins.mp3');
      
      // Day 66: Living with Intentionality
      case 'living-with-intentionality':
        return require('@/assets/audio/living-with-intentionality.mp3');
      
      // Day 67: The Gift of Mentorship
      case 'the-gift-of-mentorship':
        return require('@/assets/audio/the-gift-of-mentorship.mp3');
      
      // Day 68: Breaking Free from Addiction
      case 'breaking-free-from-addiction':
        return require('@/assets/audio/breaking-free-from-addiction.mp3');
      
      // Day 69: Your Unique Gifting
      case 'your-unique-gifting':
        return require('@/assets/audio/your-unique-gifting.mp3');
      
      // Day 70: Hope for the Prodigal
      case 'hope-for-the-prodigal':
        return require('@/assets/audio/hope-for-the-prodigal.mp3');
      
      // Day 71: The Power of Fasting
      case 'the-power-of-fasting':
        return require('@/assets/audio/the-power-of-fasting.mp3');
      
      // Day 72: Transforming Your Thought Life
      case 'transforming-your-thought-life':
        return require('@/assets/audio/transforming-your-thought-life.mp3');
      
      // Day 73: When God Redirects Your Plans
      case 'when-god-redirects-your-plans':
        return require('@/assets/audio/when-god-redirects-your-plans.mp3');
      
      // Day 74: Honoring Your Parents
      case 'honoring-your-parents':
        return require('@/assets/audio/honoring-your-parents.mp3');
      
      // Day 75: Stewarding Your Resources Wisely
      case 'stewarding-your-resources-wisely':
        return require('@/assets/audio/stewarding-your-resources-wisely.mp3');
      
      // Day 76: The Gift of Singleness
      case 'the-gift-of-singleness':
        return require('@/assets/audio/the-gift-of-singleness.mp3');
      
      // Day 77: Bearing Good Fruit
      case 'bearing-good-fruit':
        return require('@/assets/audio/bearing-good-fruit.mp3');
      
      // Day 78: Trusting God With Your Kids
      case 'trusting-god-with-your-kids':
        return require('@/assets/audio/trusting-god-with-your-kids.mp3');
      
      // Day 79: Overcoming Past Trauma
      case 'overcoming-past-trauma':
        return require('@/assets/audio/overcoming-past-trauma.mp3');
      
      // Day 80: Living Generously
      case 'living-generously':
        return require('@/assets/audio/living-generously.mp3');
      
      // Day 81: Your God-Given Purpose
      case 'your-god-given-purpose':
        return require('@/assets/audio/your-god-given-purpose.mp3');
      
      // Day 82: The Ministry of Listening
      case 'the-ministry-of-listening':
        return require('@/assets/audio/the-ministry-of-listening.mp3');
      
      // Day 83: Breaking Free from Comparison
      case 'breaking-free-from-comparison':
        return require('@/assets/audio/breaking-free-from-comparison.mp3');
      
      // Day 84: The Importance of Confession
      case 'the-importance-of-confession':
        return require('@/assets/audio/the-importance-of-confession.mp3');
      
      // Day 85: Fighting Spiritual Warfare
      case 'fighting-spiritual-warfare':
        return require('@/assets/audio/fighting-spiritual-warfare.mp3');
      
      // Day 86: Redeeming Your Time
      case 'redeeming-your-time':
        return require('@/assets/audio/redeeming-your-time.mp3');
      
      // Day 87: The Power of Corporate Worship
      case 'the-power-of-corporate-worship':
        return require('@/assets/audio/the-power-of-corporate-worship.mp3');
      
      // Day 88: When Your Faith Is Tested
      case 'when-your-faith-is-tested':
        return require('@/assets/audio/when-your-faith-is-tested.mp3');
      
      // Day 89: The Blessing of Contentment
      case 'the-blessing-of-contentment':
        return require('@/assets/audio/the-blessing-of-contentment.mp3');
      
      // Day 90: Living on Mission
      case 'living-on-mission':
        return require('@/assets/audio/living-on-mission.mp3');
      
      // Day 91: The Power of Consistency
      case 'the-power-of-consistency':
        return require('@/assets/audio/the-power-of-consistency.mp3');
      
      // Day 92: Extending Grace
      case 'extending-grace':
        return require('@/assets/audio/extending-grace.mp3');
      
      // Day 93: The Danger of Pride
      case 'the-danger-of-pride':
        return require('@/assets/audio/the-danger-of-pride.mp3');
      
      // Day 94: God's Unconditional Love
      case 'gods-unconditional-love':
        return require('@/assets/audio/gods-unconditional-love.mp3');
      
      // Day 95: Practicing Patience
      case 'practicing-patience':
        return require('@/assets/audio/practicing-patience.mp3');
      
      // Day 96: Authenticity Over Perfection
      case 'authenticity-over-perfection':
        return require('@/assets/audio/authenticity-over-perfection.mp3');
      
      // Day 97: Hope in Dark Times
      case 'hope-in-dark-times':
        return require('@/assets/audio/hope-in-dark-times.mp3');
      
      // Day 98: Trusting God's Process
      case 'trusting-gods-process':
        return require('@/assets/audio/trusting-gods-process.mp3');
      
      // Day 99: Speaking Truth in Love
      case 'speaking-truth-in-love':
        return require('@/assets/audio/speaking-truth-in-love.mp3');
      
      // Day 100: Embracing Change
      case 'embracing-change':
        return require('@/assets/audio/embracing-change.mp3');
      
      // Day 101: The Blessing of Obedience
      case 'the-blessing-of-obedience':
        return require('@/assets/audio/the-blessing-of-obedience.mp3');
      
      // Day 102: Letting God Fight
      case 'letting-god-fight':
        return require('@/assets/audio/letting-god-fight.mp3');
      
      // Day 103: Faithful in Obscurity
      case 'faithful-in-obscurity':
        return require('@/assets/audio/faithful-in-obscurity.mp3');
      
      // Day 104: The Ministry of Encouragement
      case 'the-ministry-of-encouragement':
        return require('@/assets/audio/the-ministry-of-encouragement.mp3');
      
      // Day 105: Guarding Your Eyes
      case 'guarding-your-eyes':
        return require('@/assets/audio/guarding-your-eyes.mp3');
      
      // Day 106: Supernatural Peace
      case 'supernatural-peace':
        return require('@/assets/audio/supernatural-peace.mp3');
      
      // Day 107: Honoring Authority
      case 'honoring-authority':
        return require('@/assets/audio/honoring-authority.mp3');
      
      // Day 108: Redefining Success
      case 'redefining-success':
        return require('@/assets/audio/redefining-success.mp3');
      
      // Day 109: Loving the Unlovable
      case 'loving-the-unlovable':
        return require('@/assets/audio/loving-the-unlovable.mp3');
      
      // Day 110: The Practice of Solitude
      case 'the-practice-of-solitude':
        return require('@/assets/audio/the-practice-of-solitude.mp3');
      
      // Day 111: Stewarding Your Influence
      case 'stewarding-your-influence':
        return require('@/assets/audio/stewarding-your-influence.mp3');
      
      // Day 112: The Cost of Compromise
      case 'the-cost-of-compromise':
        return require('@/assets/audio/the-cost-of-compromise.mp3');
      
      // Day 113: Receiving Correction
      case 'receiving-correction':
        return require('@/assets/audio/receiving-correction.mp3');
      
      // Day 114: Trusting in God's Provision
      case 'trusting-in-gods-provision':
        return require('@/assets/audio/trusting-in-gods-provision.mp3');
      
      // Day 115: The Discipline of Celebration
      case 'the-discipline-of-celebration':
        return require('@/assets/audio/the-discipline-of-celebration.mp3');
      
      // Day 116: Sowing and Reaping
      case 'sowing-and-reaping':
        return require('@/assets/audio/sowing-and-reaping.mp3');
      
      // Day 117: God's Perfect Timing
      case 'gods-perfect-timing':
        return require('@/assets/audio/gods-perfect-timing.mp3');
      
      // Day 118: Spiritual Warfare Reality
      case 'spiritual-warfare-reality':
        return require('@/assets/audio/spiritual-warfare-reality.mp3');
      
      // Day 119: The Fruit of the Spirit
      case 'the-fruit-of-the-spirit':
        return require('@/assets/audio/the-fruit-of-the-spirit.mp3');
      
      // Day 120: Honoring Your Spouse
      case 'honoring-your-spouse':
        return require('@/assets/audio/honoring-your-spouse.mp3');
      
      // Day 121: Surrendering Control
      case 'surrendering-control':
        return require('@/assets/audio/surrendering-control.mp3');
      
      // Day 122: The Power of Testimony
      case 'the-power-of-testimony':
        return require('@/assets/audio/the-power-of-testimony.mp3');
      
      // Day 123: Resisting Temptation
      case 'resisting-temptation':
        return require('@/assets/audio/resisting-temptation.mp3');
      
      // Day 124: Living with Integrity
      case 'living-with-integrity':
        return require('@/assets/audio/living-with-integrity.mp3');
      
      // Day 125: The Gift of Today
      case 'the-gift-of-today':
        return require('@/assets/audio/the-gift-of-today.mp3');
      
      // Day 126: Choosing Joy
      case 'choosing-joy':
        return require('@/assets/audio/choosing-joy.mp3');
      
      // Day 127: Kingdom Generosity
      case 'kingdom-generosity':
        return require('@/assets/audio/kingdom-generosity.mp3');
      
      // Day 128: Trusting God's Character
      case 'trusting-gods-character':
        return require('@/assets/audio/trusting-gods-character.mp3');
      
      // Day 129: Overcoming Discouragement
      case 'overcoming-discouragement':
        return require('@/assets/audio/overcoming-discouragement.mp3');
      
      // Day 130: The Sabbath Principle
      case 'the-sabbath-principle':
        return require('@/assets/audio/the-sabbath-principle.mp3');
      
      // Day 131: Faith Over Fear
      case 'faith-over-fear':
        return require('@/assets/audio/faith-over-fear.mp3');
      
      // Day 132: The Ministry of Presence
      case 'the-ministry-of-presence':
        return require('@/assets/audio/the-ministry-of-presence.mp3');
      
      // Day 133: Walking by Faith
      case 'walking-by-faith':
        return require('@/assets/audio/walking-by-faith.mp3');
      
      // Day 134: Guarding Your Heart
      case 'guarding-your-heart':
        return require('@/assets/audio/guarding-your-heart.mp3');
      
      // Day 135: Serving Others
      case 'serving-others':
        return require('@/assets/audio/serving-others.mp3');
      
      // Day 136: The Power of Agreement
      case 'the-power-of-agreement':
        return require('@/assets/audio/the-power-of-agreement.mp3');
      
      // Day 137: Resisting Gossip
      case 'resisting-gossip':
        return require('@/assets/audio/resisting-gossip.mp3');
      
      // Day 138: Pursuing Peace
      case 'pursuing-peace':
        return require('@/assets/audio/pursuing-peace.mp3');
      
      // Day 139: Your Eternal Home
      case 'your-eternal-home':
        return require('@/assets/audio/your-eternal-home.mp3');
      
      // Day 140: Contentment in All Circumstances
      case 'contentment-in-all-circumstances':
        return require('@/assets/audio/contentment-in-all-circumstances.mp3');
      
      // Day 141: Forgiveness Brings Freedom
      case 'forgiveness-brings-freedom':
        return require('@/assets/audio/forgiveness-brings-freedom.mp3');
      
      // Day 142: God's Faithfulness
      case 'gods-faithfulness':
        return require('@/assets/audio/gods-faithfulness.mp3');
      
      // Day 143: Building on the Rock
      case 'building-on-the-rock':
        return require('@/assets/audio/building-on-the-rock.mp3');
      
      // Day 144: The Power of Unity
      case 'the-power-of-unity':
        return require('@/assets/audio/the-power-of-unity.mp3');
      
      // Day 145: Eternal Perspective
      case 'eternal-perspective':
        return require('@/assets/audio/eternal-perspective.mp3');
      
      // Day 146: Loving Like Jesus
      case 'loving-like-jesus':
        return require('@/assets/audio/loving-like-jesus.mp3');
      
      // Day 147: Overcoming Temptation
      case 'overcoming-temptation':
        return require('@/assets/audio/overcoming-temptation.mp3');
      
      // Day 148: The Power of Thanksgiving
      case 'the-power-of-thanksgiving':
        return require('@/assets/audio/the-power-of-thanksgiving.mp3');
      
      // Day 149: Living Sacrificially
      case 'living-sacrificially':
        return require('@/assets/audio/living-sacrificially.mp3');
      
      // Day 150: Hope Anchors the Soul
      case 'hope-anchors-the-soul':
        return require('@/assets/audio/hope-anchors-the-soul.mp3');
      
      // Day 151: The Blessing of Trials
      case 'the-blessing-of-trials':
        return require('@/assets/audio/the-blessing-of-trials.mp3');
      
      // Day 152: Walking in the Light
      case 'walking-in-the-light':
        return require('@/assets/audio/walking-in-the-light.mp3');
      
      // Day 153: God's Timing Is Perfect
      case 'gods-timing-is-perfect':
        return require('@/assets/audio/gods-timing-is-perfect.mp3');
      
      // Day 154: Pursuing Holiness
      case 'pursuing-holiness':
        return require('@/assets/audio/pursuing-holiness.mp3');
      
      // Day 155: The Power of Weakness
      case 'the-power-of-weakness':
        return require('@/assets/audio/the-power-of-weakness.mp3');
      
      // Day 156: Redeeming Your Past
      case 'redeeming-your-past':
        return require('@/assets/audio/redeeming-your-past.mp3');
      
      // Day 157: The Cost of Following Jesus
      case 'the-cost-of-following-jesus':
        return require('@/assets/audio/the-cost-of-following-jesus.mp3');
      
      // Day 158: Strength in Community
      case 'strength-in-community':
        return require('@/assets/audio/strength-in-community.mp3');
      
      // Day 159: Running Your Race
      case 'running-your-race':
        return require('@/assets/audio/running-your-race.mp3');
      
      // Day 160: Loving God With All
      case 'loving-god-with-all':
        return require('@/assets/audio/loving-god-with-all.mp3');
      
      // Day 161: True Freedom
      case 'true-freedom':
        return require('@/assets/audio/true-freedom.mp3');
      
      // Day 162: God's Unshakable Kingdom
      case 'gods-unshakable-kingdom':
        return require('@/assets/audio/gods-unshakable-kingdom.mp3');
      
      // Day 163: Dealing With Anxiety
      case 'dealing-with-anxiety':
        return require('@/assets/audio/dealing-with-anxiety.mp3');
      
      // Day 164: The Practice of Confession
      case 'the-practice-of-confession':
        return require('@/assets/audio/the-practice-of-confession.mp3');
      
      // Day 165: Living as Light
      case 'living-as-light':
        return require('@/assets/audio/living-as-light.mp3');
      
      // Day 166: Wrestling in Prayer
      case 'wrestling-in-prayer':
        return require('@/assets/audio/wrestling-in-prayer.mp3');
      
      // Day 167: The Danger of Compromise
      case 'the-danger-of-compromise':
        return require('@/assets/audio/the-danger-of-compromise.mp3');
      
      // Day 168: Trusting God's Faithfulness
      case 'trusting-gods-faithfulness':
        return require('@/assets/audio/trusting-gods-faithfulness.mp3');
      
      // Day 169: Putting Off the Old Self
      case 'putting-off-the-old-self':
        return require('@/assets/audio/putting-off-the-old-self.mp3');
      
      // Day 170: The Power of Agreement
      case 'the-power-of-agreement':
        return require('@/assets/audio/the-power-of-agreement.mp3');
      
      // Day 171: Responding to Injustice
      case 'responding-to-injustice':
        return require('@/assets/audio/responding-to-injustice.mp3');
      
      // Day 172: Loving Your Neighbor
      case 'loving-your-neighbor':
        return require('@/assets/audio/loving-your-neighbor.mp3');
      
      // Day 173: The Discipline of Waiting
      case 'the-discipline-of-waiting':
        return require('@/assets/audio/the-discipline-of-waiting.mp3');
      
      // Day 174: The Gift of Encouragement
      case 'the-gift-of-encouragement':
        return require('@/assets/audio/the-gift-of-encouragement.mp3');
      
      // Day 175: Crucifying the Flesh
      case 'crucifying-the-flesh':
        return require('@/assets/audio/crucifying-the-flesh.mp3');
      
      // Day 176: God Sees Everything
      case 'god-sees-everything':
        return require('@/assets/audio/god-sees-everything.mp3');
      
      // Day 177: Rejoicing in Suffering
      case 'rejoicing-in-suffering':
        return require('@/assets/audio/rejoicing-in-suffering.mp3');
      
      // Day 178: The Path of Wisdom
      case 'the-path-of-wisdom':
        return require('@/assets/audio/the-path-of-wisdom.mp3');
      
      // Day 179: Unceasing Prayer
      case 'unceasing-prayer':
        return require('@/assets/audio/unceasing-prayer.mp3');
      
      // Day 180: The Narrow Gate
      case 'the-narrow-gate':
        return require('@/assets/audio/the-narrow-gate.mp3');
      
      // Day 181: Abiding in Christ
      case 'abiding-in-christ':
        return require('@/assets/audio/abiding-in-christ.mp3');
      
      // Day 182: Speaking Life
      case 'speaking-life':
        return require('@/assets/audio/speaking-life.mp3');
      
      // Day 183: God's Omnipresence
      case 'gods-omnipresence':
        return require('@/assets/audio/gods-omnipresence.mp3');
      
      // Day 184: The Gift of Salvation
      case 'the-gift-of-salvation':
        return require('@/assets/audio/the-gift-of-salvation.mp3');
      
      // Day 185: Testing Everything
      case 'testing-everything':
        return require('@/assets/audio/testing-everything.mp3');
      
      // Day 186: Being Salt and Light
      case 'being-salt-and-light':
        return require('@/assets/audio/being-salt-and-light.mp3');
      
      // Day 187: Growing Through Trials
      case 'growing-through-trials':
        return require('@/assets/audio/growing-through-trials.mp3');
      
      // Day 188: The Ministry of Reconciliation
      case 'the-ministry-of-reconciliation':
        return require('@/assets/audio/the-ministry-of-reconciliation.mp3');
      
      // Day 189: Fixing Your Eyes on Jesus
      case 'fixing-your-eyes-on-jesus':
        return require('@/assets/audio/fixing-your-eyes-on-jesus.mp3');
      
      // Day 190: Living With Purpose
      case 'living-with-purpose':
        return require('@/assets/audio/living-with-purpose.mp3');
      
      // Day 191: The Power of Testimony
      case 'the-power-of-testimony':
        return require('@/assets/audio/the-power-of-testimony.mp3');
      
      // Day 192: Resisting the Devil
      case 'resisting-the-devil':
        return require('@/assets/audio/resisting-the-devil.mp3');
      
      // Day 193: Overflowing Gratitude
      case 'overflowing-gratitude':
        return require('@/assets/audio/overflowing-gratitude.mp3');
      
      // Day 194: Loving Sacrificially
      case 'loving-sacrificially':
        return require('@/assets/audio/loving-sacrificially.mp3');
      
      // Day 195: God's Sovereignty
      case 'gods-sovereignty':
        return require('@/assets/audio/gods-sovereignty.mp3');
      
      // Day 196: Running to God, Not From Him
      case 'running-to-god-not-from-him':
        return require('@/assets/audio/running-to-god-not-from-him.mp3');
      
      // Day 197: Casting Your Cares
      case 'casting-your-cares':
        return require('@/assets/audio/casting-your-cares.mp3');
      
      // Day 198: Living Authentically
      case 'living-authentically':
        return require('@/assets/audio/living-authentically.mp3');
      
      // Day 199: Pursuing Peace
      case 'pursuing-peace':
        return require('@/assets/audio/pursuing-peace.mp3');
      
      // Day 200: God Works All Things Together
      case 'god-works-all-things-together':
        return require('@/assets/audio/god-works-all-things-together.mp3');
      
      // Day 201: Walking in Obedience
      case 'walking-in-obedience':
        return require('@/assets/audio/walking-in-obedience.mp3');
      
      // Day 202: The Beauty of Worship
      case 'the-beauty-of-worship':
        return require('@/assets/audio/the-beauty-of-worship.mp3');
      
      // Day 203: Practicing Patience
      case 'practicing-patience':
        return require('@/assets/audio/practicing-patience.mp3');
      
      // Day 204: Finishing Strong
      case 'finishing-strong':
        return require('@/assets/audio/finishing-strong.mp3');
      
      // Day 205: Living Generously
      case 'living-generously':
        return require('@/assets/audio/living-generously.mp3');
      
      // Day 206: God's Immeasurable Love
      case 'gods-immeasurable-love':
        return require('@/assets/audio/gods-immeasurable-love.mp3');
      
      // Day 207: The Power of Unity
      case 'the-power-of-unity':
        return require('@/assets/audio/the-power-of-unity.mp3');
      
      // Day 208: Eternal Rewards
      case 'eternal-rewards':
        return require('@/assets/audio/eternal-rewards.mp3');
      
      // Day 209: Living in the Light
      case 'living-in-the-light':
        return require('@/assets/audio/living-in-the-light.mp3');
      
      // Day 210: Hope for Tomorrow
      case 'hope-for-tomorrow':
        return require('@/assets/audio/hope-for-tomorrow.mp3');
      
      // Day 211: Living Stones
      case 'living-stones':
        return require('@/assets/audio/living-stones.mp3');
      
      // Day 212: The Power of Weakness
      case 'the-power-of-weakness':
        return require('@/assets/audio/the-power-of-weakness.mp3');
      
      // Day 213: Justified by Faith
      case 'justified-by-faith':
        return require('@/assets/audio/justified-by-faith.mp3');
      
      // Day 214: Casting All Anxiety
      case 'casting-all-anxiety':
        return require('@/assets/audio/casting-all-anxiety.mp3');
      
      // Day 215: The Mind of Christ
      case 'the-mind-of-christ':
        return require('@/assets/audio/the-mind-of-christ.mp3');
      
      // Day 216: Abiding in the Vine
      case 'abiding-in-the-vine':
        return require('@/assets/audio/abiding-in-the-vine.mp3');
      
      // Day 217: The Promise of Restoration
      case 'the-promise-of-restoration':
        return require('@/assets/audio/the-promise-of-restoration.mp3');
      
      // Day 218: Living Sacrificially
      case 'living-sacrificially':
        return require('@/assets/audio/living-sacrificially.mp3');
      
      // Day 219: The Joy of Obedience
      case 'the-joy-of-obedience':
        return require('@/assets/audio/the-joy-of-obedience.mp3');
      
      // Day 220: God's Unfailing Love
      case 'gods-unfailing-love':
        return require('@/assets/audio/gods-unfailing-love.mp3');
      
      // Day 221: The Fellowship of Suffering
      case 'the-fellowship-of-suffering':
        return require('@/assets/audio/the-fellowship-of-suffering.mp3');
      
      // Day 222: The Call to Boldness
      case 'the-call-to-boldness':
        return require('@/assets/audio/the-call-to-boldness.mp3');
      
      // Day 223: Created for Good Works
      case 'created-for-good-works':
        return require('@/assets/audio/created-for-good-works.mp3');
      
      // Day 224: Perfect Peace
      case 'perfect-peace':
        return require('@/assets/audio/perfect-peace.mp3');
      
      // Day 225: One Thing Needed
      case 'one-thing-needed':
        return require('@/assets/audio/one-thing-needed.mp3');
      
      // Day 226: Rivers of Living Water
      case 'rivers-of-living-water':
        return require('@/assets/audio/rivers-of-living-water.mp3');
      
      // Day 227: The Armor of Light
      case 'the-armor-of-light':
        return require('@/assets/audio/the-armor-of-light.mp3');
      
      // Day 228: The God Who Sees
      case 'the-god-who-sees':
        return require('@/assets/audio/the-god-who-sees.mp3');
      
      // Day 229: Walking in Humility
      case 'walking-in-humility':
        return require('@/assets/audio/walking-in-humility.mp3');
      
      // Day 230: Access to the Father
      case 'access-to-the-father':
        return require('@/assets/audio/access-to-the-father.mp3');
      
      // Day 231: The Truth Sets Free
      case 'the-truth-sets-free':
        return require('@/assets/audio/the-truth-sets-free.mp3');
      
      // Day 232: Wrestling in Prayer
      case 'wrestling-in-prayer':
        return require('@/assets/audio/wrestling-in-prayer.mp3');
      
      // Day 233: God's Thoughts Toward You
      case 'gods-thoughts-toward-you':
        return require('@/assets/audio/gods-thoughts-toward-you.mp3');
      
      // Day 234: Enduring Hardship
      case 'enduring-hardship':
        return require('@/assets/audio/enduring-hardship.mp3');
      
      // Day 235: The Reward of Diligence
      case 'the-reward-of-diligence':
        return require('@/assets/audio/the-reward-of-diligence.mp3');
      
      // Day 236: Waiting on the Lord
      case 'waiting-on-the-lord':
        return require('@/assets/audio/waiting-on-the-lord.mp3');
      
      // Day 237: The Gift of Repentance
      case 'the-gift-of-repentance':
        return require('@/assets/audio/the-gift-of-repentance.mp3');
      
      // Day 238: The Refining Fire
      case 'the-refining-fire':
        return require('@/assets/audio/the-refining-fire.mp3');
      
      // Day 239: Standing Firm
      case 'standing-firm':
        return require('@/assets/audio/standing-firm.mp3');
      
      // Day 240: The Listening Ear
      case 'the-listening-ear':
        return require('@/assets/audio/the-listening-ear.mp3');
      
      // Day 241: Kingdom Priorities
      case 'kingdom-priorities':
        return require('@/assets/audio/kingdom-priorities.mp3');
      
      // Day 242: The Helper Has Come
      case 'the-helper-has-come':
        return require('@/assets/audio/the-helper-has-come.mp3');
      
      // Day 243: The Power of Unity
      case 'the-power-of-unity':
        return require('@/assets/audio/the-power-of-unity.mp3');
      
      // Day 244: Tested Faith
      case 'tested-faith':
        return require('@/assets/audio/tested-faith.mp3');
      
      // Day 245: Living Letters
      case 'living-letters':
        return require('@/assets/audio/living-letters.mp3');
      
      // Day 246: The Great Exchange
      case 'the-great-exchange':
        return require('@/assets/audio/the-great-exchange.mp3');
      
      // Day 247: Loving Your Enemies
      case 'loving-your-enemies':
        return require('@/assets/audio/loving-your-enemies.mp3');
      
      // Day 248: The Blessing of Giving
      case 'the-blessing-of-giving':
        return require('@/assets/audio/the-blessing-of-giving.mp3');
      
      // Day 249: The Rock of Salvation
      case 'the-rock-of-salvation':
        return require('@/assets/audio/the-rock-of-salvation.mp3');
      
      // Day 250: New Mercies Daily
      case 'new-mercies-daily':
        return require('@/assets/audio/new-mercies-daily.mp3');
      
      // Day 251: The Narrow Gate
      case 'the-narrow-gate':
        return require('@/assets/audio/the-narrow-gate.mp3');
      
      // Day 252: Treasure in Jars of Clay
      case 'treasure-in-jars-of-clay':
        return require('@/assets/audio/treasure-in-jars-of-clay.mp3');
      
      // Day 253: Praying Without Ceasing
      case 'praying-without-ceasing':
        return require('@/assets/audio/praying-without-ceasing.mp3');
      
      // Day 254: The Burden Bearer
      case 'the-burden-bearer':
        return require('@/assets/audio/the-burden-bearer.mp3');
      
      // Day 255: Ambassadors for Christ
      case 'ambassadors-for-christ':
        return require('@/assets/audio/ambassadors-for-christ.mp3');
      
      // Day 256: Faithful in Little
      case 'faithful-in-little':
        return require('@/assets/audio/faithful-in-little.mp3');
      
      // Day 257: The Battle is the Lord's
      case 'the-battle-is-the-lords':
        return require('@/assets/audio/the-battle-is-the-lords.mp3');
      
      // Day 258: Words of Life
      case 'words-of-life':
        return require('@/assets/audio/words-of-life.mp3');
      
      // Day 259: Running the Race
      case 'running-the-race':
        return require('@/assets/audio/running-the-race.mp3');
      
      // Day 260: God's Sovereignty
      case 'gods-sovereignty':
        return require('@/assets/audio/gods-sovereignty.mp3');
      
      // Day 261: The Vine and Branches
      case 'the-vine-and-branches':
        return require('@/assets/audio/the-vine-and-branches.mp3');
      
      // Day 262: The Goodness of God
      case 'the-goodness-of-god':
        return require('@/assets/audio/the-goodness-of-god.mp3');
      
      // Day 263: Salt and Light
      case 'salt-and-light':
        return require('@/assets/audio/salt-and-light.mp3');
      
      // Day 264: God's Unchanging Nature
      case 'gods-unchanging-nature':
        return require('@/assets/audio/gods-unchanging-nature.mp3');
      
      // Day 265: The Power of Agreement
      case 'the-power-of-agreement':
        return require('@/assets/audio/the-power-of-agreement.mp3');
      
      // Day 266: The Resurrection Life
      case 'the-resurrection-life':
        return require('@/assets/audio/the-resurrection-life.mp3');
      
      // Day 267: Interceding for Others
      case 'interceding-for-others':
        return require('@/assets/audio/interceding-for-others.mp3');
      
      // Day 268: The Cost of Following
      case 'the-cost-of-following':
        return require('@/assets/audio/the-cost-of-following.mp3');
      
      // Day 269: The Father's Love
      case 'the-fathers-love':
        return require('@/assets/audio/the-fathers-love.mp3');
      
      // Day 270: Eternal Reward
      case 'eternal-reward':
        return require('@/assets/audio/eternal-reward.mp3');
      
      // Day 271: The Power of Gratitude
      case 'the-power-of-gratitude':
        return require('@/assets/audio/the-power-of-gratitude.mp3');
      
      // Day 272: Walking by Faith
      case 'walking-by-faith':
        return require('@/assets/audio/walking-by-faith.mp3');
      
      // Day 273: The God of All Comfort
      case 'the-god-of-all-comfort':
        return require('@/assets/audio/the-god-of-all-comfort.mp3');
      
      // Day 274: New Creation
      case 'new-creation':
        return require('@/assets/audio/new-creation.mp3');
      
      // Day 275: God's Discipline
      case 'gods-discipline':
        return require('@/assets/audio/gods-discipline.mp3');
      
      // Day 276: Blessed to Be a Blessing
      case 'blessed-to-be-a-blessing':
        return require('@/assets/audio/blessed-to-be-a-blessing.mp3');
      
      // Day 277: The Final Victory
      case 'the-final-victory':
        return require('@/assets/audio/the-final-victory.mp3');
      
      // Day 278: Transformed Thinking
      case 'transformed-thinking':
        return require('@/assets/audio/transformed-thinking.mp3');
      
      // Day 279: Led by the Spirit
      case 'led-by-the-spirit':
        return require('@/assets/audio/led-by-the-spirit.mp3');
      
      // Day 280: The Authority of Believers
      case 'the-authority-of-believers':
        return require('@/assets/audio/the-authority-of-believers.mp3');
      
      // Day 281: Loving Others First
      case 'loving-others-first':
        return require('@/assets/audio/loving-others-first.mp3');
      
      // Day 282: Count It All Joy
      case 'count-it-all-joy':
        return require('@/assets/audio/count-it-all-joy.mp3');
      
      // Day 283: The Fear of the Lord
      case 'the-fear-of-the-lord':
        return require('@/assets/audio/the-fear-of-the-lord.mp3');
      
      // Day 284: The Bread of Life
      case 'the-bread-of-life':
        return require('@/assets/audio/the-bread-of-life.mp3');
      
      // Day 285: The Believer's Armor
      case 'the-believers-armor':
        return require('@/assets/audio/the-believers-armor.mp3');
      
      // Day 286: Producing Fruit
      case 'producing-fruit':
        return require('@/assets/audio/producing-fruit.mp3');
      
      // Day 287: The Promise of His Return
      case 'the-promise-of-his-return':
        return require('@/assets/audio/the-promise-of-his-return.mp3');
      
      // Day 288: The Ultimate Sacrifice
      case 'the-ultimate-sacrifice':
        return require('@/assets/audio/the-ultimate-sacrifice.mp3');
      
      // Day 289: Walking in Truth
      case 'walking-in-truth':
        return require('@/assets/audio/walking-in-truth.mp3');
      
      // Day 290: The Power of Agreement
      case 'the-power-of-agreement':
        return require('@/assets/audio/the-power-of-agreement.mp3');
      
      // Day 291: Serving One Another
      case 'serving-one-another':
        return require('@/assets/audio/serving-one-another.mp3');
      
      // Day 292: The Good Fight
      case 'the-good-fight':
        return require('@/assets/audio/the-good-fight.mp3');
      
      // Day 293: The Joy of Salvation
      case 'the-joy-of-salvation':
        return require('@/assets/audio/the-joy-of-salvation.mp3');
      
      // Day 294: Chosen and Appointed
      case 'chosen-and-appointed':
        return require('@/assets/audio/chosen-and-appointed.mp3');
      
      // Day 295: The Narrow Path
      case 'the-narrow-path':
        return require('@/assets/audio/the-narrow-path.mp3');
      
      // Day 296: Strength in Weakness
      case 'strength-in-weakness':
        return require('@/assets/audio/strength-in-weakness.mp3');
      
      // Day 297: The Promise of Peace
      case 'the-promise-of-peace':
        return require('@/assets/audio/the-promise-of-peace.mp3');
      
      // Day 298: Overcoming by the Blood
      case 'overcoming-by-the-blood':
        return require('@/assets/audio/overcoming-by-the-blood.mp3');
      
      // Day 299: The High Calling
      case 'the-high-calling':
        return require('@/assets/audio/the-high-calling.mp3');
      
      // Day 300: Thirsting for God
      case 'thirsting-for-god':
        return require('@/assets/audio/thirsting-for-god.mp3');
      
      // Day 301: Grace Upon Grace
      case 'grace-upon-grace':
        return require('@/assets/audio/grace-upon-grace.mp3');
      
      // Day 302: Delight in the Lord
      case 'delight-in-the-lord':
        return require('@/assets/audio/delight-in-the-lord.mp3');
      
      // Day 303: Waiting with Hope
      case 'waiting-with-hope':
        return require('@/assets/audio/waiting-with-hope.mp3');
      
      // Day 304: Thankful Always
      case 'thankful-always':
        return require('@/assets/audio/thankful-always.mp3');
      
      // Day 305: The Light of Life
      case 'the-light-of-life':
        return require('@/assets/audio/the-light-of-life.mp3');
      
      // Day 306: Clothed in Righteousness
      case 'clothed-in-righteousness':
        return require('@/assets/audio/clothed-in-righteousness.mp3');
      
      // Day 307: Ask, Seek, Knock
      case 'ask-seek-knock':
        return require('@/assets/audio/ask-seek-knock.mp3');
      
      // Day 308: Living Sacrifices
      case 'living-sacrifices':
        return require('@/assets/audio/living-sacrifices.mp3');
      
      // Day 309: The Overcomer's Promise
      case 'the-overcomers-promise':
        return require('@/assets/audio/the-overcomers-promise.mp3');
      
      // Day 310: Seek First
      case 'seek-first':
        return require('@/assets/audio/seek-first.mp3');
      
      // Day 311: Hope as an Anchor
      case 'hope-as-an-anchor':
        return require('@/assets/audio/hope-as-an-anchor.mp3');
      
      // Day 312: Kingdom Citizens
      case 'kingdom-citizens':
        return require('@/assets/audio/kingdom-citizens.mp3');
      
      // Day 313: Sowing Generously
      case 'sowing-generously':
        return require('@/assets/audio/sowing-generously.mp3');
      
      // Day 314: The Name Above All Names
      case 'the-name-above-all-names':
        return require('@/assets/audio/the-name-above-all-names.mp3');
      
      // Day 315: Carried by Grace
      case 'carried-by-grace':
        return require('@/assets/audio/carried-by-grace.mp3');
      
      // Day 316: The Shepherd's Voice
      case 'the-shepherds-voice':
        return require('@/assets/audio/the-shepherds-voice.mp3');
      
      // Day 317: Patient Endurance
      case 'patient-endurance':
        return require('@/assets/audio/patient-endurance.mp3');
      
      // Day 318: The Way Maker
      case 'the-way-maker':
        return require('@/assets/audio/the-way-maker.mp3');
      
      // Day 319: Effective Prayer
      case 'effective-prayer':
        return require('@/assets/audio/effective-prayer.mp3');
      
      // Day 320: Living Water
      case 'living-water':
        return require('@/assets/audio/living-water.mp3');
      
      // Day 321: Perfect Love
      case 'perfect-love':
        return require('@/assets/audio/perfect-love.mp3');
      
      // Day 322: The Faithful Witness
      case 'the-faithful-witness':
        return require('@/assets/audio/the-faithful-witness.mp3');
      
      // Day 323: Test the Spirits
      case 'test-the-spirits':
        return require('@/assets/audio/test-the-spirits.mp3');
      
      // Day 324: The Coming King
      case 'the-coming-king':
        return require('@/assets/audio/the-coming-king.mp3');
      
      // Day 325: Stand Firm in Faith
      case 'stand-firm-in-faith':
        return require('@/assets/audio/stand-firm-in-faith.mp3');
      
      // Day 326: The Humble King
      case 'the-humble-king':
        return require('@/assets/audio/the-humble-king.mp3');
      
      // Day 327: Emmanuel - God With Us
      case 'emmanuel-god-with-us':
        return require('@/assets/audio/emmanuel-god-with-us.mp3');
      
      // Day 328: The Prince of Peace
      case 'the-prince-of-peace':
        return require('@/assets/audio/the-prince-of-peace.mp3');
      
      // Day 329: Glory to God
      case 'glory-to-god':
        return require('@/assets/audio/glory-to-god.mp3');
      
      // Day 330: The Savior is Born
      case 'the-savior-is-born':
        return require('@/assets/audio/the-savior-is-born.mp3');
      
      // Day 331: The Incarnation
      case 'the-incarnation':
        return require('@/assets/audio/the-incarnation.mp3');
      
      // Day 332: Born to Die
      case 'born-to-die':
        return require('@/assets/audio/born-to-die.mp3');
      
      // Day 333: The Gift of God
      case 'the-gift-of-god':
        return require('@/assets/audio/the-gift-of-god.mp3');
      
      // Day 334: Christmas Eve Reflection
      case 'christmas-eve-reflection':
        return require('@/assets/audio/christmas-eve-reflection.mp3');
      
      // Day 335: Christmas Day - The King Has Come
      case 'christmas-day-the-king-has-come':
        return require('@/assets/audio/christmas-day-the-king-has-come.mp3');
      
      // Day 336: After Christmas
      case 'after-christmas':
        return require('@/assets/audio/after-christmas.mp3');
      
      // Day 337: Living in Light of Eternity
      case 'living-in-light-of-eternity':
        return require('@/assets/audio/living-in-light-of-eternity.mp3');
      
      // Day 338: Finishing the Year Strong
      case 'finishing-the-year-strong':
        return require('@/assets/audio/finishing-the-year-strong.mp3');
      
      // Day 339: Reflecting on God's Faithfulness
      case 'reflecting-on-gods-faithfulness':
        return require('@/assets/audio/reflecting-on-gods-faithfulness.mp3');
      
      // Day 340: New Year Preparation
      case 'new-year-preparation':
        return require('@/assets/audio/new-year-preparation.mp3');
      
      // Day 341: New Year's Eve - Looking Forward
      case 'new-years-eve-looking-forward':
        return require('@/assets/audio/new-years-eve-looking-forward.mp3');
      
      // Day 342: New Year's Day - Fresh Start
      case 'new-years-day-fresh-start':
        return require('@/assets/audio/new-years-day-fresh-start.mp3');
      
      // Day 343: Beginning with God
      case 'beginning-with-god':
        return require('@/assets/audio/beginning-with-god.mp3');
      
      // Day 344: The Power of God's Word
      case 'the-power-of-gods-word':
        return require('@/assets/audio/the-power-of-gods-word.mp3');
      
      // Day 345: Prayer as Foundation
      case 'prayer-as-foundation':
        return require('@/assets/audio/prayer-as-foundation.mp3');
      
      // Day 346: Walking in Obedience
      case 'walking-in-obedience':
        return require('@/assets/audio/walking-in-obedience.mp3');
      
      // Day 347: Living Generously
      case 'living-generously':
        return require('@/assets/audio/living-generously.mp3');
      
      // Day 348: Guarding Your Heart
      case 'guarding-your-heart':
        return require('@/assets/audio/guarding-your-heart.mp3');
      
      // Day 349: Living with Purpose
      case 'living-with-purpose':
        return require('@/assets/audio/living-with-purpose.mp3');
      
      // Day 350: Enduring Trials
      case 'enduring-trials':
        return require('@/assets/audio/enduring-trials.mp3');
      
      // Day 351: Speaking Life
      case 'speaking-life':
        return require('@/assets/audio/speaking-life.mp3');
      
      // Day 352: Forgiving Others
      case 'forgiving-others':
        return require('@/assets/audio/forgiving-others.mp3');
      
      // Day 353: Seeking God First
      case 'seeking-god-first':
        return require('@/assets/audio/seeking-god-first.mp3');
      
      // Day 354: Trusting God's Timing
      case 'trusting-gods-timing':
        return require('@/assets/audio/trusting-gods-timing.mp3');
      
      // Day 355: Bearing Much Fruit
      case 'bearing-much-fruit':
        return require('@/assets/audio/bearing-much-fruit.mp3');
      
      // Day 356: Loving God Completely
      case 'loving-god-completely':
        return require('@/assets/audio/loving-god-completely.mp3');
      
      // Day 357: Living in Peace
      case 'living-in-peace':
        return require('@/assets/audio/living-in-peace.mp3');
      
      // Day 358: Walking Humbly
      case 'walking-humbly':
        return require('@/assets/audio/walking-humbly.mp3');
      
      // Day 359: Being Strong and Courageous
      case 'being-strong-and-courageous':
        return require('@/assets/audio/being-strong-and-courageous.mp3');
      
      // Day 360: Running with Endurance
      case 'running-with-endurance':
        return require('@/assets/audio/running-with-endurance.mp3');
      
      // Day 361: Fixing Eyes on Jesus
      case 'fixing-eyes-on-jesus':
        return require('@/assets/audio/fixing-eyes-on-jesus.mp3');
      
      // Day 362: Rejoicing Always
      case 'rejoicing-always':
        return require('@/assets/audio/rejoicing-always.mp3');
      
      // Day 363: Living with Gratitude
      case 'living-with-gratitude':
        return require('@/assets/audio/living-with-gratitude.mp3');
      
      // Day 364: Abiding in God's Love
      case 'abiding-in-gods-love':
        return require('@/assets/audio/abiding-in-gods-love.mp3');
      
      // Day 365: The Year Ahead - Moving Forward
      case 'the-year-ahead-moving-forward':
        return require('@/assets/audio/the-year-ahead-moving-forward.mp3');
      
      default:
        // Audio file not registered - won't show player
        console.log(`ℹ️  No audio file registered for: ${fileName}.mp3`);
        return null;
    }
  } catch (error) {
    console.warn(`⚠️  Could not load audio file: ${fileName}.mp3`, error);
    return null;
  }
}

/**
 * Get audio source by day of year (1-365)
 */
export function getAudioSourceByDayOfYear(dayOfYear: number): any | null {
  // Import devotionals to get the title for the day
  const { devotionals } = require('@/constants/devotionals');
  const index = (dayOfYear - 1) % 365;
  const devotion = devotionals[index];
  
  if (!devotion) return null;
  
  return getDynamicAudioSource(devotion.title);
}
